import type { Preset } from '../types.js';

export const ANIMATED_SERIES_PRESETS: Preset[] = [
  // ── Ahsoka Tano (Clone Wars) ── Green main + yellow-green shoto
  {
    id: 'animated-ahsoka-cw-green',
    name: 'Ahsoka Tano (Clone Wars - Green)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Ahsoka\'s primary green lightsaber from The Clone Wars. Vivid emerald blade with a warm shimmer reminiscent of her early Padawan years.',
    hiltNotes: 'Custom curved hilt gifted by Anakin Skywalker.',
    config: {
      name: 'AhsokaCWGreen',
      baseColor: { r: 0, g: 220, b: 40 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 200, g: 255, b: 180 },
      blastColor: { r: 180, g: 255, b: 120 },
      dragColor: { r: 255, g: 200, b: 0 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.15,
      ledCount: 144,
      sparkSize: 0.4,
      swingFxIntensity: 0.4,
    },
  },
  {
    id: 'animated-ahsoka-cw-yellowgreen',
    name: 'Ahsoka Tano (Clone Wars - Yellow-Green Shoto)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    description:
      'Ahsoka\'s shorter yellow-green shoto saber used in her Jar\'Kai dual-wielding style.',
    hiltNotes: 'Compact shoto hilt for reverse-grip.',
    config: {
      name: 'AhsokaCWShoto',
      baseColor: { r: 128, g: 235, b: 20 },
      clashColor: { r: 255, g: 255, b: 180 },
      lockupColor: { r: 200, g: 240, b: 100 },
      blastColor: { r: 180, g: 255, b: 80 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 250,
      retractionMs: 350,
      shimmer: 0.12,
      ledCount: 100,
    },
  },

  // ── Ahsoka Tano (Rebels / Mandalorian) ── White dual blades
  {
    id: 'animated-ahsoka-rebels-white',
    name: 'Ahsoka Tano (Rebels/Mandalorian - White)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Purified white blades carried by Ahsoka after leaving the Jedi Order. Brilliant silver-white with a subtle cool shimmer.',
    hiltNotes: 'Curved hilts with white wrappings, based on purified kyber crystals from an Inquisitor.',
    config: {
      name: 'AhsokaWhite',
      baseColor: { r: 240, g: 240, b: 250 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 180, g: 200, b: 240 },
      blastColor: { r: 220, g: 235, b: 255 },
      dragColor: { r: 180, g: 190, b: 220 },
      style: 'photon',
      ignition: 'summon',
      retraction: 'evaporate',
      ignitionMs: 280,
      retractionMs: 450,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Pre Vizsla (Darksaber) ──
  {
    id: 'animated-pre-vizsla-darksaber',
    name: 'Pre Vizsla (Darksaber)',
    character: 'Pre Vizsla',
    era: 'animated',
    affiliation: 'other',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'The ancient Mandalorian Darksaber: a flat, katana-shaped blade with a bright white core surrounded by a dark energy edge.',
    hiltNotes: 'Unique rectangular hilt of Mandalorian beskar, the only one of its kind.',
    topologyNotes: 'Flat blade profile rather than cylindrical. White core with dark black-purple corona.',
    config: {
      name: 'Darksaber',
      baseColor: { r: 255, g: 255, b: 255 },
      clashColor: { r: 160, g: 180, b: 255 },
      lockupColor: { r: 100, g: 120, b: 200 },
      blastColor: { r: 200, g: 210, b: 255 },
      style: 'darksaber',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 300,
      shimmer: 0.3,
      ledCount: 144,
    },
  },

  // ── Ezra Bridger ──
  {
    id: 'animated-ezra-bridger-blue',
    name: 'Ezra Bridger (Blue)',
    character: 'Ezra Bridger',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Ezra\'s second lightsaber — a traditional blue blade replacing his earlier blaster-saber hybrid.',
    hiltNotes: 'Cross-guard style hilt built on Atollon. First hilt was a blaster hybrid destroyed by Vader.',
    config: {
      name: 'EzraBridger',
      baseColor: { r: 20, g: 80, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 150, g: 180, b: 255 },
      blastColor: { r: 100, g: 160, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 400,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Ezra Bridger (Blaster Hybrid) ──
  {
    id: 'animated-ezra-bridger-hybrid',
    name: 'Ezra Bridger (Blaster Hybrid)',
    character: 'Ezra Bridger',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    description:
      'Ezra\'s first lightsaber — a unique blaster-saber hybrid built from spare parts on Lothal. A scrappy, street-kid weapon.',
    hiltNotes: 'Compact blaster/saber hybrid with integrated stun blaster. Destroyed by Vader on Malachor.',
    config: {
      name: 'EzraHybrid',
      baseColor: { r: 30, g: 100, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 120, g: 170, b: 255 },
      style: 'stable',
      ignition: 'stutter',
      retraction: 'standard',
      ignitionMs: 400,
      retractionMs: 350,
      shimmer: 0.12,
      ledCount: 144,
    },
  },

  // ── Kanan Jarrus ──
  {
    id: 'animated-kanan-jarrus-blue',
    name: 'Kanan Jarrus (Blue)',
    character: 'Kanan Jarrus',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Caleb Dume\'s blue lightsaber, carried through the dark times and wielded throughout the Rebellion on Lothal.',
    hiltNotes: 'Two-piece modular hilt that separates for concealment.',
    config: {
      name: 'KananJarrus',
      baseColor: { r: 30, g: 100, b: 255 },
      clashColor: { r: 220, g: 230, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 120, g: 170, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'summon',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Grand Inquisitor ──
  {
    id: 'animated-grand-inquisitor-red',
    name: 'Grand Inquisitor (Red)',
    character: 'Grand Inquisitor',
    era: 'animated',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'The Grand Inquisitor\'s spinning double-bladed red lightsaber. Menacing crimson with aggressive flicker.',
    hiltNotes: 'Crescent-shaped spinning hilt with dual emitters. Capable of helicopter flight mode.',
    config: {
      name: 'GrandInquisitor',
      baseColor: { r: 240, g: 20, b: 10 },
      clashColor: { r: 255, g: 200, b: 150 },
      lockupColor: { r: 255, g: 100, b: 50 },
      blastColor: { r: 255, g: 80, b: 30 },
      dragColor: { r: 255, g: 60, b: 0 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'dissolve',
      ignitionMs: 200,
      retractionMs: 250,
      shimmer: 0.35,
      ledCount: 144,
      noiseLevel: 0.08,
      swingFxIntensity: 0.45,
    },
  },

  // ── Second Sister ──
  {
    id: 'animated-second-sister-red',
    name: 'Second Sister (Red)',
    character: 'Second Sister',
    era: 'animated',
    affiliation: 'sith',
    tier: 'base',
    screenAccurate: true,
    description:
      'Trilla Suduri as the Second Sister. Deep blood-red blade with a controlled, precise flicker.',
    hiltNotes: 'Standard Inquisitor spinning hilt.',
    config: {
      name: 'SecondSister',
      baseColor: { r: 220, g: 0, b: 10 },
      clashColor: { r: 255, g: 180, b: 140 },
      lockupColor: { r: 255, g: 80, b: 60 },
      blastColor: { r: 255, g: 60, b: 40 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 220,
      retractionMs: 280,
      shimmer: 0.25,
      ledCount: 144,
      noiseLevel: 0.05,
    },
  },

  // ── Third Sister / Reva ──
  {
    id: 'animated-third-sister-reva-red',
    name: 'Third Sister / Reva (Red)',
    character: 'Reva Sevander',
    era: 'animated',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Reva\'s aggressive red double-bladed saber. Fierce scarlet with volatile energy matching her volatile temperament.',
    hiltNotes: 'Double-bladed Inquisitor spinning hilt, often used as a single blade.',
    config: {
      name: 'ThirdSisterReva',
      baseColor: { r: 255, g: 20, b: 10 },
      clashColor: { r: 255, g: 220, b: 180 },
      lockupColor: { r: 255, g: 120, b: 70 },
      blastColor: { r: 255, g: 90, b: 50 },
      dragColor: { r: 255, g: 80, b: 0 },
      style: 'unstable',
      ignition: 'fracture',
      retraction: 'flickerOut',
      ignitionMs: 180,
      retractionMs: 300,
      shimmer: 0.28,
      ledCount: 144,
      noiseLevel: 0.1,
      swingFxIntensity: 0.5,
    },
  },

  // ── Fifth Brother ──
  {
    id: 'animated-fifth-brother-red',
    name: 'Fifth Brother (Red)',
    character: 'Fifth Brother',
    era: 'animated',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'The Fifth Brother\'s imposing red blade. A deep, powerful crimson with heavy weight.',
    hiltNotes: 'Large Inquisitor spinning hilt matching his brutish fighting style.',
    config: {
      name: 'FifthBrother',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 255, g: 160, b: 120 },
      lockupColor: { r: 255, g: 70, b: 40 },
      blastColor: { r: 255, g: 50, b: 20 },
      dragColor: { r: 255, g: 100, b: 0 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 260,
      retractionMs: 300,
      shimmer: 0.18,
      ledCount: 144,
      noiseLevel: 0.04,
      swingFxIntensity: 0.3,
    },
  },

  // ── Seventh Sister ──
  {
    id: 'animated-seventh-sister-red',
    name: 'Seventh Sister (Red)',
    character: 'Seventh Sister',
    era: 'animated',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'The Seventh Sister\'s sleek red blade. A sharp, vivid crimson with a refined, almost surgical feel.',
    hiltNotes: 'Compact Inquisitor spinning hilt suited to her agile fighting style.',
    config: {
      name: 'SeventhSister',
      baseColor: { r: 240, g: 10, b: 20 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 70, b: 50 },
      blastColor: { r: 255, g: 70, b: 50 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 190,
      retractionMs: 240,
      shimmer: 0.15,
      ledCount: 144,
      noiseLevel: 0.03,
      swingFxIntensity: 0.4,
    },
  },

  // ── Sabine Wren (Darksaber) ──
  {
    id: 'animated-sabine-wren-darksaber',
    name: 'Sabine Wren (Darksaber)',
    character: 'Sabine Wren',
    era: 'animated',
    affiliation: 'other',
    tier: 'base',
    screenAccurate: true,
    description:
      'The Darksaber wielded by Sabine Wren after claiming it in Mandalorian tradition. Same ancient blade, new warrior.',
    hiltNotes: 'Mandalorian Darksaber — identical hilt to Pre Vizsla\'s, passed through combat.',
    topologyNotes: 'Flat blade profile. White core with dark energy corona.',
    config: {
      name: 'SabineDarksaber',
      baseColor: { r: 255, g: 255, b: 255 },
      clashColor: { r: 150, g: 170, b: 255 },
      lockupColor: { r: 110, g: 130, b: 210 },
      blastColor: { r: 190, g: 200, b: 255 },
      style: 'darksaber',
      ignition: 'wipe',
      retraction: 'fadeout',
      ignitionMs: 220,
      retractionMs: 350,
      shimmer: 0.32,
      ledCount: 144,
    },
  },

  // ── Sabine Wren (Ahsoka series) ──
  {
    id: 'animated-sabine-wren-blue',
    name: 'Sabine Wren (Blue - Ahsoka series)',
    character: 'Sabine Wren',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Sabine\'s blue-bladed lightsaber from the Ahsoka series, trained by Ahsoka Tano. A bright azure blade in the hands of a Mandalorian learning the Jedi way.',
    hiltNotes: 'Ezra\'s lightsaber passed to Sabine. Modified with Mandalorian personal touches.',
    config: {
      name: 'SabineBlue',
      baseColor: { r: 20, g: 80, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 150, g: 180, b: 255 },
      blastColor: { r: 100, g: 160, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 380,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Cal Kestis (Blue Default) ──
  {
    id: 'animated-cal-kestis-blue',
    name: 'Cal Kestis (Blue)',
    character: 'Cal Kestis',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    description:
      'Cal Kestis\'s default blue lightsaber from Jedi: Fallen Order — the blade on first ignition and in marketing/box art. A bright, hopeful blade. (Cyan is a customization unlock rather than the default.)',
    hiltNotes: 'Jaro Tapal\'s repaired hilt, later rebuilt on Bogano.',
    config: {
      name: 'CalKestisBlue',
      baseColor: { r: 30, g: 100, b: 255 },
      clashColor: { r: 200, g: 230, b: 255 },
      lockupColor: { r: 140, g: 200, b: 255 },
      blastColor: { r: 100, g: 180, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
      sparkSize: 0.5,
      swingFxIntensity: 0.35,
    },
  },

  // ── Cere Junda ──
  {
    id: 'animated-cere-junda-blue',
    name: 'Cere Junda (Blue)',
    character: 'Cere Junda',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: false,
    description:
      'Cere Junda\'s blue lightsaber. A steady, resolute blade reflecting her hard-won wisdom.',
    hiltNotes: 'Restored Jedi hilt reclaimed after years in hiding.',
    config: {
      name: 'CereJunda',
      baseColor: { r: 40, g: 110, b: 255 },
      clashColor: { r: 210, g: 225, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 120, g: 170, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 420,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Baylan Skoll ──
  {
    id: 'animated-baylan-skoll-orange',
    name: 'Baylan Skoll (Orange-Red)',
    character: 'Baylan Skoll',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Baylan Skoll\'s distinctive orange-red blade. A warm, magmatic hue between Jedi and Sith — fitting for a fallen master seeking something beyond both orders.',
    hiltNotes: 'Ornate hilt of older Jedi design, well-maintained despite years away from the Order.',
    config: {
      name: 'BaylanSkoll',
      baseColor: { r: 255, g: 110, b: 20 },
      clashColor: { r: 255, g: 220, b: 160 },
      lockupColor: { r: 255, g: 150, b: 80 },
      blastColor: { r: 255, g: 130, b: 50 },
      dragColor: { r: 200, g: 60, b: 0 },
      style: 'cinder',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 380,
      retractionMs: 440,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.05,
    },
  },

  // ── Shin Hati ──
  {
    id: 'animated-shin-hati-orange',
    name: 'Shin Hati (Orange)',
    character: 'Shin Hati',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Shin Hati\'s orange lightsaber. A sharp, intense amber-orange blade wielded by Baylan Skoll\'s apprentice with cold precision.',
    hiltNotes: 'Simple, functional hilt reflecting her pragmatic training under Baylan.',
    config: {
      name: 'ShinHatiAnimated',
      baseColor: { r: 255, g: 120, b: 0 },
      clashColor: { r: 255, g: 225, b: 160 },
      lockupColor: { r: 255, g: 170, b: 70 },
      blastColor: { r: 255, g: 150, b: 30 },
      dragColor: { r: 200, g: 80, b: 0 },
      style: 'cinder',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.04,
    },
  },

  // ── Din Djarin (Darksaber) ──
  {
    id: 'animated-din-djarin-darksaber',
    name: 'Din Djarin (Darksaber)',
    character: 'Din Djarin',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: true,
    description: 'The Mandalorian struggles to wield the ancient Darksaber. Crackling, unstable white-core blade with a dark edge, reflecting his lack of training.',
    hiltNotes: 'Ancient Mandalorian Darksaber — flat blade, angular hilt with black finish.',
    config: {
      name: 'DinDarksaber',
      baseColor: { r: 255, g: 255, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 180, g: 180, b: 200 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'darksaber',
      ignition: 'stutter',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ── Ahsoka Tano (Live-Action) ──
  {
    id: 'animated-ahsoka-liveaction-white',
    name: 'Ahsoka Tano (Live-Action)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description: 'The Ahsoka series — pure white blades with a photon particle stream effect, representing her fully realized connection to the Force.',
    hiltNotes: 'Custom curved hilts with white leather wrapping, evolved from Rebels design.',
    config: {
      name: 'AhsokaLive',
      baseColor: { r: 240, g: 245, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 240 },
      blastColor: { r: 255, g: 255, b: 255 },
      dragColor: { r: 180, g: 190, b: 210 },
      style: 'photon',
      ignition: 'center',
      retraction: 'fadeout',
      ignitionMs: 250,
      retractionMs: 500,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.25,
      noiseLevel: 0.02,
    },
  },

  // ── Huyang ──
  {
    id: 'animated-huyang',
    name: 'Huyang (Droid Architect)',
    character: 'Huyang',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: false,
    description:
      'Speculative interpretation of a personal lightsaber for the ancient droid saber-architect. Huyang is not shown wielding a lightsaber in on-screen Star Wars media — he is the Jedi Order\'s saber construction expert. A clean, precise blue reflecting 25,000 years of craftsmanship.',
    hiltNotes: 'Speculative personal lightsaber for the ancient droid — canonically he is the saber architect, not a wielder.',
    config: {
      name: 'Huyang',
      baseColor: { r: 30, g: 120, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 130, g: 180, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 350,
      shimmer: 0.03,
      ledCount: 144,
    },
  },

  // ── Grogu (speculative) ──
  {
    id: 'animated-grogu',
    name: 'Grogu (Armored Youngling)',
    character: 'Grogu',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    description:
      'Grogu\'s tiny lightsaber built by the Armorer. A pure, bright green shoto blade — small but fierce, just like its wielder.',
    hiltNotes: 'Beskar-forged shoto hilt, built by the Armorer with a rancor tooth accent.',
    config: {
      name: 'Grogu',
      baseColor: { r: 0, g: 230, b: 30 },
      clashColor: { r: 200, g: 255, b: 200 },
      lockupColor: { r: 180, g: 240, b: 180 },
      blastColor: { r: 150, g: 255, b: 150 },
      style: 'pulse',
      ignition: 'spark',
      retraction: 'scroll',
      ignitionMs: 250,
      retractionMs: 300,
      shimmer: 0.1,
      ledCount: 100,
      pulseSpeed: 0.8,
      pulseMinBright: 0.6,
      swingFxIntensity: 0.4,
    },
  },
];
