import type { Preset } from '../types.js';

export const ANIMATED_SERIES_PRESETS: Preset[] = [
  // ── Ahsoka Tano (Clone Wars) ── Green main + yellow-green shoto
  {
    id: 'animated-ahsoka-cw-green',
    name: 'Ahsoka Tano (Clone Wars - Green)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Ahsoka\'s primary green lightsaber from The Clone Wars. Vivid emerald blade with a warm shimmer reminiscent of her early Padawan years.',
    hiltNotes: 'Custom curved hilt gifted by Anakin Skywalker.',
    config: {
      name: 'AhsokaCWGreen',
      baseColor: { r: 0, g: 220, b: 40 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 200, g: 255, b: 180 },
      blastColor: { r: 180, g: 255, b: 120 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'animated-ahsoka-cw-yellowgreen',
    name: 'Ahsoka Tano (Clone Wars - Yellow-Green Shoto)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Ahsoka\'s shorter yellow-green shoto saber used in her Jar\'Kai dual-wielding style.',
    hiltNotes: 'Compact shoto hilt for reverse-grip.',
    config: {
      name: 'AhsokaCWShoto',
      baseColor: { r: 128, g: 235, b: 20 },
      clashColor: { r: 255, g: 255, b: 180 },
      lockupColor: { r: 200, g: 240, b: 100 },
      blastColor: { r: 180, g: 255, b: 80 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 250,
      retractionMs: 350,
      shimmer: 0.12,
      ledCount: 100,
    },
  },

  // ── Ahsoka Tano (Rebels / Mandalorian) ── White dual blades
  {
    id: 'animated-ahsoka-rebels-white',
    name: 'Ahsoka Tano (Rebels/Mandalorian - White)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'neutral',
    description:
      'Purified white blades carried by Ahsoka after leaving the Jedi Order. Brilliant silver-white with a subtle cool shimmer.',
    hiltNotes: 'Curved hilts with white wrappings, based on purified kyber crystals from an Inquisitor.',
    config: {
      name: 'AhsokaWhite',
      baseColor: { r: 240, g: 245, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 180, g: 200, b: 240 },
      blastColor: { r: 220, g: 235, b: 255 },
      style: 'rotoscope',
      ignition: 'center',
      retraction: 'fadeout',
      ignitionMs: 280,
      retractionMs: 450,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Pre Vizsla (Darksaber) ──
  {
    id: 'animated-pre-vizsla-darksaber',
    name: 'Pre Vizsla (Darksaber)',
    character: 'Pre Vizsla',
    era: 'animated',
    affiliation: 'other',
    description:
      'The ancient Mandalorian Darksaber: a flat, katana-shaped blade with a bright white core surrounded by a dark energy edge.',
    hiltNotes: 'Unique rectangular hilt of Mandalorian beskar, the only one of its kind.',
    topologyNotes: 'Flat blade profile rather than cylindrical. White core with dark black-purple corona.',
    config: {
      name: 'Darksaber',
      baseColor: { r: 245, g: 248, b: 255 },
      clashColor: { r: 160, g: 180, b: 255 },
      lockupColor: { r: 100, g: 120, b: 200 },
      blastColor: { r: 200, g: 210, b: 255 },
      style: 'unstable',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 300,
      shimmer: 0.3,
      ledCount: 144,
      darkCore: true,
      coreColor: { r: 10, g: 5, b: 20 },
    },
  },

  // ── Ezra Bridger ──
  {
    id: 'animated-ezra-bridger-blue',
    name: 'Ezra Bridger (Blue)',
    character: 'Ezra Bridger',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Ezra\'s second lightsaber — a traditional blue blade replacing his earlier blaster-saber hybrid.',
    hiltNotes: 'Cross-guard style hilt built on Atollon. First hilt was a blaster hybrid destroyed by Vader.',
    config: {
      name: 'EzraBridger',
      baseColor: { r: 20, g: 80, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 150, g: 180, b: 255 },
      blastColor: { r: 100, g: 160, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 400,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Kanan Jarrus ──
  {
    id: 'animated-kanan-jarrus-blue',
    name: 'Kanan Jarrus (Blue)',
    character: 'Kanan Jarrus',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Caleb Dume\'s blue lightsaber, carried through the dark times and wielded throughout the Rebellion on Lothal.',
    hiltNotes: 'Two-piece modular hilt that separates for concealment.',
    config: {
      name: 'KananJarrus',
      baseColor: { r: 30, g: 100, b: 255 },
      clashColor: { r: 220, g: 230, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 120, g: 170, b: 255 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Grand Inquisitor ──
  {
    id: 'animated-grand-inquisitor-red',
    name: 'Grand Inquisitor (Red)',
    character: 'Grand Inquisitor',
    era: 'animated',
    affiliation: 'sith',
    description:
      'The Grand Inquisitor\'s spinning double-bladed red lightsaber. Menacing crimson with aggressive flicker.',
    hiltNotes: 'Crescent-shaped spinning hilt with dual emitters. Capable of helicopter flight mode.',
    config: {
      name: 'GrandInquisitor',
      baseColor: { r: 255, g: 10, b: 0 },
      clashColor: { r: 255, g: 200, b: 150 },
      lockupColor: { r: 255, g: 100, b: 50 },
      blastColor: { r: 255, g: 80, b: 30 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 200,
      retractionMs: 250,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ── Second Sister ──
  {
    id: 'animated-second-sister-red',
    name: 'Second Sister (Red)',
    character: 'Second Sister',
    era: 'animated',
    affiliation: 'sith',
    description:
      'Trilla Suduri as the Second Sister. Deep blood-red blade with a controlled, precise flicker.',
    hiltNotes: 'Standard Inquisitor spinning hilt.',
    config: {
      name: 'SecondSister',
      baseColor: { r: 220, g: 0, b: 10 },
      clashColor: { r: 255, g: 180, b: 140 },
      lockupColor: { r: 255, g: 80, b: 60 },
      blastColor: { r: 255, g: 60, b: 40 },
      style: 'stable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 220,
      retractionMs: 280,
      shimmer: 0.18,
      ledCount: 144,
    },
  },

  // ── Third Sister / Reva ──
  {
    id: 'animated-third-sister-reva-red',
    name: 'Third Sister / Reva (Red)',
    character: 'Reva Sevander',
    era: 'animated',
    affiliation: 'sith',
    description:
      'Reva\'s aggressive red double-bladed saber. Fierce scarlet with volatile energy matching her volatile temperament.',
    hiltNotes: 'Double-bladed Inquisitor spinning hilt, often used as a single blade.',
    config: {
      name: 'ThirdSisterReva',
      baseColor: { r: 255, g: 20, b: 10 },
      clashColor: { r: 255, g: 220, b: 180 },
      lockupColor: { r: 255, g: 120, b: 70 },
      blastColor: { r: 255, g: 90, b: 50 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 180,
      retractionMs: 300,
      shimmer: 0.28,
      ledCount: 144,
    },
  },

  // ── Fifth Brother ──
  {
    id: 'animated-fifth-brother-red',
    name: 'Fifth Brother (Red)',
    character: 'Fifth Brother',
    era: 'animated',
    affiliation: 'sith',
    description:
      'The Fifth Brother\'s imposing red blade. A deep, powerful crimson with heavy weight.',
    hiltNotes: 'Large Inquisitor spinning hilt matching his brutish fighting style.',
    config: {
      name: 'FifthBrother',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 255, g: 160, b: 120 },
      lockupColor: { r: 255, g: 70, b: 40 },
      blastColor: { r: 255, g: 50, b: 20 },
      style: 'fire',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 260,
      retractionMs: 300,
      shimmer: 0.15,
      ledCount: 144,
      fireSize: 0.5,
      sparkRate: 0.4,
      heatSpread: 0.5,
    },
  },

  // ── Seventh Sister ──
  {
    id: 'animated-seventh-sister-red',
    name: 'Seventh Sister (Red)',
    character: 'Seventh Sister',
    era: 'animated',
    affiliation: 'sith',
    description:
      'The Seventh Sister\'s sleek red blade. A sharp, vivid crimson with a refined, almost surgical feel.',
    hiltNotes: 'Compact Inquisitor spinning hilt suited to her agile fighting style.',
    config: {
      name: 'SeventhSister',
      baseColor: { r: 240, g: 10, b: 20 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 90, b: 70 },
      blastColor: { r: 255, g: 70, b: 50 },
      style: 'plasma',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 190,
      retractionMs: 240,
      shimmer: 0.12,
      ledCount: 144,
      frequency: 1.5,
      phaseSpeed: 1.0,
    },
  },

  // ── Sabine Wren (Darksaber) ──
  {
    id: 'animated-sabine-wren-darksaber',
    name: 'Sabine Wren (Darksaber)',
    character: 'Sabine Wren',
    era: 'animated',
    affiliation: 'other',
    description:
      'The Darksaber wielded by Sabine Wren after claiming it in Mandalorian tradition. Same ancient blade, new warrior.',
    hiltNotes: 'Mandalorian Darksaber — identical hilt to Pre Vizsla\'s, passed through combat.',
    topologyNotes: 'Flat blade profile. White core with dark energy corona.',
    config: {
      name: 'SabineDarksaber',
      baseColor: { r: 240, g: 245, b: 255 },
      clashColor: { r: 150, g: 170, b: 255 },
      lockupColor: { r: 110, g: 130, b: 210 },
      blastColor: { r: 190, g: 200, b: 255 },
      style: 'unstable',
      ignition: 'wipe',
      retraction: 'fadeout',
      ignitionMs: 220,
      retractionMs: 350,
      shimmer: 0.32,
      ledCount: 144,
      darkCore: true,
      coreColor: { r: 8, g: 4, b: 18 },
    },
  },

  // ── Cal Kestis (Blue/Cyan Default) ──
  {
    id: 'animated-cal-kestis-blue',
    name: 'Cal Kestis (Blue/Cyan)',
    character: 'Cal Kestis',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Cal Kestis\'s default cyan-blue lightsaber from Jedi: Fallen Order. A bright, hopeful blade.',
    hiltNotes: 'Jaro Tapal\'s repaired hilt, later rebuilt on Bogano.',
    config: {
      name: 'CalKestisCyan',
      baseColor: { r: 0, g: 160, b: 255 },
      clashColor: { r: 200, g: 230, b: 255 },
      lockupColor: { r: 140, g: 200, b: 255 },
      blastColor: { r: 100, g: 180, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Cere Junda ──
  {
    id: 'animated-cere-junda-blue',
    name: 'Cere Junda (Blue)',
    character: 'Cere Junda',
    era: 'animated',
    affiliation: 'jedi',
    description:
      'Cere Junda\'s blue lightsaber. A steady, resolute blade reflecting her hard-won wisdom.',
    hiltNotes: 'Restored Jedi hilt reclaimed after years in hiding.',
    config: {
      name: 'CereJunda',
      baseColor: { r: 40, g: 110, b: 255 },
      clashColor: { r: 210, g: 225, b: 255 },
      lockupColor: { r: 160, g: 190, b: 255 },
      blastColor: { r: 120, g: 170, b: 255 },
      style: 'rotoscope',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 350,
      retractionMs: 420,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Baylan Skoll ──
  {
    id: 'animated-baylan-skoll-orange',
    name: 'Baylan Skoll (Orange-Red)',
    character: 'Baylan Skoll',
    era: 'animated',
    affiliation: 'neutral',
    description:
      'Baylan Skoll\'s distinctive orange-red blade. A warm, magmatic hue between Jedi and Sith — fitting for a fallen master seeking something beyond both orders.',
    hiltNotes: 'Ornate hilt of older Jedi design, well-maintained despite years away from the Order.',
    config: {
      name: 'BaylanSkoll',
      baseColor: { r: 255, g: 90, b: 10 },
      clashColor: { r: 255, g: 220, b: 160 },
      lockupColor: { r: 255, g: 150, b: 80 },
      blastColor: { r: 255, g: 130, b: 50 },
      style: 'cinder',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 380,
      retractionMs: 440,
      shimmer: 0.14,
      ledCount: 144,
    },
  },

  // ── Din Djarin (Darksaber) ──
  {
    id: 'animated-din-djarin-darksaber',
    name: 'Din Djarin (Darksaber)',
    character: 'Din Djarin',
    era: 'animated',
    affiliation: 'neutral',
    description: 'The Mandalorian struggles to wield the ancient Darksaber. Crackling, unstable white-core blade with a dark edge, reflecting his lack of training.',
    hiltNotes: 'Ancient Mandalorian Darksaber — flat blade, angular hilt with black finish.',
    config: {
      name: 'DinDarksaber',
      baseColor: { r: 200, g: 200, b: 210 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 180, g: 180, b: 200 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'unstable',
      ignition: 'stutter',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.35,
      ledCount: 144,
      flicker: 0.6,
    },
  },

  // ── Ahsoka Tano (Live-Action) ──
  {
    id: 'animated-ahsoka-liveaction-white',
    name: 'Ahsoka Tano (Live-Action)',
    character: 'Ahsoka Tano',
    era: 'animated',
    affiliation: 'jedi',
    description: 'The Ahsoka series — pure white blades with a photon particle stream effect, representing her fully realized connection to the Force.',
    hiltNotes: 'Custom curved hilts with white leather wrapping, evolved from Rebels design.',
    config: {
      name: 'AhsokaLive',
      baseColor: { r: 240, g: 245, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 240 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'photon',
      ignition: 'center',
      retraction: 'fadeout',
      ignitionMs: 250,
      retractionMs: 500,
      shimmer: 0.06,
      ledCount: 144,
    },
  },

  // ── Morgan Elsbeth ──
  {
    id: 'animated-morgan-elsbeth-red',
    name: 'Morgan Elsbeth',
    character: 'Morgan Elsbeth',
    era: 'animated',
    affiliation: 'sith',
    description: 'Nightsister-linked blade forged with dark magick. Flickering red fire that burns with ancient power.',
    hiltNotes: 'Curved hilt with Nightsister runes, blade emitter wrapped in red energy.',
    config: {
      name: 'MorganElsbeth',
      baseColor: { r: 220, g: 20, b: 20 },
      clashColor: { r: 255, g: 180, b: 120 },
      lockupColor: { r: 255, g: 100, b: 50 },
      blastColor: { r: 255, g: 200, b: 150 },
      style: 'fire',
      ignition: 'wipe',
      retraction: 'fadeout',
      ignitionMs: 350,
      retractionMs: 600,
      shimmer: 0.12,
      ledCount: 144,
      fireSize: 0.5,
      sparkRate: 0.4,
      heatSpread: 0.6,
    },
  },
];
