import type { Preset } from '../types.js';

/**
 * Creative, fun, and community-inspired presets.
 * Categories: In-Universe Deep Cuts, Tongue-in-Cheek, Crossover/Pop Culture,
 * Nature/Elements, and Community Classics.
 */
export const CREATIVE_COMMUNITY_PRESETS: Preset[] = [
  // ════════════════════════════════════════════
  // IN-UNIVERSE DEEP CUTS
  // ════════════════════════════════════════════

  {
    id: 'creative-temple-sentinel',
    name: 'Temple Sentinel',
    character: 'Jedi Temple Guard',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    description: 'The Jedi Temple Guard\'s rotating pike blade. Warm authoritative yellow with a solemn, steady pulse. Clash produces a blinding flash of golden white.',
    hiltNotes: 'Double-bladed pike with masked guard hilt design.',
    config: {
      name: 'TempleSentinel',
      baseColor: { r: 200, g: 180, b: 0 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 200, b: 50 },
      blastColor: { r: 255, g: 255, b: 100 },
      style: 'rotoscope',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 800,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-darksaber-deep',
    name: 'Darksaber (Crackling)',
    character: 'Darksaber',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    description: 'Jet-black core with a crackling white edge. High shimmer creates the irregular, living energy the Darksaber is known for. The blade fights you.',
    hiltNotes: 'Ancient Mandalorian hilt with angular crossguard shape.',
    config: {
      name: 'DarksaberCrackling',
      baseColor: { r: 10, g: 10, b: 10 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 180, g: 180, b: 200 },
      blastColor: { r: 200, g: 200, b: 255 },
      style: 'unstable',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-kyber-bleeding',
    name: 'Kyber Bleeding',
    character: 'Corrupted Crystal',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'A Jedi crystal being corrupted by the dark side. Starts pure blue, slowly bleeds to crimson. Each clash accelerates the corruption. The fall made visible.',
    config: {
      name: 'KyberBleeding',
      baseColor: { r: 30, g: 80, b: 220 },
      clashColor: { r: 180, g: 20, b: 20 },
      lockupColor: { r: 120, g: 30, b: 100 },
      blastColor: { r: 200, g: 50, b: 50 },
      style: 'gradient',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-purification',
    name: 'Crystal Purification',
    character: 'Redeemed Crystal',
    era: 'animated',
    affiliation: 'jedi',
    tier: 'detailed',
    description: 'Red healing to brilliant white. The inverse of bleeding — a crystal redeemed through the Force. Clash reveals the white light breaking through.',
    config: {
      name: 'CrystalPurification',
      baseColor: { r: 200, g: 30, b: 30 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 220, g: 180, b: 200 },
      blastColor: { r: 255, g: 200, b: 220 },
      style: 'gradient',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1200,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-sith-alchemy',
    name: 'Sith Alchemy',
    character: 'Ancient Sith',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'Ancient dark-side forge blade. Deep arterial red with roiling plasma texture. Lockup summons violet Sith lightning. This blade was never meant to exist.',
    config: {
      name: 'SithAlchemy',
      baseColor: { r: 100, g: 0, b: 0 },
      clashColor: { r: 180, g: 0, b: 180 },
      lockupColor: { r: 60, g: 0, b: 60 },
      blastColor: { r: 255, g: 50, b: 0 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 700,
      retractionMs: 800,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-first-lightsaber',
    name: 'First Lightsaber',
    character: 'Youngling',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    description: 'A youngling\'s shaky first ignition. High instability, nervous flicker, long hesitant startup. The blade sputters and wavers but holds. Everyone starts somewhere.',
    config: {
      name: 'FirstLightsaber',
      baseColor: { r: 50, g: 140, b: 255 },
      clashColor: { r: 200, g: 200, b: 255 },
      lockupColor: { r: 100, g: 180, b: 255 },
      blastColor: { r: 150, g: 200, b: 255 },
      style: 'unstable',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1500,
      retractionMs: 500,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-beskar-reflection',
    name: 'Beskar Reflection',
    character: 'Mandalorian',
    era: 'animated',
    affiliation: 'neutral',
    tier: 'detailed',
    description: 'Mandalorian-wielded blade with metallic silver-blue sheen. Prismatic light plays across the surface like beskar catching firelight. Clash sparks orange like forged metal.',
    config: {
      name: 'BeskarReflection',
      baseColor: { r: 160, g: 170, b: 180 },
      clashColor: { r: 255, g: 200, b: 50 },
      lockupColor: { r: 200, g: 200, b: 210 },
      blastColor: { r: 255, g: 150, b: 0 },
      style: 'prism',
      ignition: 'wipe',
      retraction: 'scroll',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // TONGUE-IN-CHEEK / FUN
  // ════════════════════════════════════════════

  {
    id: 'creative-baguette-blade',
    name: 'Baguette Blade',
    character: 'Artisan Baker',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Artisan bread from hilt to tip. Golden-brown crust gradient with a warm bready glow. Clash sends flour everywhere. Oui oui.',
    config: {
      name: 'BaguetteBlade',
      baseColor: { r: 180, g: 130, b: 50 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 140, g: 90, b: 20 },
      blastColor: { r: 255, g: 220, b: 150 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 1000,
      retractionMs: 800,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-rgb-gamer',
    name: 'RGB Gamer',
    character: 'PC Master Race',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Maximum RGB at all times. Fast rainbow cycle with clash triggering the Blue Screen of Death. Your FPS has not improved.',
    config: {
      name: 'RGBGamer',
      baseColor: { r: 0, g: 255, b: 0 },
      clashColor: { r: 0, g: 0, b: 255 },
      lockupColor: { r: 255, g: 0, b: 0 },
      blastColor: { r: 0, g: 120, b: 215 },
      style: 'photon',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 200,
      shimmer: 0.8,
      ledCount: 144,
    },
  },
  {
    id: 'creative-battery-anxiety',
    name: 'Battery Anxiety',
    character: 'Low Power',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Starts full green. Slowly yellows, then reds, then flickers desperately. Retraction is a long, sad fadeout. Charge your saber, you fool.',
    config: {
      name: 'BatteryAnxiety',
      baseColor: { r: 50, g: 200, b: 50 },
      clashColor: { r: 200, g: 200, b: 0 },
      lockupColor: { r: 200, g: 100, b: 0 },
      blastColor: { r: 255, g: 0, b: 0 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 2000,
      retractionMs: 3000,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-disco-inferno',
    name: 'Disco Inferno',
    character: 'Disco Ball',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Sound-reactive color explosions. The blade IS the dance floor. Clash drops the beat. Best paired with a Disco font.',
    config: {
      name: 'DiscoInferno',
      baseColor: { r: 255, g: 0, b: 128 },
      clashColor: { r: 255, g: 255, b: 0 },
      lockupColor: { r: 0, g: 255, b: 255 },
      blastColor: { r: 255, g: 128, b: 0 },
      style: 'photon',
      ignition: 'center',
      retraction: 'shatter',
      ignitionMs: 300,
      retractionMs: 500,
      shimmer: 0.9,
      ledCount: 144,
    },
  },
  {
    id: 'creative-rave-saber',
    name: 'Rave Saber',
    character: 'Raver',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'UV purple with strobe-on-swing. High shimmer creates relentless pulse. Bring glow sticks.',
    config: {
      name: 'RaveSaber',
      baseColor: { r: 120, g: 0, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 0, b: 255 },
      blastColor: { r: 0, g: 255, b: 200 },
      style: 'pulse',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 250,
      retractionMs: 400,
      shimmer: 0.85,
      ledCount: 144,
    },
  },
  {
    id: 'creative-gender-reveal',
    name: 'Gender Reveal',
    character: 'Surprise',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Ignites pure white. First clash reveals pink, lockup reveals blue. Less property damage than the alternatives.',
    config: {
      name: 'GenderReveal',
      baseColor: { r: 240, g: 240, b: 240 },
      clashColor: { r: 255, g: 100, b: 150 },
      lockupColor: { r: 100, g: 150, b: 255 },
      blastColor: { r: 255, g: 200, b: 50 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-404-not-found',
    name: '404 Saber Not Found',
    character: 'Error',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Digital corruption made physical. Pixelated blocks, glitch artifacts, random color tearing. The blade renders incorrectly and that IS the point.',
    config: {
      name: '404NotFound',
      baseColor: { r: 0, g: 200, b: 0 },
      clashColor: { r: 255, g: 0, b: 0 },
      lockupColor: { r: 0, g: 0, b: 200 },
      blastColor: { r: 255, g: 255, b: 0 },
      style: 'crystalShatter',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 900,
      retractionMs: 600,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-christmas',
    name: 'Christmas Classic',
    character: 'Holiday',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Alternating red and green with gold lockup like tinsel. Blast sends snowflakes. Festive and aggressive.',
    config: {
      name: 'ChristmasClassic',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 0, g: 200, b: 0 },
      lockupColor: { r: 255, g: 215, b: 0 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 800,
      retractionMs: 800,
      shimmer: 0.25,
      ledCount: 144,
    },
  },
  {
    id: 'creative-spooky-season',
    name: 'Spooky Season',
    character: 'Halloween',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Jack-o-lantern orange fire with purple clash and ghostly green blast. Slow fadeout like a candle dying. Boo.',
    config: {
      name: 'SpookySeason',
      baseColor: { r: 200, g: 80, b: 0 },
      clashColor: { r: 100, g: 0, b: 180 },
      lockupColor: { r: 50, g: 0, b: 100 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'fire',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 700,
      retractionMs: 1200,
      shimmer: 0.4,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // CROSSOVER / POP CULTURE
  // ════════════════════════════════════════════

  {
    id: 'creative-energy-sword',
    name: 'Energy Sword',
    character: 'Covenant',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Split cyan-blue plasma blade inspired by alien energy weapons. Center ignition blooms outward. Clean, alien, lethal.',
    config: {
      name: 'EnergySword',
      baseColor: { r: 0, g: 150, b: 255 },
      clashColor: { r: 200, g: 255, b: 255 },
      lockupColor: { r: 0, g: 200, b: 255 },
      blastColor: { r: 100, g: 220, b: 255 },
      style: 'prism',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 400,
      retractionMs: 300,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dragon-glass',
    name: 'Dragon Glass',
    character: 'Ice & Fire',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Icy obsidian white-blue with fiery orange clash. Shatter retraction looks like glass breaking. Winter is handled.',
    config: {
      name: 'DragonGlass',
      baseColor: { r: 180, g: 220, b: 255 },
      clashColor: { r: 255, g: 100, b: 0 },
      lockupColor: { r: 255, g: 150, b: 50 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'crystalShatter',
      ignition: 'wipe',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-protosaber',
    name: 'Protosaber',
    character: 'Retro Sci-Fi',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Warm amber filament glow like a vintage vacuum tube. Cinder particles rise like old-tech energy. Retro sci-fi pulp magazine aesthetic.',
    config: {
      name: 'Protosaber',
      baseColor: { r: 200, g: 150, b: 50 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 180, g: 120, b: 30 },
      blastColor: { r: 255, g: 180, b: 80 },
      style: 'cinder',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1000,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-grid-runner',
    name: 'Grid Runner',
    character: 'Digital World',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Razor-sharp cyan with zero shimmer. Perfectly clean lines for that hard geometric digital aesthetic. The Grid demands precision.',
    config: {
      name: 'GridRunner',
      baseColor: { r: 0, g: 255, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 0, g: 200, b: 200 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'stable',
      ignition: 'wipe',
      retraction: 'scroll',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-digital-rain',
    name: 'Digital Rain',
    character: 'The Matrix',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Cascading green aurora-wave down the blade like falling code. There is no spoon, but there is this saber.',
    config: {
      name: 'DigitalRain',
      baseColor: { r: 0, g: 180, b: 0 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 100, b: 0 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 800,
      shimmer: 0.45,
      ledCount: 144,
    },
  },
  {
    id: 'creative-neon-noir',
    name: 'Neon Noir',
    character: 'Cyberpunk',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Hot pink fading to cyan at the tip. Cyberpunk neon in a rain-soaked alley. Clash inverts the gradient. Chrome and attitude.',
    config: {
      name: 'NeonNoir',
      baseColor: { r: 255, g: 0, b: 100 },
      clashColor: { r: 0, g: 255, b: 255 },
      lockupColor: { r: 200, g: 0, b: 200 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'gradient',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 600,
      shimmer: 0.35,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dark-energy',
    name: 'Dark Energy',
    character: 'Dark Fantasy',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'Deep violet-black plasma with chain lightning lockup. Dark fantasy energy blade for those who serve a darker power.',
    config: {
      name: 'DarkEnergy',
      baseColor: { r: 80, g: 0, b: 120 },
      clashColor: { r: 200, g: 100, b: 255 },
      lockupColor: { r: 60, g: 0, b: 80 },
      blastColor: { r: 150, g: 50, b: 200 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 700,
      shimmer: 0.55,
      ledCount: 144,
    },
  },
  {
    id: 'creative-power-grayskull',
    name: 'Power of Grayskull',
    character: 'Heroic Warrior',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Regal gold with silver clash. Dual-tone heroic blade. Simple, bold, legendary.',
    config: {
      name: 'PowerGrayskull',
      baseColor: { r: 220, g: 190, b: 50 },
      clashColor: { r: 200, g: 200, b: 210 },
      lockupColor: { r: 255, g: 215, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-companion-cube',
    name: 'Companion Cube',
    character: 'Portal',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Orange blade, blue clash. The cake is a lie but the style is real.',
    config: {
      name: 'CompanionCube',
      baseColor: { r: 255, g: 120, b: 0 },
      clashColor: { r: 0, g: 100, b: 255 },
      lockupColor: { r: 255, g: 80, b: 0 },
      blastColor: { r: 0, g: 150, b: 255 },
      style: 'pulse',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-pixel-miner',
    name: 'Pixel Miner',
    character: 'Block World',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Aqua diamond crystal shatter pattern. Blocky, chunky, satisfying. Blast sparkles like dropped XP.',
    config: {
      name: 'PixelMiner',
      baseColor: { r: 0, g: 200, b: 200 },
      clashColor: { r: 150, g: 150, b: 150 },
      lockupColor: { r: 0, g: 150, b: 150 },
      blastColor: { r: 50, g: 255, b: 50 },
      style: 'crystalShatter',
      ignition: 'scroll',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 400,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // NATURE / ELEMENTS
  // ════════════════════════════════════════════

  {
    id: 'creative-aurora-borealis',
    name: 'Aurora Borealis',
    character: 'Northern Lights',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Shifting green-cyan-purple waves. Slow, mesmerizing aurora movement along the blade. Best viewed in the dark with awe.',
    config: {
      name: 'AuroraBorealis',
      baseColor: { r: 0, g: 180, b: 100 },
      clashColor: { r: 100, g: 0, b: 200 },
      lockupColor: { r: 0, g: 255, b: 150 },
      blastColor: { r: 0, g: 150, b: 255 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-magma-core',
    name: 'Magma Core',
    character: 'Volcanic',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Black-red-orange with rising ember particles. The blade looks like cooled lava cracking to reveal molten fury beneath. Clash erupts in yellow fire.',
    config: {
      name: 'MagmaCore',
      baseColor: { r: 180, g: 30, b: 0 },
      clashColor: { r: 255, g: 200, b: 0 },
      lockupColor: { r: 100, g: 10, b: 0 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'cinder',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 800,
      retractionMs: 2000,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-abyssal',
    name: 'Abyssal',
    character: 'Deep Ocean',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Crushing deep-ocean blue with bioluminescent cyan pulses. Slow pulsing like something alive in the deep. Clash triggers a jellyfish flash.',
    config: {
      name: 'Abyssal',
      baseColor: { r: 0, g: 20, b: 80 },
      clashColor: { r: 0, g: 255, b: 200 },
      lockupColor: { r: 0, g: 50, b: 120 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'pulse',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1200,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-lightning-storm',
    name: 'Lightning Storm',
    character: 'Tempest',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'White-purple with extreme instability creating constant crackling. High shimmer makes this blade feel like barely-contained electricity.',
    config: {
      name: 'LightningStorm',
      baseColor: { r: 200, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 150, g: 100, b: 255 },
      blastColor: { r: 180, g: 150, b: 255 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.75,
      ledCount: 144,
    },
  },
  {
    id: 'creative-permafrost',
    name: 'Permafrost',
    character: 'Ice',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Icy pale blue with crystalline fracture patterns. Clash creates white flash like ice cracking. Shatter retraction breaks the frozen blade.',
    config: {
      name: 'Permafrost',
      baseColor: { r: 150, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 100, g: 150, b: 220 },
      blastColor: { r: 200, g: 230, b: 255 },
      style: 'crystalShatter',
      ignition: 'wipe',
      retraction: 'shatter',
      ignitionMs: 700,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-solar-flare',
    name: 'Solar Flare',
    character: 'Sun',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Blinding yellow-white fire with orange corona. Solar prominence dynamics. Look directly at this blade and regret it.',
    config: {
      name: 'SolarFlare',
      baseColor: { r: 255, g: 220, b: 100 },
      clashColor: { r: 255, g: 150, b: 0 },
      lockupColor: { r: 255, g: 180, b: 50 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'fire',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 800,
      shimmer: 0.4,
      ledCount: 144,
    },
  },
  {
    id: 'creative-nebula',
    name: 'Nebula',
    character: 'Cosmos',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Deep purple-pink-cyan cosmic gradient with slow rotational drift. Extremely long ignition scroll like a nebula forming. Meditative.',
    config: {
      name: 'Nebula',
      baseColor: { r: 120, g: 0, b: 180 },
      clashColor: { r: 255, g: 100, b: 200 },
      lockupColor: { r: 80, g: 0, b: 120 },
      blastColor: { r: 0, g: 200, b: 200 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1500,
      retractionMs: 1800,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // COMMUNITY CLASSICS
  // ════════════════════════════════════════════

  {
    id: 'creative-fire-and-ice',
    name: 'Fire & Ice',
    character: 'Classic Split',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Red base fading to blue at the tip. The community classic that never gets old. Clash inverts to blue, lockup blends to purple.',
    config: {
      name: 'FireAndIce',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 0, g: 100, b: 255 },
      lockupColor: { r: 150, g: 0, b: 150 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'gradient',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-kryptonite',
    name: 'Kryptonite',
    character: 'Radioactive',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Toxic radioactive green with heavy unstable flicker. The blade looks like it is actively dangerous to hold. It probably is.',
    config: {
      name: 'Kryptonite',
      baseColor: { r: 0, g: 220, b: 50 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 150, b: 30 },
      blastColor: { r: 100, g: 255, b: 100 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 700,
      shimmer: 0.55,
      ledCount: 144,
    },
  },
  {
    id: 'creative-ghostblade',
    name: 'Ghostblade',
    character: 'Spectral',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Dim, translucent spectral blade. Barely visible, hauntingly beautiful. Clash triggers a bright spectral flash that fades fast.',
    config: {
      name: 'Ghostblade',
      baseColor: { r: 30, g: 40, b: 60 },
      clashColor: { r: 150, g: 180, b: 255 },
      lockupColor: { r: 60, g: 80, b: 120 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 2000,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-sparkle-blade',
    name: 'Sparkle Blade',
    character: 'Crystal Glitter',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Maximum prismatic shimmer on a white-lavender base. Pure crystalline glitter. Impractical, gorgeous, unapologetic.',
    config: {
      name: 'SparkleBlade',
      baseColor: { r: 220, g: 220, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 200, b: 240 },
      blastColor: { r: 255, g: 200, b: 255 },
      style: 'prism',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.9,
      ledCount: 144,
    },
  },
  {
    id: 'creative-binary-sunset',
    name: 'Binary Sunset',
    character: 'Tatooine',
    era: 'original-trilogy',
    affiliation: 'jedi',
    tier: 'base',
    description: 'Warm orange-gold fading to dusky purple at the tip. The Tatooine sky at dusk. Williams plays in your head automatically.',
    config: {
      name: 'BinarySunset',
      baseColor: { r: 255, g: 150, b: 30 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 200, g: 100, b: 20 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1500,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-void-walker',
    name: 'Void Walker',
    character: 'The Void',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'Near-black violet plasma that drinks light. The blade is a wound in space. Clash erupts in violent purple. For the edgelords, and they are right to love it.',
    config: {
      name: 'VoidWalker',
      baseColor: { r: 20, g: 0, b: 40 },
      clashColor: { r: 200, g: 0, b: 255 },
      lockupColor: { r: 40, g: 0, b: 60 },
      blastColor: { r: 150, g: 0, b: 200 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.65,
      ledCount: 144,
    },
  },
  {
    id: 'creative-quantum-flux',
    name: 'Quantum Flux',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'base',
    description: 'Maximum prismatic refraction — a blade of pure light split into every color, spinning wildly.',
    config: {
      name: 'QuantumFlux',
      baseColor: { r: 0, g: 200, b: 220 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 200, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'prism',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 200,
      retractionMs: 300,
      shimmer: 0.15,
      ledCount: 144,
      facets: 12,
      rotationSpeed: 3.0,
    },
  },
  {
    id: 'creative-nebula-core',
    name: 'Nebula Core',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'detailed',
    description: 'Chaotic plasma energy from a dying star. Deep purple arcs crackle unpredictably.',
    config: {
      name: 'NebulaCore',
      baseColor: { r: 100, g: 30, b: 180 },
      clashColor: { r: 200, g: 150, b: 255 },
      lockupColor: { r: 180, g: 100, b: 255 },
      blastColor: { r: 255, g: 200, b: 255 },
      style: 'plasma',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 350,
      retractionMs: 500,
      shimmer: 0.18,
      ledCount: 144,
      frequency: 2.5,
      phaseSpeed: 1.8,
    },
  },
  {
    id: 'creative-ghost-signal',
    name: 'Ghost Signal',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'base',
    description: 'An ethereal blade that flickers in and out of existence, like a transmission from another dimension.',
    config: {
      name: 'GhostSignal',
      baseColor: { r: 120, g: 220, b: 160 },
      clashColor: { r: 200, g: 255, b: 220 },
      lockupColor: { r: 150, g: 240, b: 180 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'photon',
      ignition: 'glitch',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 600,
      shimmer: 0.12,
      ledCount: 144,
    },
  },
  {
    id: 'creative-thermal-detonator',
    name: 'Thermal Detonator',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'detailed',
    description: 'A blade that could explode at any moment. Maximum fire intensity — blindingly hot orange-yellow.',
    config: {
      name: 'ThermalDetonator',
      baseColor: { r: 255, g: 180, b: 30 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 200, b: 100 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'fire',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 200,
      retractionMs: 250,
      shimmer: 0.2,
      ledCount: 144,
      fireSize: 0.9,
      sparkRate: 0.8,
      heatSpread: 1.0,
    },
  },
  {
    id: 'creative-tidal-wave',
    name: 'Tidal Wave',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'detailed',
    description: 'Deep ocean energy captured in blade form. Slow, mesmerizing aurora waves in deep blue-teal.',
    config: {
      name: 'TidalWave',
      baseColor: { r: 10, g: 60, b: 180 },
      clashColor: { r: 150, g: 200, b: 255 },
      lockupColor: { r: 100, g: 150, b: 220 },
      blastColor: { r: 200, g: 230, b: 255 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 700,
      shimmer: 0.1,
      ledCount: 144,
      waveCount: 7,
      driftSpeed: 0.8,
    },
  },
  {
    id: 'creative-heartbeat',
    name: 'Heartbeat',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'A deep crimson blade that pulses like a heartbeat — slow, rhythmic, almost alive.',
    config: {
      name: 'Heartbeat',
      baseColor: { r: 180, g: 10, b: 20 },
      clashColor: { r: 255, g: 100, b: 100 },
      lockupColor: { r: 220, g: 50, b: 50 },
      blastColor: { r: 255, g: 200, b: 200 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 800,
      shimmer: 0.05,
      ledCount: 144,
      pulseSpeed: 0.6,
      pulseMinBright: 0.1,
    },
  },
  {
    id: 'creative-starfield',
    name: 'Starfield',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'jedi',
    tier: 'base',
    description: 'A pure white blade that fractures into crystalline segments, each twinkling like distant stars.',
    config: {
      name: 'Starfield',
      baseColor: { r: 220, g: 230, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 240 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'crystalShatter',
      ignition: 'wipe',
      retraction: 'shatter',
      ignitionMs: 350,
      retractionMs: 300,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-molten-core',
    name: 'Molten Core',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'base',
    description: 'Dying ember blade — dark with glowing hot spots that shift like molten magma.',
    config: {
      name: 'MoltenCore',
      baseColor: { r: 200, g: 60, b: 10 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 255, g: 150, b: 50 },
      blastColor: { r: 255, g: 220, b: 150 },
      style: 'cinder',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 450,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-retro-crt',
    name: 'Retro CRT',
    character: 'Custom',
    era: 'expanded-universe',
    affiliation: 'neutral',
    tier: 'base',
    description: 'Old-school green phosphor display effect — the original rotoscope look from 1977, cranked up.',
    config: {
      name: 'RetroCRT',
      baseColor: { r: 30, g: 255, b: 50 },
      clashColor: { r: 200, g: 255, b: 200 },
      lockupColor: { r: 150, g: 255, b: 150 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'rotoscope',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 400,
      retractionMs: 400,
      shimmer: 0.15,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // NEW STYLES SHOWCASE
  // ════════════════════════════════════════════

  // ── NATURE & ELEMENTS ──────────────────────

  {
    id: 'creative-deep-current',
    name: 'Deep Current',
    character: 'Ocean',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Abyssal tidal currents flow through the blade like deep ocean water pushed by invisible forces. The retraction drains downward like a receding tide.',
    config: {
      name: 'DeepCurrent',
      baseColor: { r: 0, g: 60, b: 90 },
      clashColor: { r: 100, g: 220, b: 255 },
      lockupColor: { r: 0, g: 100, b: 130 },
      blastColor: { r: 0, g: 180, b: 200 },
      style: 'tidal',
      ignition: 'drip-up',
      retraction: 'drain',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.25,
      ledCount: 144,
    },
  },
  {
    id: 'creative-wildfire',
    name: 'Wildfire',
    character: 'Inferno',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Embers rise and swirl like a forest fire raging out of control. Ignition crackles to life like kindling catching, retraction evaporates into heat shimmer.',
    config: {
      name: 'Wildfire',
      baseColor: { r: 220, g: 80, b: 0 },
      clashColor: { r: 255, g: 255, b: 100 },
      lockupColor: { r: 180, g: 40, b: 0 },
      blastColor: { r: 255, g: 200, b: 50 },
      style: 'ember',
      ignition: 'crackle',
      retraction: 'evaporate',
      ignitionMs: 800,
      retractionMs: 1000,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-glacier',
    name: 'Glacier',
    character: 'Arctic',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Cascading bands of glacial ice flow slowly down the blade. Fracture ignition cracks the ice open, dissolve retraction scatters it into powder snow.',
    config: {
      name: 'Glacier',
      baseColor: { r: 180, g: 220, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 120, g: 180, b: 240 },
      blastColor: { r: 200, g: 240, b: 255 },
      style: 'cascade',
      ignition: 'fracture',
      retraction: 'dissolve',
      ignitionMs: 900,
      retractionMs: 1200,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-sandstorm',
    name: 'Sandstorm',
    character: 'Desert',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Heat haze and swirling sand in blade form. The mirage effect makes the edge shimmer like a desert horizon. Seismic ignition rumbles it to life.',
    config: {
      name: 'Sandstorm',
      baseColor: { r: 200, g: 170, b: 100 },
      clashColor: { r: 255, g: 220, b: 150 },
      lockupColor: { r: 160, g: 130, b: 70 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'mirage',
      ignition: 'seismic',
      retraction: 'dissolve',
      ignitionMs: 700,
      retractionMs: 900,
      shimmer: 0.4,
      ledCount: 144,
    },
  },
  {
    id: 'creative-bioluminescence',
    name: 'Bioluminescence',
    character: 'Deep Sea',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Living light from the midnight zone. Deep indigo nebula clouds pulse with sudden cyan flashes like startled deep-sea creatures. Hauntingly alive.',
    config: {
      name: 'Bioluminescence',
      baseColor: { r: 10, g: 20, b: 80 },
      clashColor: { r: 0, g: 255, b: 220 },
      lockupColor: { r: 20, g: 50, b: 120 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'nebula',
      ignition: 'summon',
      retraction: 'flickerOut',
      ignitionMs: 1000,
      retractionMs: 1400,
      shimmer: 0.35,
      ledCount: 144,
    },
  },
  {
    id: 'creative-earthquake',
    name: 'Earthquake',
    character: 'Tectonic',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'The blade reacts to gravity like liquefied earth. Tilt it and the color pools and shifts. Seismic ignition shakes it awake, drain retraction lets it settle.',
    config: {
      name: 'Earthquake',
      baseColor: { r: 140, g: 50, b: 10 },
      clashColor: { r: 255, g: 150, b: 0 },
      lockupColor: { r: 100, g: 30, b: 0 },
      blastColor: { r: 255, g: 100, b: 30 },
      style: 'gravity',
      ignition: 'seismic',
      retraction: 'drain',
      ignitionMs: 600,
      retractionMs: 1000,
      shimmer: 0.3,
      ledCount: 144,
    },
  },

  // ── SCI-FI & CYBERPUNK ─────────────────────

  {
    id: 'creative-mainframe',
    name: 'Mainframe',
    character: 'Hacker',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Traveling data packets stream through the blade like live network traffic. Hyperspace ignition boots the system, spaghettify retraction stretches the data into oblivion.',
    config: {
      name: 'Mainframe',
      baseColor: { r: 0, g: 200, b: 50 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 120, b: 30 },
      blastColor: { r: 0, g: 255, b: 100 },
      style: 'dataStream',
      ignition: 'hyperspace',
      retraction: 'spaghettify',
      ignitionMs: 500,
      retractionMs: 800,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-neural-link',
    name: 'Neural Link',
    character: 'Cyborg',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Cellular automata patterns evolve along the blade like synapses firing across a neural network. Flash-fill ignition lights up every node at once.',
    config: {
      name: 'NeuralLink',
      baseColor: { r: 0, g: 200, b: 220 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 0, g: 150, b: 180 },
      blastColor: { r: 200, g: 255, b: 255 },
      style: 'automata',
      ignition: 'flash-fill',
      retraction: 'dissolve',
      ignitionMs: 400,
      retractionMs: 700,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-warp-core',
    name: 'Warp Core',
    character: 'Engineer',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Twin energy helices spiral around each other like matter and antimatter streams in a warp reactor. Hyperspace ignition stretches them to lightspeed.',
    config: {
      name: 'WarpCore',
      baseColor: { r: 60, g: 40, b: 220 },
      clashColor: { r: 200, g: 150, b: 255 },
      lockupColor: { r: 80, g: 0, b: 180 },
      blastColor: { r: 150, g: 100, b: 255 },
      style: 'helix',
      ignition: 'hyperspace',
      retraction: 'implode',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.25,
      ledCount: 144,
    },
  },
  {
    id: 'creative-singularity',
    name: 'Singularity',
    character: 'Black Hole',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'A swirling vortex of gravitational collapse. Near-black blade with violent purple accretion disk energy. Spaghettify retraction is exactly what it sounds like.',
    config: {
      name: 'Singularity',
      baseColor: { r: 20, g: 0, b: 30 },
      clashColor: { r: 180, g: 50, b: 255 },
      lockupColor: { r: 40, g: 0, b: 60 },
      blastColor: { r: 120, g: 0, b: 200 },
      style: 'vortex',
      ignition: 'summon',
      retraction: 'spaghettify',
      ignitionMs: 800,
      retractionMs: 1200,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-quantum-entangle',
    name: 'Quantum Entangle',
    character: 'Physicist',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Magenta and cyan interference fringes ripple across the blade like entangled photon pairs. Pulse-wave ignition builds in quantum oscillations.',
    config: {
      name: 'QuantumEntangle',
      baseColor: { r: 200, g: 0, b: 200 },
      clashColor: { r: 0, g: 255, b: 255 },
      lockupColor: { r: 150, g: 0, b: 180 },
      blastColor: { r: 100, g: 255, b: 255 },
      style: 'moire',
      ignition: 'pulse-wave',
      retraction: 'unravel',
      ignitionMs: 700,
      retractionMs: 900,
      shimmer: 0.45,
      ledCount: 144,
    },
  },

  // ── FANTASY & MYTHOLOGY ────────────────────

  {
    id: 'creative-dragonfire',
    name: 'Dragonfire',
    character: 'Dragon',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Ancient dragon flame trapped in a blade. Deep red-gold fbm flicker with billowing gust events, like breath from a furnace the size of a cathedral.',
    config: {
      name: 'Dragonfire',
      baseColor: { r: 180, g: 40, b: 0 },
      clashColor: { r: 255, g: 220, b: 100 },
      lockupColor: { r: 200, g: 80, b: 0 },
      blastColor: { r: 255, g: 180, b: 0 },
      style: 'candle',
      ignition: 'crackle',
      retraction: 'evaporate',
      ignitionMs: 900,
      retractionMs: 1100,
      shimmer: 0.55,
      ledCount: 144,
    },
  },
  {
    id: 'creative-frostbane',
    name: 'Frostbane',
    character: 'Ice Mage',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Independent shards of ice crystal pulse and shift like a blade forged from a frozen waterfall. Fracture ignition cracks it into existence. Implode retraction crushes it to nothing.',
    config: {
      name: 'Frostbane',
      baseColor: { r: 160, g: 210, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 100, g: 160, b: 220 },
      blastColor: { r: 220, g: 240, b: 255 },
      style: 'shatter',
      ignition: 'fracture',
      retraction: 'implode',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-astral-projection',
    name: 'Astral Projection',
    character: 'Mystic',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'A single ethereal particle bounces endlessly through the blade, trailing pale purple afterimages. The weapon of a being not entirely present in this dimension.',
    config: {
      name: 'AstralProjection',
      baseColor: { r: 140, g: 100, b: 200 },
      clashColor: { r: 220, g: 200, b: 255 },
      lockupColor: { r: 100, g: 70, b: 160 },
      blastColor: { r: 200, g: 180, b: 255 },
      style: 'neutron',
      ignition: 'summon',
      retraction: 'flickerOut',
      ignitionMs: 1000,
      retractionMs: 1300,
      shimmer: 0.4,
      ledCount: 144,
    },
  },
  {
    id: 'creative-phoenix-rising',
    name: 'Phoenix Rising',
    character: 'Phoenix',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Torrential flame energy surging upward like a phoenix reborn from ash. Flash-fill ignition erupts in blinding white before settling into orange-gold-red.',
    config: {
      name: 'PhoenixRising',
      baseColor: { r: 240, g: 120, b: 0 },
      clashColor: { r: 255, g: 255, b: 150 },
      lockupColor: { r: 200, g: 60, b: 0 },
      blastColor: { r: 255, g: 200, b: 50 },
      style: 'torrent',
      ignition: 'flash-fill',
      retraction: 'evaporate',
      ignitionMs: 500,
      retractionMs: 800,
      shimmer: 0.45,
      ledCount: 144,
    },
  },

  // ── ABSTRACT & ARTISTIC ────────────────────

  {
    id: 'creative-interference',
    name: 'Interference',
    character: 'Light Artist',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Thin-film interference patterns create a constantly shifting rainbow across the blade surface. Like oil on water, captured in plasma. Unravel retraction peels the colors apart.',
    config: {
      name: 'Interference',
      baseColor: { r: 200, g: 100, b: 255 },
      clashColor: { r: 100, g: 255, b: 200 },
      lockupColor: { r: 255, g: 150, b: 100 },
      blastColor: { r: 0, g: 255, b: 255 },
      style: 'moire',
      ignition: 'pulse-wave',
      retraction: 'unravel',
      ignitionMs: 800,
      retractionMs: 1000,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-perpetual-motion',
    name: 'Perpetual Motion',
    character: 'Inventor',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Twin white-gold helices spiral endlessly. Hyperspace ignition winds them up, drain retraction lets the energy spiral down to stillness.',
    config: {
      name: 'PerpetualMotion',
      baseColor: { r: 255, g: 230, b: 180 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 220, g: 200, b: 150 },
      blastColor: { r: 255, g: 255, b: 220 },
      style: 'helix',
      ignition: 'hyperspace',
      retraction: 'drain',
      ignitionMs: 500,
      retractionMs: 900,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-cellular',
    name: 'Cellular',
    character: 'Mathematician',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Rule 30 cellular automaton evolves in real time along the blade. Green cells on black void. Emergent complexity from simple rules. Stephen Wolfram approves.',
    config: {
      name: 'Cellular',
      baseColor: { r: 0, g: 180, b: 30 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 100, b: 10 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'automata',
      ignition: 'crackle',
      retraction: 'dissolve',
      ignitionMs: 600,
      retractionMs: 800,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-event-horizon',
    name: 'Event Horizon',
    character: 'Void',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'The point of no return. Near-black vortex with violent violet accents spiraling inward. Seismic ignition warps spacetime. Spaghettify retraction is the last thing you see.',
    config: {
      name: 'EventHorizon',
      baseColor: { r: 10, g: 0, b: 15 },
      clashColor: { r: 150, g: 0, b: 255 },
      lockupColor: { r: 30, g: 0, b: 50 },
      blastColor: { r: 100, g: 0, b: 180 },
      style: 'vortex',
      ignition: 'seismic',
      retraction: 'spaghettify',
      ignitionMs: 700,
      retractionMs: 1100,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-cozy-fireplace',
    name: 'Cozy Fireplace',
    character: 'Homebody',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Warm amber-orange fbm flicker like a crackling hearth on a winter night. Drip-up ignition slowly kindles, flicker-out retraction dies to embers. Comfort in blade form.',
    config: {
      name: 'CozyFireplace',
      baseColor: { r: 220, g: 140, b: 40 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 180, g: 100, b: 20 },
      blastColor: { r: 255, g: 180, b: 60 },
      style: 'candle',
      ignition: 'drip-up',
      retraction: 'flickerOut',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },

  // ── FUN & NOVELTY ──────────────────────────

  {
    id: 'creative-loading-screen',
    name: 'Loading Screen',
    character: 'Buffering',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Data packets stream up the blade like a progress bar that never quite finishes. Pulse-wave ignition loads in segments. Dissolve retraction: connection lost.',
    config: {
      name: 'LoadingScreen',
      baseColor: { r: 30, g: 100, b: 220 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 20, g: 60, b: 150 },
      blastColor: { r: 100, g: 180, b: 255 },
      style: 'dataStream',
      ignition: 'pulse-wave',
      retraction: 'dissolve',
      ignitionMs: 1000,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-graviton',
    name: 'Graviton',
    character: 'Zero-G',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Bright white energy that pools toward gravity like liquid light. Tilt the hilt and watch the color slide. The most satisfying fidget toy disguised as a weapon.',
    config: {
      name: 'Graviton',
      baseColor: { r: 230, g: 230, b: 240 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 200, b: 220 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'gravity',
      ignition: 'seismic',
      retraction: 'implode',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-shooting-star',
    name: 'Shooting Star',
    character: 'Meteor',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'A single bright white particle bounces endlessly, trailing stardust. Hyperspace ignition launches it at lightspeed. Evaporate retraction burns it up in the atmosphere.',
    config: {
      name: 'ShootingStar',
      baseColor: { r: 240, g: 240, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 240 },
      blastColor: { r: 255, g: 255, b: 200 },
      style: 'neutron',
      ignition: 'hyperspace',
      retraction: 'evaporate',
      ignitionMs: 300,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-tectonic',
    name: 'Tectonic',
    character: 'Magma',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Cooled black crust shatters to reveal magma-red molten segments pulsing independently. Seismic ignition rumbles it apart. Drain retraction cools it from tip to hilt.',
    config: {
      name: 'Tectonic',
      baseColor: { r: 200, g: 20, b: 0 },
      clashColor: { r: 255, g: 180, b: 0 },
      lockupColor: { r: 150, g: 10, b: 0 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'shatter',
      ignition: 'seismic',
      retraction: 'drain',
      ignitionMs: 700,
      retractionMs: 1000,
      shimmer: 0.35,
      ledCount: 144,
    },
  },
  {
    id: 'creative-monsoon',
    name: 'Monsoon',
    character: 'Storm',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Blue-gray rain bands cascade down the blade in heavy sheets. Drip-up ignition fills it from the bottom like rising floodwater. Drain retraction lets it all flow out.',
    config: {
      name: 'Monsoon',
      baseColor: { r: 80, g: 100, b: 140 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 50, g: 70, b: 110 },
      blastColor: { r: 150, g: 180, b: 220 },
      style: 'cascade',
      ignition: 'drip-up',
      retraction: 'drain',
      ignitionMs: 800,
      retractionMs: 1000,
      shimmer: 0.2,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // WILD & CRAZY
  // ════════════════════════════════════════════

  {
    id: 'creative-vaporwave-aesthetic',
    name: 'V A P O R W A V E',
    character: 'A E S T H E T I C',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Hot pink to cyan gradient on a slow aurora drift. It is always 1991 in the mall and the sun never sets. Retraction unravels like a VHS tape being eaten. Macintosh Plus plays in the distance.',
    config: {
      name: 'Vaporwave',
      baseColor: { r: 255, g: 50, b: 150 },
      clashColor: { r: 0, g: 255, b: 255 },
      lockupColor: { r: 180, g: 0, b: 255 },
      blastColor: { r: 100, g: 255, b: 200 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'unravel',
      ignitionMs: 1800,
      retractionMs: 2000,
      shimmer: 0.45,
      ledCount: 144,
    },
  },
  {
    id: 'creative-bsod',
    name: 'Lightsaber.exe Has Crashed',
    character: 'Blue Screen of Death',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Solid Windows blue. Completely stable. Absolutely nothing wrong. Then clash happens and it all goes to glitch-matrix hell. Retraction dissolves like corrupted memory being freed. Your saber has encountered an unexpected error.',
    config: {
      name: 'BSOD',
      baseColor: { r: 0, g: 120, b: 215 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 0, g: 80, b: 180 },
      blastColor: { r: 255, g: 0, b: 0 },
      style: 'stable',
      ignition: 'glitch',
      retraction: 'dissolve',
      ignitionMs: 100,
      retractionMs: 3000,
      shimmer: 0.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dial-up',
    name: 'Dial-Up Internet',
    character: '56k Modem',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Takes 3 full seconds to ignite because it is connecting at 56 kilobits per second. Data packets crawl up the blade like AOL loading a JPEG in 1997. Clash produces the modem handshake screech in your soul. Worth the wait. Probably.',
    config: {
      name: 'DialUp',
      baseColor: { r: 0, g: 160, b: 0 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 0, g: 80, b: 0 },
      blastColor: { r: 200, g: 200, b: 200 },
      style: 'dataStream',
      ignition: 'pulse-wave',
      retraction: 'spaghettify',
      ignitionMs: 3000,
      retractionMs: 2500,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-nyan-saber',
    name: 'Nyan Saber',
    character: 'Pop-Tart Cat',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Hot pink base with maximum rainbow prism shimmer. The blade IS the rainbow trail. Hyperspace ignition launches it at meme speed. Evaporate retraction? Nyan Cat never stops. But your battery does.',
    config: {
      name: 'NyanSaber',
      baseColor: { r: 255, g: 100, b: 180 },
      clashColor: { r: 255, g: 255, b: 0 },
      lockupColor: { r: 0, g: 255, b: 100 },
      blastColor: { r: 100, g: 100, b: 255 },
      style: 'prism',
      ignition: 'hyperspace',
      retraction: 'evaporate',
      ignitionMs: 200,
      retractionMs: 400,
      shimmer: 1.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-its-over-9000',
    name: 'IT\'S OVER 9000!!!',
    character: 'Power Level',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Blinding yellow-white overcharge aura with maximum shimmer and torrential energy. The blade screams. You scream. Everything screams. Flash-fill ignition is instantaneous because your power level demands it. Spaghettify retraction because this much energy tears spacetime.',
    config: {
      name: 'Over9000',
      baseColor: { r: 255, g: 240, b: 0 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      style: 'torrent',
      ignition: 'flash-fill',
      retraction: 'spaghettify',
      ignitionMs: 50,
      retractionMs: 200,
      shimmer: 1.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-saber-goes-brrr',
    name: 'Saber Goes Brrr',
    character: 'Money Printer',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Maximum green data stream going absolutely haywire. The Federal Reserve of lightsabers. Unlimited blade works. Crackle ignition because the economy is a series of controlled explosions. Dissolve retraction as the value evaporates.',
    config: {
      name: 'SaberGoesBrrr',
      baseColor: { r: 0, g: 200, b: 0 },
      clashColor: { r: 0, g: 255, b: 0 },
      lockupColor: { r: 0, g: 100, b: 0 },
      blastColor: { r: 100, g: 255, b: 100 },
      style: 'dataStream',
      ignition: 'crackle',
      retraction: 'dissolve',
      ignitionMs: 150,
      retractionMs: 300,
      shimmer: 0.9,
      ledCount: 144,
    },
  },
  {
    id: 'creative-synthwave-sunset',
    name: 'Synthwave Sunset',
    character: 'Retrowave',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Deep magenta helix spirals over a chrome-orange base. The Miami skyline at dusk if the skyline was made of pure energy. Clash goes full neon cyan. Drive down the coast, blade out the window, synthwave on the stereo.',
    config: {
      name: 'SynthwaveSunset',
      baseColor: { r: 255, g: 80, b: 0 },
      clashColor: { r: 0, g: 255, b: 255 },
      lockupColor: { r: 200, g: 0, b: 180 },
      blastColor: { r: 255, g: 0, b: 200 },
      style: 'helix',
      ignition: 'wipe',
      retraction: 'flickerOut',
      ignitionMs: 500,
      retractionMs: 700,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-glitch-in-the-matrix',
    name: 'Glitch in the Matrix',
    character: 'Deja Vu',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Green automata cells evolve and suddenly BREAK. Shatter fragments randomly reassemble. The simulation is failing. Glitch ignition stutters reality. Spaghettify retraction stretches the world like taffy. Did you just see that cat twice?',
    config: {
      name: 'GlitchMatrix',
      baseColor: { r: 0, g: 220, b: 30 },
      clashColor: { r: 255, g: 0, b: 0 },
      lockupColor: { r: 0, g: 100, b: 0 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'automata',
      ignition: 'glitch',
      retraction: 'spaghettify',
      ignitionMs: 400,
      retractionMs: 600,
      shimmer: 0.75,
      ledCount: 144,
    },
  },
  {
    id: 'creative-lofi-chill',
    name: 'Lo-Fi Chill Beats Saber',
    character: 'Study Girl',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Warm amber candle flicker on low shimmer. Gentle, cozy, meditative. The blade equivalent of rain on a window while you study for Jedi exams. Drip-up ignition kindles slowly. Flicker-out retraction dies like the last ember. Looping forever.',
    config: {
      name: 'LoFiChill',
      baseColor: { r: 200, g: 130, b: 60 },
      clashColor: { r: 255, g: 200, b: 120 },
      lockupColor: { r: 150, g: 90, b: 30 },
      blastColor: { r: 220, g: 170, b: 80 },
      style: 'candle',
      ignition: 'drip-up',
      retraction: 'flickerOut',
      ignitionMs: 2000,
      retractionMs: 2500,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-maximum-rgb',
    name: 'RGB Gaming Saber Pro Max Ultra',
    character: 'PC Master Race',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Every RGB trick at once. Vortex style because the colors must SPIN. Shimmer at absolute maximum. Hyperspace ignition because SPEED. Your FPS did not improve. Your electricity bill did. Razer would sponsor this.',
    config: {
      name: 'MaxRGB',
      baseColor: { r: 255, g: 0, b: 0 },
      clashColor: { r: 0, g: 255, b: 0 },
      lockupColor: { r: 0, g: 0, b: 255 },
      blastColor: { r: 255, g: 255, b: 0 },
      style: 'vortex',
      ignition: 'hyperspace',
      retraction: 'shatter',
      ignitionMs: 100,
      retractionMs: 150,
      shimmer: 1.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dark-mode',
    name: 'Dark Mode',
    character: 'Developer',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Near-black blade with barely visible dark gray pulse. Because your eyes are sensitive and you refuse to use light mode. Clash triggers a blinding white flash that ruins your night vision for 20 minutes. Just like accidentally opening Settings on your phone at 3 AM.',
    config: {
      name: 'DarkMode',
      baseColor: { r: 15, g: 15, b: 20 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 30, g: 30, b: 40 },
      blastColor: { r: 200, g: 200, b: 200 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 800,
      retractionMs: 1500,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-forbidden-saber',
    name: 'The Forbidden Saber',
    character: 'Cursed Object',
    era: 'expanded-universe',
    affiliation: 'sith',
    tier: 'detailed',
    description: 'You were told not to build this. Inverted colors, maximum instability, every parameter at an extreme. Fracture ignition because this saber was never meant to exist in one piece. Spaghettify retraction because nothing good comes from wielding this. You were warned.',
    config: {
      name: 'ForbiddenSaber',
      baseColor: { r: 0, g: 0, b: 0 },
      clashColor: { r: 255, g: 0, b: 255 },
      lockupColor: { r: 255, g: 0, b: 0 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'unstable',
      ignition: 'fracture',
      retraction: 'spaghettify',
      ignitionMs: 50,
      retractionMs: 3000,
      shimmer: 1.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-cyberpunk-2077',
    name: 'Night City Chrome',
    character: 'Cyberpunk Edgerunner',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Electric yellow moire interference patterns over a hot pink base. Corpo-grade cyberware energy. Glitch ignition because nothing in Night City works right the first time. Implode retraction for when you flatline. Wake up, samurai.',
    config: {
      name: 'NightCityChrome',
      baseColor: { r: 255, g: 0, b: 80 },
      clashColor: { r: 255, g: 255, b: 0 },
      lockupColor: { r: 0, g: 255, b: 200 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'moire',
      ignition: 'glitch',
      retraction: 'implode',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-comic-sans',
    name: 'Comic Sans Saber',
    character: 'Design Crime',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Aggressively cheerful yellow-orange with bouncy pulse. The most unprofessional lightsaber in the galaxy. Every graphic designer who sees this blade feels a disturbance in the Force. Pairs well with Papyrus.',
    config: {
      name: 'ComicSans',
      baseColor: { r: 255, g: 200, b: 0 },
      clashColor: { r: 255, g: 100, b: 200 },
      lockupColor: { r: 0, g: 200, b: 255 },
      blastColor: { r: 255, g: 150, b: 0 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 800,
      retractionMs: 800,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dueling-banjos',
    name: 'Rave Stick Deluxe',
    character: 'Festival Goer',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'UV purple nebula clouds with flash-fill white strobe clash. This is not a weapon, it is a personal dance floor beacon. Center ignition blooms outward like the bass drop. Evaporate retraction for when the DJ kills the music and the lights come on at 4 AM. Reality hurts.',
    config: {
      name: 'RaveStickDeluxe',
      baseColor: { r: 100, g: 0, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 0, b: 150 },
      blastColor: { r: 0, g: 255, b: 100 },
      style: 'nebula',
      ignition: 'center',
      retraction: 'evaporate',
      ignitionMs: 250,
      retractionMs: 500,
      shimmer: 0.95,
      ledCount: 144,
    },
  },
  {
    id: 'creative-microwave-dinner',
    name: 'Microwave Dinner',
    character: 'Lazy Chef',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Starts frozen blue, gradually heats to scalding red-orange with ember particles rising like steam. But the middle stays cold. Stutter ignition because you had to press Start three times. Drain retraction because you gave up and ordered pizza.',
    config: {
      name: 'MicrowaveDinner',
      baseColor: { r: 60, g: 100, b: 200 },
      clashColor: { r: 255, g: 100, b: 0 },
      lockupColor: { r: 200, g: 50, b: 0 },
      blastColor: { r: 255, g: 200, b: 0 },
      style: 'ember',
      ignition: 'stutter',
      retraction: 'drain',
      ignitionMs: 2000,
      retractionMs: 1500,
      shimmer: 0.35,
      ledCount: 144,
    },
  },
  {
    id: 'creative-windows-xp',
    name: 'Windows XP Bliss',
    character: 'Nostalgic OS',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Serene green-to-blue gradient. The most peaceful lightsaber ever made. Then clash triggers the critical error red and everything goes wrong. Stutter ignition plays the startup chime in your memory. Dissolve retraction is the shutdown animation you actually waited for.',
    config: {
      name: 'WindowsXPBliss',
      baseColor: { r: 50, g: 180, b: 50 },
      clashColor: { r: 255, g: 0, b: 0 },
      lockupColor: { r: 0, g: 120, b: 215 },
      blastColor: { r: 255, g: 255, b: 0 },
      style: 'gradient',
      ignition: 'stutter',
      retraction: 'dissolve',
      ignitionMs: 1500,
      retractionMs: 2000,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-everything-everywhere',
    name: 'Everything Bagel',
    character: 'Multiverse',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'All styles, all colors, all at once. A vortex of pure chaotic energy containing every possible blade configuration simultaneously. This is what it looks like when you open every door at the same time. Seismic ignition rips open the multiverse. Spaghettify retraction collapses it.',
    config: {
      name: 'EverythingBagel',
      baseColor: { r: 128, g: 0, b: 255 },
      clashColor: { r: 255, g: 128, b: 0 },
      lockupColor: { r: 0, g: 255, b: 128 },
      blastColor: { r: 255, g: 0, b: 128 },
      style: 'vortex',
      ignition: 'seismic',
      retraction: 'spaghettify',
      ignitionMs: 300,
      retractionMs: 500,
      shimmer: 0.85,
      ledCount: 144,
    },
  },
  {
    id: 'creative-absolute-zero',
    name: 'Absolute Zero',
    character: 'Entropy Death',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'The coldest possible blade. Near-white ice blue cascade flows down at glacial speed. Zero shimmer. Zero warmth. Zero mercy. Summon ignition crystallizes from nothing. Implode retraction collapses to a single frozen point. The heat death of your lightsaber.',
    config: {
      name: 'AbsoluteZero',
      baseColor: { r: 200, g: 230, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 150, g: 200, b: 255 },
      blastColor: { r: 220, g: 240, b: 255 },
      style: 'cascade',
      ignition: 'summon',
      retraction: 'implode',
      ignitionMs: 2500,
      retractionMs: 800,
      shimmer: 0.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-supernova',
    name: 'Supernova',
    character: 'Dying Star',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'A star exploding in your hand. Blinding white torrent with maximum shimmer, 50ms flash-fill ignition that nukes your retinas, then violent orange-red-purple death throes. Spaghettify retraction tears the remnant apart into a nebula. Wear sunglasses. Not optional.',
    config: {
      name: 'Supernova',
      baseColor: { r: 255, g: 255, b: 240 },
      clashColor: { r: 255, g: 100, b: 0 },
      lockupColor: { r: 255, g: 50, b: 50 },
      blastColor: { r: 200, g: 0, b: 255 },
      style: 'torrent',
      ignition: 'flash-fill',
      retraction: 'spaghettify',
      ignitionMs: 50,
      retractionMs: 1500,
      shimmer: 1.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-anxiety-core',
    name: 'Anxiety Core',
    character: 'Overthinking',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'detailed',
    description: 'Unstable tidal surges in sickly yellow-green. The blade is fine. Everything is fine. The shimmer is your heartbeat and it will not slow down. Stutter ignition because you cannot commit. Flicker-out retraction because you eventually exhaust yourself. Very relatable. Too relatable.',
    config: {
      name: 'AnxietyCore',
      baseColor: { r: 180, g: 200, b: 0 },
      clashColor: { r: 255, g: 0, b: 0 },
      lockupColor: { r: 200, g: 180, b: 0 },
      blastColor: { r: 255, g: 255, b: 0 },
      style: 'tidal',
      ignition: 'stutter',
      retraction: 'flickerOut',
      ignitionMs: 1500,
      retractionMs: 2000,
      shimmer: 0.8,
      ledCount: 144,
    },
  },
  {
    id: 'creative-party-mode',
    name: 'Party Mode Activated',
    character: 'Birthday',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Hot pink mirage shimmer because reality is optional at parties. Gold clash like confetti. Green lockup like laser pointers on the dance floor. Spark ignition shoots up like a roman candle. Shatter retraction explodes like a pinata. Happy birthday, you absolute legend.',
    config: {
      name: 'PartyMode',
      baseColor: { r: 255, g: 20, b: 147 },
      clashColor: { r: 255, g: 215, b: 0 },
      lockupColor: { r: 0, g: 255, b: 0 },
      blastColor: { r: 0, g: 150, b: 255 },
      style: 'mirage',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.8,
      ledCount: 144,
    },
  },
  {
    id: 'creative-lava-lamp',
    name: 'Lava Lamp',
    character: 'Retro Decor',
    era: 'expanded-universe',
    affiliation: 'other',
    tier: 'base',
    description: 'Slow gravity-driven blobs of orange-red energy that pool and stretch as you tilt the hilt. Pure 1970s vibes. The most relaxing weapon of mass destruction ever created. Drip-up ignition is the wax warming up. Drain retraction cools it back down. Far out, man.',
    config: {
      name: 'LavaLamp',
      baseColor: { r: 255, g: 60, b: 0 },
      clashColor: { r: 255, g: 200, b: 0 },
      lockupColor: { r: 200, g: 0, b: 100 },
      blastColor: { r: 255, g: 150, b: 0 },
      style: 'gravity',
      ignition: 'drip-up',
      retraction: 'drain',
      ignitionMs: 2500,
      retractionMs: 3000,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
];
