import type { Preset } from '../types.js';

/**
 * Creative, fun, and community-inspired presets.
 * Categories: In-Universe Deep Cuts, Tongue-in-Cheek, Crossover/Pop Culture,
 * Nature/Elements, and Community Classics.
 */
export const CREATIVE_COMMUNITY_PRESETS: Preset[] = [
  // ════════════════════════════════════════════
  // IN-UNIVERSE DEEP CUTS
  // ════════════════════════════════════════════

  {
    id: 'creative-temple-sentinel',
    name: 'Temple Sentinel',
    character: 'Jedi Temple Guard',
    era: 'prequel',
    affiliation: 'jedi',
    description: 'The Jedi Temple Guard\'s rotating pike blade. Warm authoritative yellow with a solemn, steady pulse. Clash produces a blinding flash of golden white.',
    hiltNotes: 'Double-bladed pike with masked guard hilt design.',
    config: {
      name: 'TempleSentinel',
      baseColor: { r: 200, g: 180, b: 0 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 200, b: 50 },
      blastColor: { r: 255, g: 255, b: 100 },
      style: 'rotoscope',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 800,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-darksaber-deep',
    name: 'Darksaber (Crackling)',
    character: 'Darksaber',
    era: 'animated',
    affiliation: 'neutral',
    description: 'Jet-black core with a crackling white edge. High shimmer creates the irregular, living energy the Darksaber is known for. The blade fights you.',
    hiltNotes: 'Ancient Mandalorian hilt with angular crossguard shape.',
    config: {
      name: 'DarksaberCrackling',
      baseColor: { r: 10, g: 10, b: 10 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 180, g: 180, b: 200 },
      blastColor: { r: 200, g: 200, b: 255 },
      style: 'unstable',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-kyber-bleeding',
    name: 'Kyber Bleeding',
    character: 'Corrupted Crystal',
    era: 'prequel',
    affiliation: 'sith',
    description: 'A Jedi crystal being corrupted by the dark side. Starts pure blue, slowly bleeds to crimson. Each clash accelerates the corruption. The fall made visible.',
    config: {
      name: 'KyberBleeding',
      baseColor: { r: 30, g: 80, b: 220 },
      clashColor: { r: 180, g: 20, b: 20 },
      lockupColor: { r: 120, g: 30, b: 100 },
      blastColor: { r: 200, g: 50, b: 50 },
      style: 'gradient',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-purification',
    name: 'Crystal Purification',
    character: 'Redeemed Crystal',
    era: 'animated',
    affiliation: 'jedi',
    description: 'Red healing to brilliant white. The inverse of bleeding — a crystal redeemed through the Force. Clash reveals the white light breaking through.',
    config: {
      name: 'CrystalPurification',
      baseColor: { r: 200, g: 30, b: 30 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 220, g: 180, b: 200 },
      blastColor: { r: 255, g: 200, b: 220 },
      style: 'gradient',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1200,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-sith-alchemy',
    name: 'Sith Alchemy',
    character: 'Ancient Sith',
    era: 'expanded-universe',
    affiliation: 'sith',
    description: 'Ancient dark-side forge blade. Deep arterial red with roiling plasma texture. Lockup summons violet Sith lightning. This blade was never meant to exist.',
    config: {
      name: 'SithAlchemy',
      baseColor: { r: 100, g: 0, b: 0 },
      clashColor: { r: 180, g: 0, b: 180 },
      lockupColor: { r: 60, g: 0, b: 60 },
      blastColor: { r: 255, g: 50, b: 0 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 700,
      retractionMs: 800,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-first-lightsaber',
    name: 'First Lightsaber',
    character: 'Youngling',
    era: 'prequel',
    affiliation: 'jedi',
    description: 'A youngling\'s shaky first ignition. High instability, nervous flicker, long hesitant startup. The blade sputters and wavers but holds. Everyone starts somewhere.',
    config: {
      name: 'FirstLightsaber',
      baseColor: { r: 50, g: 140, b: 255 },
      clashColor: { r: 200, g: 200, b: 255 },
      lockupColor: { r: 100, g: 180, b: 255 },
      blastColor: { r: 150, g: 200, b: 255 },
      style: 'unstable',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1500,
      retractionMs: 500,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-beskar-reflection',
    name: 'Beskar Reflection',
    character: 'Mandalorian',
    era: 'animated',
    affiliation: 'neutral',
    description: 'Mandalorian-wielded blade with metallic silver-blue sheen. Prismatic light plays across the surface like beskar catching firelight. Clash sparks orange like forged metal.',
    config: {
      name: 'BeskarReflection',
      baseColor: { r: 160, g: 170, b: 180 },
      clashColor: { r: 255, g: 200, b: 50 },
      lockupColor: { r: 200, g: 200, b: 210 },
      blastColor: { r: 255, g: 150, b: 0 },
      style: 'prism',
      ignition: 'wipe',
      retraction: 'scroll',
      ignitionMs: 500,
      retractionMs: 400,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // TONGUE-IN-CHEEK / FUN
  // ════════════════════════════════════════════

  {
    id: 'creative-baguette-blade',
    name: 'Baguette Blade',
    character: 'Artisan Baker',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Artisan bread from hilt to tip. Golden-brown crust gradient with a warm bready glow. Clash sends flour everywhere. Oui oui.',
    config: {
      name: 'BaguetteBlade',
      baseColor: { r: 180, g: 130, b: 50 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 140, g: 90, b: 20 },
      blastColor: { r: 255, g: 220, b: 150 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 1000,
      retractionMs: 800,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-rgb-gamer',
    name: 'RGB Gamer',
    character: 'PC Master Race',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Maximum RGB at all times. Fast rainbow cycle with clash triggering the Blue Screen of Death. Your FPS has not improved.',
    config: {
      name: 'RGBGamer',
      baseColor: { r: 0, g: 255, b: 0 },
      clashColor: { r: 0, g: 0, b: 255 },
      lockupColor: { r: 255, g: 0, b: 0 },
      blastColor: { r: 0, g: 120, b: 215 },
      style: 'photon',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 200,
      shimmer: 0.8,
      ledCount: 144,
    },
  },
  {
    id: 'creative-battery-anxiety',
    name: 'Battery Anxiety',
    character: 'Low Power',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Starts full green. Slowly yellows, then reds, then flickers desperately. Retraction is a long, sad fadeout. Charge your saber, you fool.',
    config: {
      name: 'BatteryAnxiety',
      baseColor: { r: 50, g: 200, b: 50 },
      clashColor: { r: 200, g: 200, b: 0 },
      lockupColor: { r: 200, g: 100, b: 0 },
      blastColor: { r: 255, g: 0, b: 0 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 2000,
      retractionMs: 3000,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-disco-inferno',
    name: 'Disco Inferno',
    character: 'Disco Ball',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Sound-reactive color explosions. The blade IS the dance floor. Clash drops the beat. Best paired with a Disco font.',
    config: {
      name: 'DiscoInferno',
      baseColor: { r: 255, g: 0, b: 128 },
      clashColor: { r: 255, g: 255, b: 0 },
      lockupColor: { r: 0, g: 255, b: 255 },
      blastColor: { r: 255, g: 128, b: 0 },
      style: 'photon',
      ignition: 'center',
      retraction: 'shatter',
      ignitionMs: 300,
      retractionMs: 500,
      shimmer: 0.9,
      ledCount: 144,
    },
  },
  {
    id: 'creative-rave-saber',
    name: 'Rave Saber',
    character: 'Raver',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'UV purple with strobe-on-swing. High shimmer creates relentless pulse. Bring glow sticks.',
    config: {
      name: 'RaveSaber',
      baseColor: { r: 120, g: 0, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 0, b: 255 },
      blastColor: { r: 0, g: 255, b: 200 },
      style: 'pulse',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 250,
      retractionMs: 400,
      shimmer: 0.85,
      ledCount: 144,
    },
  },
  {
    id: 'creative-gender-reveal',
    name: 'Gender Reveal',
    character: 'Surprise',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Ignites pure white. First clash reveals pink, lockup reveals blue. Less property damage than the alternatives.',
    config: {
      name: 'GenderReveal',
      baseColor: { r: 240, g: 240, b: 240 },
      clashColor: { r: 255, g: 100, b: 150 },
      lockupColor: { r: 100, g: 150, b: 255 },
      blastColor: { r: 255, g: 200, b: 50 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'creative-404-not-found',
    name: '404 Saber Not Found',
    character: 'Error',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Digital corruption made physical. Pixelated blocks, glitch artifacts, random color tearing. The blade renders incorrectly and that IS the point.',
    config: {
      name: '404NotFound',
      baseColor: { r: 0, g: 200, b: 0 },
      clashColor: { r: 255, g: 0, b: 0 },
      lockupColor: { r: 0, g: 0, b: 200 },
      blastColor: { r: 255, g: 255, b: 0 },
      style: 'crystalShatter',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 900,
      retractionMs: 600,
      shimmer: 0.7,
      ledCount: 144,
    },
  },
  {
    id: 'creative-christmas',
    name: 'Christmas Classic',
    character: 'Holiday',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Alternating red and green with gold lockup like tinsel. Blast sends snowflakes. Festive and aggressive.',
    config: {
      name: 'ChristmasClassic',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 0, g: 200, b: 0 },
      lockupColor: { r: 255, g: 215, b: 0 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 800,
      retractionMs: 800,
      shimmer: 0.25,
      ledCount: 144,
    },
  },
  {
    id: 'creative-spooky-season',
    name: 'Spooky Season',
    character: 'Halloween',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Jack-o-lantern orange fire with purple clash and ghostly green blast. Slow fadeout like a candle dying. Boo.',
    config: {
      name: 'SpookySeason',
      baseColor: { r: 200, g: 80, b: 0 },
      clashColor: { r: 100, g: 0, b: 180 },
      lockupColor: { r: 50, g: 0, b: 100 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'fire',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 700,
      retractionMs: 1200,
      shimmer: 0.4,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // CROSSOVER / POP CULTURE
  // ════════════════════════════════════════════

  {
    id: 'creative-energy-sword',
    name: 'Energy Sword',
    character: 'Covenant',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Split cyan-blue plasma blade inspired by alien energy weapons. Center ignition blooms outward. Clean, alien, lethal.',
    config: {
      name: 'EnergySword',
      baseColor: { r: 0, g: 150, b: 255 },
      clashColor: { r: 200, g: 255, b: 255 },
      lockupColor: { r: 0, g: 200, b: 255 },
      blastColor: { r: 100, g: 220, b: 255 },
      style: 'prism',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 400,
      retractionMs: 300,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dragon-glass',
    name: 'Dragon Glass',
    character: 'Ice & Fire',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Icy obsidian white-blue with fiery orange clash. Shatter retraction looks like glass breaking. Winter is handled.',
    config: {
      name: 'DragonGlass',
      baseColor: { r: 180, g: 220, b: 255 },
      clashColor: { r: 255, g: 100, b: 0 },
      lockupColor: { r: 255, g: 150, b: 50 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'crystalShatter',
      ignition: 'wipe',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-protosaber',
    name: 'Protosaber',
    character: 'Retro Sci-Fi',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Warm amber filament glow like a vintage vacuum tube. Cinder particles rise like old-tech energy. Retro sci-fi pulp magazine aesthetic.',
    config: {
      name: 'Protosaber',
      baseColor: { r: 200, g: 150, b: 50 },
      clashColor: { r: 255, g: 200, b: 100 },
      lockupColor: { r: 180, g: 120, b: 30 },
      blastColor: { r: 255, g: 180, b: 80 },
      style: 'cinder',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1000,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-grid-runner',
    name: 'Grid Runner',
    character: 'Digital World',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Razor-sharp cyan with zero shimmer. Perfectly clean lines for that hard geometric digital aesthetic. The Grid demands precision.',
    config: {
      name: 'GridRunner',
      baseColor: { r: 0, g: 255, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 0, g: 200, b: 200 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'stable',
      ignition: 'wipe',
      retraction: 'wipe',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.0,
      ledCount: 144,
    },
  },
  {
    id: 'creative-digital-rain',
    name: 'Digital Rain',
    character: 'The Matrix',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Cascading green aurora-wave down the blade like falling code. There is no spoon, but there is this saber.',
    config: {
      name: 'DigitalRain',
      baseColor: { r: 0, g: 180, b: 0 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 100, b: 0 },
      blastColor: { r: 0, g: 255, b: 0 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 800,
      shimmer: 0.45,
      ledCount: 144,
    },
  },
  {
    id: 'creative-neon-noir',
    name: 'Neon Noir',
    character: 'Cyberpunk',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Hot pink fading to cyan at the tip. Cyberpunk neon in a rain-soaked alley. Clash inverts the gradient. Chrome and attitude.',
    config: {
      name: 'NeonNoir',
      baseColor: { r: 255, g: 0, b: 100 },
      clashColor: { r: 0, g: 255, b: 255 },
      lockupColor: { r: 200, g: 0, b: 200 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'gradient',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 600,
      shimmer: 0.35,
      ledCount: 144,
    },
  },
  {
    id: 'creative-dark-energy',
    name: 'Dark Energy',
    character: 'Dark Fantasy',
    era: 'expanded-universe',
    affiliation: 'sith',
    description: 'Deep violet-black plasma with chain lightning lockup. Dark fantasy energy blade for those who serve a darker power.',
    config: {
      name: 'DarkEnergy',
      baseColor: { r: 80, g: 0, b: 120 },
      clashColor: { r: 200, g: 100, b: 255 },
      lockupColor: { r: 60, g: 0, b: 80 },
      blastColor: { r: 150, g: 50, b: 200 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 700,
      shimmer: 0.55,
      ledCount: 144,
    },
  },
  {
    id: 'creative-power-grayskull',
    name: 'Power of Grayskull',
    character: 'Heroic Warrior',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Regal gold with silver clash. Dual-tone heroic blade. Simple, bold, legendary.',
    config: {
      name: 'PowerGrayskull',
      baseColor: { r: 220, g: 190, b: 50 },
      clashColor: { r: 200, g: 200, b: 210 },
      lockupColor: { r: 255, g: 215, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-companion-cube',
    name: 'Companion Cube',
    character: 'Portal',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Orange blade, blue clash. The cake is a lie but the style is real.',
    config: {
      name: 'CompanionCube',
      baseColor: { r: 255, g: 120, b: 0 },
      clashColor: { r: 0, g: 100, b: 255 },
      lockupColor: { r: 255, g: 80, b: 0 },
      blastColor: { r: 0, g: 150, b: 255 },
      style: 'pulse',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-pixel-miner',
    name: 'Pixel Miner',
    character: 'Block World',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Aqua diamond crystal shatter pattern. Blocky, chunky, satisfying. Blast sparkles like dropped XP.',
    config: {
      name: 'PixelMiner',
      baseColor: { r: 0, g: 200, b: 200 },
      clashColor: { r: 150, g: 150, b: 150 },
      lockupColor: { r: 0, g: 150, b: 150 },
      blastColor: { r: 50, g: 255, b: 50 },
      style: 'crystalShatter',
      ignition: 'scroll',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 400,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // NATURE / ELEMENTS
  // ════════════════════════════════════════════

  {
    id: 'creative-aurora-borealis',
    name: 'Aurora Borealis',
    character: 'Northern Lights',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Shifting green-cyan-purple waves. Slow, mesmerizing aurora movement along the blade. Best viewed in the dark with awe.',
    config: {
      name: 'AuroraBorealis',
      baseColor: { r: 0, g: 180, b: 100 },
      clashColor: { r: 100, g: 0, b: 200 },
      lockupColor: { r: 0, g: 255, b: 150 },
      blastColor: { r: 0, g: 150, b: 255 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 1500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-magma-core',
    name: 'Magma Core',
    character: 'Volcanic',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Black-red-orange with rising ember particles. The blade looks like cooled lava cracking to reveal molten fury beneath. Clash erupts in yellow fire.',
    config: {
      name: 'MagmaCore',
      baseColor: { r: 180, g: 30, b: 0 },
      clashColor: { r: 255, g: 200, b: 0 },
      lockupColor: { r: 100, g: 10, b: 0 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'cinder',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 800,
      retractionMs: 2000,
      shimmer: 0.5,
      ledCount: 144,
    },
  },
  {
    id: 'creative-abyssal',
    name: 'Abyssal',
    character: 'Deep Ocean',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Crushing deep-ocean blue with bioluminescent cyan pulses. Slow pulsing like something alive in the deep. Clash triggers a jellyfish flash.',
    config: {
      name: 'Abyssal',
      baseColor: { r: 0, g: 20, b: 80 },
      clashColor: { r: 0, g: 255, b: 200 },
      lockupColor: { r: 0, g: 50, b: 120 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'pulse',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1200,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'creative-lightning-storm',
    name: 'Lightning Storm',
    character: 'Tempest',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'White-purple with extreme instability creating constant crackling. High shimmer makes this blade feel like barely-contained electricity.',
    config: {
      name: 'LightningStorm',
      baseColor: { r: 200, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 150, g: 100, b: 255 },
      blastColor: { r: 180, g: 150, b: 255 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.75,
      ledCount: 144,
    },
  },
  {
    id: 'creative-permafrost',
    name: 'Permafrost',
    character: 'Ice',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Icy pale blue with crystalline fracture patterns. Clash creates white flash like ice cracking. Shatter retraction breaks the frozen blade.',
    config: {
      name: 'Permafrost',
      baseColor: { r: 150, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 100, g: 150, b: 220 },
      blastColor: { r: 200, g: 230, b: 255 },
      style: 'crystalShatter',
      ignition: 'wipe',
      retraction: 'shatter',
      ignitionMs: 700,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
    },
  },
  {
    id: 'creative-solar-flare',
    name: 'Solar Flare',
    character: 'Sun',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Blinding yellow-white fire with orange corona. Solar prominence dynamics. Look directly at this blade and regret it.',
    config: {
      name: 'SolarFlare',
      baseColor: { r: 255, g: 220, b: 100 },
      clashColor: { r: 255, g: 150, b: 0 },
      lockupColor: { r: 255, g: 180, b: 50 },
      blastColor: { r: 255, g: 100, b: 0 },
      style: 'fire',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 800,
      shimmer: 0.4,
      ledCount: 144,
    },
  },
  {
    id: 'creative-nebula',
    name: 'Nebula',
    character: 'Cosmos',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Deep purple-pink-cyan cosmic gradient with slow rotational drift. Extremely long ignition scroll like a nebula forming. Meditative.',
    config: {
      name: 'Nebula',
      baseColor: { r: 120, g: 0, b: 180 },
      clashColor: { r: 255, g: 100, b: 200 },
      lockupColor: { r: 80, g: 0, b: 120 },
      blastColor: { r: 0, g: 200, b: 200 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1500,
      retractionMs: 1800,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ════════════════════════════════════════════
  // COMMUNITY CLASSICS
  // ════════════════════════════════════════════

  {
    id: 'creative-fire-and-ice',
    name: 'Fire & Ice',
    character: 'Classic Split',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Red base fading to blue at the tip. The community classic that never gets old. Clash inverts to blue, lockup blends to purple.',
    config: {
      name: 'FireAndIce',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 0, g: 100, b: 255 },
      lockupColor: { r: 150, g: 0, b: 150 },
      blastColor: { r: 0, g: 200, b: 255 },
      style: 'gradient',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 500,
      retractionMs: 500,
      shimmer: 0.3,
      ledCount: 144,
    },
  },
  {
    id: 'creative-kryptonite',
    name: 'Kryptonite',
    character: 'Radioactive',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Toxic radioactive green with heavy unstable flicker. The blade looks like it is actively dangerous to hold. It probably is.',
    config: {
      name: 'Kryptonite',
      baseColor: { r: 0, g: 220, b: 50 },
      clashColor: { r: 150, g: 255, b: 150 },
      lockupColor: { r: 0, g: 150, b: 30 },
      blastColor: { r: 100, g: 255, b: 100 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 500,
      retractionMs: 700,
      shimmer: 0.55,
      ledCount: 144,
    },
  },
  {
    id: 'creative-ghostblade',
    name: 'Ghostblade',
    character: 'Spectral',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Dim, translucent spectral blade. Barely visible, hauntingly beautiful. Clash triggers a bright spectral flash that fades fast.',
    config: {
      name: 'Ghostblade',
      baseColor: { r: 30, g: 40, b: 60 },
      clashColor: { r: 150, g: 180, b: 255 },
      lockupColor: { r: 60, g: 80, b: 120 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'pulse',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 1200,
      retractionMs: 2000,
      shimmer: 0.6,
      ledCount: 144,
    },
  },
  {
    id: 'creative-sparkle-blade',
    name: 'Sparkle Blade',
    character: 'Crystal Glitter',
    era: 'expanded-universe',
    affiliation: 'other',
    description: 'Maximum prismatic shimmer on a white-lavender base. Pure crystalline glitter. Impractical, gorgeous, unapologetic.',
    config: {
      name: 'SparkleBlade',
      baseColor: { r: 220, g: 220, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 200, b: 240 },
      blastColor: { r: 255, g: 200, b: 255 },
      style: 'prism',
      ignition: 'spark',
      retraction: 'shatter',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.9,
      ledCount: 144,
    },
  },
  {
    id: 'creative-binary-sunset',
    name: 'Binary Sunset',
    character: 'Tatooine',
    era: 'original-trilogy',
    affiliation: 'jedi',
    description: 'Warm orange-gold fading to dusky purple at the tip. The Tatooine sky at dusk. Williams plays in your head automatically.',
    config: {
      name: 'BinarySunset',
      baseColor: { r: 255, g: 150, b: 30 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 200, g: 100, b: 20 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'gradient',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 1000,
      retractionMs: 1500,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'creative-void-walker',
    name: 'Void Walker',
    character: 'The Void',
    era: 'expanded-universe',
    affiliation: 'sith',
    description: 'Near-black violet plasma that drinks light. The blade is a wound in space. Clash erupts in violent purple. For the edgelords, and they are right to love it.',
    config: {
      name: 'VoidWalker',
      baseColor: { r: 20, g: 0, b: 40 },
      clashColor: { r: 200, g: 0, b: 255 },
      lockupColor: { r: 40, g: 0, b: 60 },
      blastColor: { r: 150, g: 0, b: 200 },
      style: 'plasma',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.65,
      ledCount: 144,
    },
  },
];
