import type { Preset } from '../types.js';

export const EXTENDED_UNIVERSE_PRESETS: Preset[] = [
  // ── Cal Kestis Variants ──
  {
    id: 'eu-cal-kestis-green',
    name: 'Cal Kestis (Green)',
    character: 'Cal Kestis',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Cal Kestis with a vivid green kyber crystal. A classic Jedi hue for the Fallen Order survivor.',
    hiltNotes: 'Customizable hilt rebuilt on Bogano, multiple material options.',
    config: {
      name: 'CalKestisGreen',
      baseColor: { r: 10, g: 225, b: 50 },
      clashColor: { r: 220, g: 255, b: 200 },
      lockupColor: { r: 160, g: 240, b: 140 },
      blastColor: { r: 130, g: 255, b: 100 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'eu-cal-kestis-orange',
    name: 'Cal Kestis (Orange)',
    character: 'Cal Kestis',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Cal Kestis with a rare orange kyber crystal. A warm amber glow unique among Jedi.',
    config: {
      name: 'CalKestisOrange',
      baseColor: { r: 255, g: 140, b: 0 },
      clashColor: { r: 255, g: 230, b: 170 },
      lockupColor: { r: 255, g: 180, b: 80 },
      blastColor: { r: 255, g: 160, b: 40 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 380,
      shimmer: 0.12,
      ledCount: 144,
    },
  },
  {
    id: 'eu-cal-kestis-purple',
    name: 'Cal Kestis (Purple)',
    character: 'Cal Kestis',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Cal Kestis with a purple kyber crystal. A rich violet blade straddling the line between light and dark.',
    config: {
      name: 'CalKestisPurple',
      baseColor: { r: 160, g: 30, b: 255 },
      clashColor: { r: 220, g: 180, b: 255 },
      lockupColor: { r: 190, g: 100, b: 255 },
      blastColor: { r: 180, g: 80, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
    },
  },
  {
    id: 'eu-cal-kestis-red',
    name: 'Cal Kestis (Red - Dark Side)',
    character: 'Cal Kestis',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Cal Kestis in a dark-side alternate path. Bleeding red crystal with unstable, crackling energy.',
    config: {
      name: 'CalKestisRed',
      baseColor: { r: 255, g: 0, b: 10 },
      clashColor: { r: 255, g: 200, b: 160 },
      lockupColor: { r: 255, g: 100, b: 60 },
      blastColor: { r: 255, g: 70, b: 40 },
      style: 'unstable',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 250,
      retractionMs: 300,
      shimmer: 0.35,
      ledCount: 144,
    },
  },

  // ── Merrin ──
  {
    id: 'eu-merrin-green',
    name: 'Merrin (Green - Nightsister)',
    character: 'Merrin',
    era: 'expanded-universe',
    affiliation: 'neutral',
    description:
      'Merrin\'s green-tinged blade from Jedi: Survivor. Infused with Nightsister magick, the blade has an eerie, spectral quality.',
    hiltNotes: 'Lightsaber constructed with Nightsister-influenced components.',
    config: {
      name: 'MerrinNightsister',
      baseColor: { r: 0, g: 210, b: 60 },
      clashColor: { r: 180, g: 255, b: 180 },
      lockupColor: { r: 100, g: 240, b: 120 },
      blastColor: { r: 80, g: 255, b: 100 },
      style: 'plasma',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 340,
      retractionMs: 500,
      shimmer: 0.22,
      ledCount: 144,
      magickGlow: true,
    },
  },

  // ── Stellan Gios (High Republic) ──
  {
    id: 'eu-stellan-gios-blue',
    name: 'Stellan Gios (Blue - Crossguard)',
    character: 'Stellan Gios',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Stellan Gios\'s blue crossguard lightsaber from the High Republic era. A noble, radiant azure blade.',
    hiltNotes: 'Ornate crossguard hilt of High Republic Jedi design, predating Kylo Ren\'s by centuries.',
    topologyNotes: 'Main blade with two crossguard quillons.',
    config: {
      name: 'StellanGios',
      baseColor: { r: 30, g: 120, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 140, g: 180, b: 255 },
      blastColor: { r: 100, g: 160, b: 255 },
      style: 'photon',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 380,
      retractionMs: 420,
      shimmer: 0.06,
      ledCount: 144,
      crossguard: true,
    },
  },

  // ── Vernestra Rwoh ──
  {
    id: 'eu-vernestra-rwoh-purple',
    name: 'Vernestra Rwoh (Purple - Lightwhip)',
    character: 'Vernestra Rwoh',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Vernestra Rwoh\'s unique purple lightsaber that can convert into a lightwhip. A vibrant violet with fluid motion.',
    hiltNotes: 'Modified hilt with lightwhip conversion mechanism, youngest Jedi Knight in a generation.',
    topologyNotes: 'Standard blade mode, but hilt supports lightwhip extension.',
    config: {
      name: 'VernrestaRwoh',
      baseColor: { r: 140, g: 20, b: 255 },
      clashColor: { r: 210, g: 170, b: 255 },
      lockupColor: { r: 180, g: 100, b: 255 },
      blastColor: { r: 170, g: 80, b: 255 },
      style: 'pulse',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 350,
      retractionMs: 400,
      shimmer: 0.18,
      ledCount: 144,
      lightwhipMode: true,
    },
  },

  // ── Kelleran Beq ──
  {
    id: 'eu-kelleran-beq-blue',
    name: 'Kelleran Beq (Blue)',
    character: 'Kelleran Beq',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Kelleran Beq\'s blue lightsaber. The Sabered Hand, champion of the Jedi Temple training grounds who rescued Grogu during Order 66.',
    hiltNotes: 'Dual-wielder with standard Jedi hilts.',
    config: {
      name: 'KelleranBeq',
      baseColor: { r: 20, g: 90, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 150, g: 185, b: 255 },
      blastColor: { r: 110, g: 165, b: 255 },
      style: 'rotoscope',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 350,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Shin Hati ──
  {
    id: 'eu-shin-hati-orange',
    name: 'Shin Hati (Orange)',
    character: 'Shin Hati',
    era: 'expanded-universe',
    affiliation: 'neutral',
    description:
      'Shin Hati\'s orange lightsaber. A sharp, intense amber-orange blade wielded by Baylan Skoll\'s apprentice.',
    hiltNotes: 'Simple, functional hilt reflecting her pragmatic training under Baylan.',
    config: {
      name: 'ShinHati',
      baseColor: { r: 255, g: 120, b: 0 },
      clashColor: { r: 255, g: 225, b: 160 },
      lockupColor: { r: 255, g: 170, b: 70 },
      blastColor: { r: 255, g: 150, b: 30 },
      style: 'fire',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.12,
      ledCount: 144,
      fireSize: 0.5,
      sparkRate: 0.6,
      heatSpread: 0.4,
    },
  },

  // ── Marrok ──
  {
    id: 'eu-marrok-red',
    name: 'Marrok (Red)',
    character: 'Marrok',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Marrok\'s red lightsaber. A sinister, smoky crimson wielded by the mysterious dark-side mercenary. Upon death, green Nightsister magick was released.',
    hiltNotes: 'Inquisitor-style hilt beneath dark armor.',
    config: {
      name: 'Marrok',
      baseColor: { r: 230, g: 10, b: 10 },
      clashColor: { r: 255, g: 190, b: 140 },
      lockupColor: { r: 255, g: 90, b: 50 },
      blastColor: { r: 255, g: 70, b: 30 },
      style: 'fire',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 260,
      retractionMs: 400,
      shimmer: 0.25,
      ledCount: 144,
    },
  },

  // ── Trilla Suduri (Fallen Order version) ──
  {
    id: 'eu-trilla-suduri-red',
    name: 'Trilla Suduri (Red)',
    character: 'Trilla Suduri',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Trilla Suduri\'s red double-bladed lightsaber as the Second Sister in Jedi: Fallen Order. A controlled, lethal crimson.',
    hiltNotes: 'Inquisitor spinning double-bladed hilt.',
    config: {
      name: 'TrillaSuduri',
      baseColor: { r: 220, g: 5, b: 15 },
      clashColor: { r: 255, g: 185, b: 145 },
      lockupColor: { r: 255, g: 85, b: 60 },
      blastColor: { r: 255, g: 65, b: 40 },
      style: 'stable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 220,
      retractionMs: 280,
      shimmer: 0.16,
      ledCount: 144,
    },
  },

  // ── Dagan Gera (Jedi: Survivor) ──
  {
    id: 'eu-dagan-gera-red',
    name: 'Dagan Gera (Red)',
    character: 'Dagan Gera',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Dagan Gera\'s corrupted red lightsaber from Jedi: Survivor. Once a High Republic Jedi, his blade now burns with betrayal and obsession.',
    hiltNotes: 'Ancient High Republic hilt design, single and crossguard modes.',
    config: {
      name: 'DaganGera',
      baseColor: { r: 240, g: 15, b: 5 },
      clashColor: { r: 255, g: 210, b: 170 },
      lockupColor: { r: 255, g: 110, b: 70 },
      blastColor: { r: 255, g: 90, b: 40 },
      style: 'unstable',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 200,
      retractionMs: 280,
      shimmer: 0.3,
      ledCount: 144,
    },
  },

  // ── Bode Akuna (Jedi: Survivor) ──
  {
    id: 'eu-bode-akuna-red',
    name: 'Bode Akuna (Red)',
    character: 'Bode Akuna',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Bode Akuna\'s revealed red lightsaber from Jedi: Survivor. A hidden Jedi turned ISB agent, his blade reflects his betrayal.',
    hiltNotes: 'Concealed standard hilt, dual-wielded with a blaster.',
    config: {
      name: 'BodeAkuna',
      baseColor: { r: 255, g: 20, b: 20 },
      clashColor: { r: 255, g: 200, b: 160 },
      lockupColor: { r: 255, g: 105, b: 65 },
      blastColor: { r: 255, g: 80, b: 45 },
      style: 'plasma',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.14,
      ledCount: 144,
      frequency: 1.2,
      phaseSpeed: 0.8,
    },
  },

  // ── Taron Malicos (Fallen Order) ──
  {
    id: 'eu-taron-malicos-red',
    name: 'Taron Malicos (Red)',
    character: 'Taron Malicos',
    era: 'expanded-universe',
    affiliation: 'sith',
    description:
      'Taron Malicos\'s dual red lightsabers from Dathomir. A fallen Jedi Master corrupted by the dark side and Nightbrother influence.',
    hiltNotes: 'Dual standard hilts, scarred and weathered from years on Dathomir.',
    config: {
      name: 'TaronMalicos',
      baseColor: { r: 210, g: 0, b: 5 },
      clashColor: { r: 255, g: 175, b: 130 },
      lockupColor: { r: 255, g: 80, b: 45 },
      blastColor: { r: 255, g: 55, b: 25 },
      style: 'fire',
      ignition: 'stutter',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 320,
      shimmer: 0.28,
      ledCount: 144,
    },
  },

  // ── Avar Kriss (High Republic) ──
  {
    id: 'eu-avar-kriss-green',
    name: 'Avar Kriss (Green)',
    character: 'Avar Kriss',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description:
      'Avar Kriss\'s green lightsaber from the High Republic. A brilliant, inspiring emerald blade befitting the Hero of Hetzal.',
    hiltNotes: 'Elegant High Republic hilt design, convertible to a lightwhip configuration.',
    config: {
      name: 'AvarKriss',
      baseColor: { r: 0, g: 210, b: 45 },
      clashColor: { r: 200, g: 255, b: 190 },
      lockupColor: { r: 120, g: 240, b: 130 },
      blastColor: { r: 90, g: 255, b: 110 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 400,
      shimmer: 0.07,
      ledCount: 144,
    },
  },
  {
    id: 'eu-keeve-trennis-green',
    name: 'Keeve Trennis',
    character: 'Keeve Trennis',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description: 'High Republic Jedi Knight with a green blade that shimmers like the aurora borealis.',
    config: {
      name: 'KeeveTrennis',
      baseColor: { r: 30, g: 200, b: 80 },
      clashColor: { r: 200, g: 255, b: 200 },
      lockupColor: { r: 150, g: 230, b: 150 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'aurora',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 350,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      waveCount: 3,
      driftSpeed: 0.5,
    },
  },
  {
    id: 'eu-loden-greatstorm-blue',
    name: 'Loden Greatstorm',
    character: 'Loden Greatstorm',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description: 'High Republic Jedi Master — a brilliant blue photon blade radiating calm strength.',
    config: {
      name: 'LodenGreatstorm',
      baseColor: { r: 40, g: 120, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 180, g: 200, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'photon',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.05,
      ledCount: 144,
    },
  },
  {
    id: 'eu-marchion-ro-nihil',
    name: 'Marchion Ro (Nihil)',
    character: 'Marchion Ro',
    era: 'expanded-universe',
    affiliation: 'sith',
    description: 'The Eye of the Nihil — a fractured, corrupted blade symbolizing his war against the Jedi.',
    config: {
      name: 'MarchionRo',
      baseColor: { r: 180, g: 20, b: 30 },
      clashColor: { r: 255, g: 100, b: 100 },
      lockupColor: { r: 200, g: 50, b: 50 },
      blastColor: { r: 255, g: 150, b: 100 },
      style: 'crystalShatter',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 400,
      retractionMs: 300,
      shimmer: 0.2,
      ledCount: 144,
    },
  },
  {
    id: 'eu-elzar-mann-purple',
    name: 'Elzar Mann',
    character: 'Elzar Mann',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description: 'Unconventional High Republic Jedi. Plasma arcs dance along his blue-purple blade.',
    config: {
      name: 'ElzarMann',
      baseColor: { r: 80, g: 60, b: 220 },
      clashColor: { r: 200, g: 180, b: 255 },
      lockupColor: { r: 150, g: 130, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'plasma',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 350,
      retractionMs: 500,
      shimmer: 0.1,
      ledCount: 144,
      frequency: 1.0,
      phaseSpeed: 1.2,
    },
  },
  {
    id: 'eu-orla-jareni-white',
    name: 'Orla Jareni (Wayseeker)',
    character: 'Orla Jareni',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description: 'Independent Wayseeker who left the traditional Jedi path. White prismatic blade.',
    config: {
      name: 'OrlaJareni',
      baseColor: { r: 230, g: 235, b: 250 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 240 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'prism',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      facets: 5,
      rotationSpeed: 1.0,
    },
  },
  {
    id: 'eu-burryaga-green',
    name: 'Burryaga (Wookiee Jedi)',
    character: 'Burryaga',
    era: 'expanded-universe',
    affiliation: 'jedi',
    description: 'Rare Wookiee Jedi of the High Republic era. Oversized green blade with slow, powerful ignition.',
    config: {
      name: 'Burryaga',
      baseColor: { r: 20, g: 180, b: 40 },
      clashColor: { r: 180, g: 255, b: 180 },
      lockupColor: { r: 150, g: 220, b: 150 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 600,
      retractionMs: 500,
      shimmer: 0.03,
      ledCount: 144,
    },
  },
];
