import type { Preset } from '../types.js';

export const LEGENDS_PRESETS: Preset[] = [
  // ── Darth Revan (Purple) ──
  {
    id: 'legends-darth-revan-purple',
    name: 'Darth Revan (Purple)',
    character: 'Darth Revan',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'neutral',
    tier: 'detailed',
    description:
      'Revan\'s iconic purple lightsaber. The blade of the Prodigal Knight straddles light and dark — a deep, regal violet that has become one of the most recognized sabers in all of Star Wars.',
    hiltNotes: 'Distinctive hilt with angled emitter shroud, often paired with his Mandalorian mask.',
    config: {
      name: 'DarthRevan',
      baseColor: { r: 140, g: 0, b: 240 },
      clashColor: { r: 220, g: 180, b: 255 },
      lockupColor: { r: 180, g: 80, b: 255 },
      blastColor: { r: 170, g: 60, b: 255 },
      dragColor: { r: 255, g: 180, b: 80 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Darth Revan (Red - Sith Lord) ──
  {
    id: 'legends-darth-revan-red',
    name: 'Darth Revan (Red - Sith Lord)',
    character: 'Darth Revan',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Revan as Sith Lord during the Jedi Civil War. A deep, commanding crimson blade wielded by the Dark Lord before his redemption.',
    hiltNotes: 'Same distinctive hilt, now with a bled kyber crystal.',
    config: {
      name: 'RevanSith',
      baseColor: { r: 200, g: 0, b: 10 },
      clashColor: { r: 255, g: 180, b: 130 },
      lockupColor: { r: 255, g: 80, b: 50 },
      blastColor: { r: 255, g: 60, b: 30 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 350,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Bastila Shan ──
  {
    id: 'legends-bastila-shan-yellow',
    name: 'Bastila Shan (Yellow - Double-Bladed)',
    character: 'Bastila Shan',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Bastila Shan\'s golden yellow double-bladed lightsaber. The warm, radiant blade of the Jedi Sentinel who wielded Battle Meditation.',
    hiltNotes: 'Long double-bladed hilt, saberstaff configuration.',
    config: {
      name: 'BastilaYellow',
      baseColor: { r: 255, g: 220, b: 0 },
      clashColor: { r: 255, g: 255, b: 180 },
      lockupColor: { r: 255, g: 240, b: 100 },
      blastColor: { r: 255, g: 235, b: 60 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 300,
      retractionMs: 350,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Darth Nihilus ──
  {
    id: 'legends-darth-nihilus-red',
    name: 'Darth Nihilus (Red)',
    character: 'Darth Nihilus',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'The Lord of Hunger\'s red lightsaber. A deep, consuming crimson that seems to devour the light around it, mirroring Nihilus\'s insatiable hunger through the Force. Cracked-crystal lore from KOTOR II justifies the unstable shimmer — his blade drinks the life around it.',
    hiltNotes: 'Standard Sith hilt, though Nihilus rarely relied on his saber over his devastating Force drain.',
    config: {
      name: 'DarthNihilus',
      baseColor: { r: 180, g: 0, b: 0 },
      clashColor: { r: 255, g: 140, b: 100 },
      lockupColor: { r: 220, g: 50, b: 30 },
      blastColor: { r: 200, g: 30, b: 15 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'unstable',
      ignition: 'pulse-wave',
      retraction: 'spaghettify',
      ignitionMs: 200,
      retractionMs: 500,
      shimmer: 0.35,
      ledCount: 144,
      noiseLevel: 0.15,
      flicker: 0.6,
      swingFxIntensity: 0.2,
    },
  },

  // ── Darth Sion ──
  {
    id: 'legends-darth-sion-red',
    name: 'Darth Sion (Red)',
    character: 'Darth Sion',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'The Lord of Pain\'s red lightsaber. A harsh, angry crimson — cracked and raw like Sion\'s own shattered body held together by sheer rage.',
    config: {
      name: 'DarthSion',
      baseColor: { r: 200, g: 10, b: 0 },
      clashColor: { r: 255, g: 180, b: 130 },
      lockupColor: { r: 240, g: 70, b: 30 },
      blastColor: { r: 230, g: 50, b: 15 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'shatter',
      ignition: 'fracture',
      retraction: 'dissolve',
      ignitionMs: 250,
      retractionMs: 300,
      shimmer: 0.32,
      ledCount: 144,
      flicker: 0.8,
      noiseLevel: 0.18,
      swingFxIntensity: 0.5,
    },
  },

  // ── Darth Malak ──
  {
    id: 'legends-darth-malak-red',
    name: 'Darth Malak (Red)',
    character: 'Darth Malak',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Darth Malak\'s red lightsaber. A bold, domineering scarlet wielded by Revan\'s fallen apprentice and the Dark Lord of the Sith during the Jedi Civil War.',
    hiltNotes: 'Large hilt matching Malak\'s imposing stature.',
    config: {
      name: 'DarthMalak',
      baseColor: { r: 235, g: 10, b: 10 },
      clashColor: { r: 255, g: 200, b: 160 },
      lockupColor: { r: 255, g: 90, b: 50 },
      blastColor: { r: 255, g: 70, b: 30 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Meetra Surik / Jedi Exile ──
  {
    id: 'legends-meetra-surik-cyan',
    name: 'Meetra Surik / Jedi Exile (Cyan)',
    character: 'Meetra Surik',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'The Jedi Exile\'s cyan lightsaber. A tranquil, piercing icy-blue blade rebuilt after the Mandalorian Wars. Color is configurable in-game — cyan is the canonical default.',
    hiltNotes: 'Rebuilt hilt after years without a lightsaber following Malachor V.',
    config: {
      name: 'MeetraSurik',
      baseColor: { r: 0, g: 200, b: 240 },
      clashColor: { r: 180, g: 240, b: 255 },
      lockupColor: { r: 100, g: 220, b: 255 },
      blastColor: { r: 80, g: 210, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 340,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Starkiller / Galen Marek (Light Side) ──
  {
    id: 'legends-starkiller-blue',
    name: 'Starkiller / Galen Marek (Blue)',
    character: 'Galen Marek',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Starkiller\'s blue lightsaber after turning to the light. A brilliant cobalt blade wielded with raw, unbridled power by Vader\'s secret apprentice turned rebel hero.',
    hiltNotes: 'Compact hilt with reverse grip. Kento Marek\'s original lightsaber.',
    config: {
      name: 'StarkillerBlue',
      baseColor: { r: 20, g: 70, b: 255 },
      clashColor: { r: 200, g: 215, b: 255 },
      lockupColor: { r: 140, g: 170, b: 255 },
      blastColor: { r: 100, g: 150, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'photon',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 280,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.55,
      noiseLevel: 0.06,
    },
  },

  // ── Starkiller (Dark Side) ──
  {
    id: 'legends-starkiller-red',
    name: 'Starkiller / Galen Marek (Red - Dark Side)',
    character: 'Galen Marek',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Starkiller\'s red lightsabers from the dark-side path. Dual-wielded crimson blades burning with unchecked fury — the canonical unstable blade of Force Unleashed, cracked-crystal dark-side corruption made visible.',
    hiltNotes: 'Dual reverse-grip hilts for the Sith Stalker armor configuration.',
    config: {
      name: 'StarkillerRed',
      baseColor: { r: 255, g: 5, b: 5 },
      clashColor: { r: 255, g: 200, b: 150 },
      lockupColor: { r: 255, g: 100, b: 55 },
      blastColor: { r: 255, g: 75, b: 35 },
      dragColor: { r: 255, g: 150, b: 0 },
      style: 'unstable',
      ignition: 'crackle',
      retraction: 'shatter',
      ignitionMs: 150,
      retractionMs: 250,
      shimmer: 0.5,
      ledCount: 144,
      flicker: 0.7,
      noiseLevel: 0.18,
      swingFxIntensity: 0.6,
    },
  },

  // ── Mara Jade ──
  {
    id: 'legends-mara-jade-purple',
    name: 'Mara Jade (Purple)',
    character: 'Mara Jade',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Mara Jade\'s purple lightsaber. The Emperor\'s Hand turned Jedi Master and wife of Luke Skywalker. A magenta-tinged violet reflecting her complex journey.',
    hiltNotes: 'Sleek, functional hilt. Later used Luke\'s spare blue saber as well.',
    config: {
      name: 'MaraJadePurple',
      baseColor: { r: 180, g: 20, b: 220 },
      clashColor: { r: 230, g: 180, b: 255 },
      lockupColor: { r: 210, g: 100, b: 240 },
      blastColor: { r: 200, g: 80, b: 230 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Kyle Katarn (Blue - primary, Dark Forces / Jedi Knight games) ──
  {
    id: 'legends-kyle-katarn-blue',
    name: 'Kyle Katarn (Blue)',
    character: 'Kyle Katarn',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Kyle Katarn\'s blue lightsaber from the Dark Forces / Jedi Knight games — his most canonically recognized blade (Jedi Outcast, Jedi Academy). The dependable cobalt blade of the mercenary-turned-Jedi Battlemaster.',
    hiltNotes: 'Rahn\'s lightsaber, passed to Kyle. Simple, rugged design befitting a soldier.',
    config: {
      name: 'KyleKatarnBlue',
      baseColor: { r: 0, g: 120, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 140, g: 180, b: 255 },
      blastColor: { r: 110, g: 165, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Kyle Katarn (Green - Legacy era secondary) ──
  {
    id: 'legends-kyle-katarn-green',
    name: 'Kyle Katarn (Green - Legacy era)',
    character: 'Kyle Katarn',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Kyle Katarn\'s later green lightsaber from Legacy-era appearances. A dependable emerald blade wielded by the Jedi Battlemaster of the New Jedi Order.',
    hiltNotes: 'Rahn\'s lightsaber, passed to Kyle. Simple, rugged design befitting a soldier.',
    config: {
      name: 'KyleKatarnGreen',
      baseColor: { r: 15, g: 200, b: 40 },
      clashColor: { r: 200, g: 255, b: 190 },
      lockupColor: { r: 120, g: 235, b: 130 },
      blastColor: { r: 90, g: 245, b: 100 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Jaina Solo ──
  {
    id: 'legends-jaina-solo-purple',
    name: 'Jaina Solo (Purple)',
    character: 'Jaina Solo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Jaina Solo\'s purple lightsaber. The Sword of the Jedi — daughter of Han and Leia, twin of Jacen, ace pilot, and the one who brought down Darth Caedus.',
    config: {
      name: 'JainaSolo',
      baseColor: { r: 150, g: 30, b: 255 },
      clashColor: { r: 215, g: 180, b: 255 },
      lockupColor: { r: 185, g: 100, b: 255 },
      blastColor: { r: 175, g: 75, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Jacen Solo (Blue - pre-fall Jedi) ──
  {
    id: 'legends-jacen-solo-blue',
    name: 'Jacen Solo (Blue - Pre-Fall Jedi)',
    character: 'Jacen Solo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Jacen Solo\'s blue lightsaber from his Jedi years. The son of Han and Leia, twin of Jaina, wielded this cerulean blade through the New Jedi Order era before his tragic descent into Darth Caedus.',
    hiltNotes: 'Standard Jedi hilt, plain and functional.',
    config: {
      name: 'JacenSoloJedi',
      baseColor: { r: 30, g: 110, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 140, g: 180, b: 255 },
      blastColor: { r: 110, g: 165, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Jacen Solo / Darth Caedus (Red) ──
  {
    id: 'legends-darth-caedus-red',
    name: 'Jacen Solo / Darth Caedus (Red)',
    character: 'Jacen Solo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Darth Caedus\'s red lightsaber. Once Jacen Solo with a blue blade, now the Sith Lord whose fall echoes Anakin\'s — a deep arterial red reflecting his tragic descent.',
    config: {
      name: 'DarthCaedus',
      baseColor: { r: 220, g: 0, b: 15 },
      clashColor: { r: 255, g: 185, b: 145 },
      lockupColor: { r: 250, g: 80, b: 50 },
      blastColor: { r: 240, g: 60, b: 30 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.12,
      ledCount: 144,
    },
  },

  // ── Corran Horn ──
  {
    id: 'legends-corran-horn-silver',
    name: 'Corran Horn (Silver/White)',
    character: 'Corran Horn',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Corran Horn\'s distinctive silver-white lightsaber, unique among Jedi. Built from a speeder bike throttle with a dual-phase mechanism.',
    hiltNotes: 'Constructed from a speeder bike throttle. Dual-phase: standard and extended reach.',
    config: {
      name: 'CorranHorn',
      baseColor: { r: 220, g: 225, b: 240 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 210, b: 230 },
      blastColor: { r: 210, g: 215, b: 240 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'rotoscope',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 350,
      retractionMs: 400,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Exar Kun (Jedi - pre-fall blue) ──
  {
    id: 'legends-exar-kun-jedi',
    name: 'Exar Kun (Blue - Pre-Fall Jedi)',
    character: 'Exar Kun',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Exar Kun\'s blue lightsaber from his Jedi apprenticeship under Vodo-Siosk Baas. A vivid azure blade — wielded before his descent into Sith lore and the Great Sith War.',
    hiltNotes: 'Standard Jedi hilt, before its later modification into the first known double-bladed saber.',
    config: {
      name: 'ExarKunJedi',
      baseColor: { r: 30, g: 80, b: 255 },
      clashColor: { r: 180, g: 200, b: 255 },
      lockupColor: { r: 120, g: 155, b: 255 },
      blastColor: { r: 90, g: 140, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Exar Kun (Sith - red double-bladed) ──
  {
    id: 'legends-exar-kun-sith',
    name: 'Exar Kun (Red - Sith Double-Bladed)',
    character: 'Exar Kun',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Exar Kun\'s red double-bladed lightsaber as Dark Lord of the Sith — the first known saberstaff in canon. A vivid, sinister crimson wielded by the Sith who nearly destroyed the Jedi 4,000 years before Yavin in the Great Sith War.',
    hiltNotes: 'The original double-bladed lightsaber design, modified from a standard Jedi hilt using Sith knowledge.',
    config: {
      name: 'ExarKunSith',
      baseColor: { r: 220, g: 10, b: 10 },
      clashColor: { r: 255, g: 190, b: 140 },
      lockupColor: { r: 245, g: 75, b: 40 },
      blastColor: { r: 230, g: 55, b: 25 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 260,
      retractionMs: 320,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Nomi Sunrider ──
  {
    id: 'legends-nomi-sunrider-green',
    name: 'Nomi Sunrider (Green)',
    character: 'Nomi Sunrider',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Nomi Sunrider\'s green lightsaber. Grand Master of the Jedi Order during the Great Sith War, her verdant blade symbolizes her reluctant but powerful rise to leadership.',
    config: {
      name: 'NomiSunrider',
      baseColor: { r: 0, g: 200, b: 30 },
      clashColor: { r: 190, g: 255, b: 180 },
      lockupColor: { r: 100, g: 235, b: 110 },
      blastColor: { r: 80, g: 245, b: 90 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 340,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Ulic Qel-Droma (Blue - Jedi era) ──
  {
    id: 'legends-ulic-qel-droma-blue',
    name: 'Ulic Qel-Droma (Blue)',
    character: 'Ulic Qel-Droma',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Ulic Qel-Droma\'s blue lightsaber. The tragic Jedi Knight who fell to the dark side as Exar Kun\'s Sith apprentice before redeeming himself.',
    config: {
      name: 'UlicQelDroma',
      baseColor: { r: 40, g: 100, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 140, g: 180, b: 255 },
      blastColor: { r: 110, g: 160, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Ulic Qel-Droma (Red - Sith era) ──
  {
    id: 'legends-ulic-qel-droma-red',
    name: 'Ulic Qel-Droma (Red - Sith Apprentice)',
    character: 'Ulic Qel-Droma',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Ulic Qel-Droma\'s red lightsaber during his tenure as Exar Kun\'s Sith apprentice. A deep, mournful crimson wielded before his redemption — the tragic weapon of the Fallen Jedi.',
    config: {
      name: 'UlicQelDromaSith',
      baseColor: { r: 210, g: 10, b: 10 },
      clashColor: { r: 255, g: 180, b: 140 },
      lockupColor: { r: 245, g: 80, b: 45 },
      blastColor: { r: 235, g: 60, b: 30 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.12,
      ledCount: 144,
    },
  },

  // ── Darth Bane ──
  {
    id: 'legends-darth-bane-red',
    name: 'Darth Bane (Red)',
    character: 'Darth Bane',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Darth Bane\'s red lightsaber. The creator of the Rule of Two — a deep, menacing crimson blade wielded by the Sith who reshaped the dark side forever.',
    hiltNotes: 'Curved hilt design. Bane later encased himself in orbalisks that served as living armor.',
    config: {
      name: 'DarthBane',
      baseColor: { r: 200, g: 0, b: 0 },
      clashColor: { r: 255, g: 170, b: 120 },
      lockupColor: { r: 240, g: 60, b: 30 },
      blastColor: { r: 225, g: 40, b: 15 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'fracture',
      retraction: 'drain',
      ignitionMs: 280,
      retractionMs: 350,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Darth Plagueis ──
  {
    id: 'legends-darth-plagueis-red',
    name: 'Darth Plagueis (Red)',
    character: 'Darth Plagueis',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Darth Plagueis\'s red lightsaber. The Wise — Sidious\'s master who could manipulate midi-chlorians to create life. The slow pulse evokes the life-giving, life-taking rhythm of his forbidden art.',
    hiltNotes: 'Elegant Muun-proportioned hilt.',
    config: {
      name: 'DarthPlagueis',
      baseColor: { r: 170, g: 0, b: 10 },
      clashColor: { r: 255, g: 160, b: 120 },
      lockupColor: { r: 220, g: 50, b: 30 },
      blastColor: { r: 200, g: 30, b: 15 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'pulse',
      ignition: 'drip-up',
      retraction: 'drain',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.15,
      ledCount: 144,
      pulseSpeed: 0.8,
      pulseMinBright: 0.3,
      noiseLevel: 0.05,
      swingFxIntensity: 0.2,
    },
  },

  // ── Darth Talon ──
  {
    id: 'legends-darth-talon-red',
    name: 'Darth Talon (Red)',
    character: 'Darth Talon',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Darth Talon\'s red lightsaber. The Twi\'lek Sith Lady from the Legacy era — a fierce, vivid scarlet blade matching her striking tattooed appearance.',
    config: {
      name: 'DarthTalon',
      baseColor: { r: 255, g: 15, b: 10 },
      clashColor: { r: 255, g: 210, b: 170 },
      lockupColor: { r: 255, g: 100, b: 60 },
      blastColor: { r: 255, g: 80, b: 40 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 300,
      shimmer: 0.14,
      ledCount: 144,
    },
  },

  // ── Darth Krayt ──
  {
    id: 'legends-darth-krayt-red',
    name: 'Darth Krayt (Red)',
    character: 'Darth Krayt',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Darth Krayt\'s red lightsaber. Once A\'Sharad Hett the Tusken Jedi, now the founder of the One Sith.',
    hiltNotes: 'Dual lightsabers, coral-encrusted Yuuzhan Vong-influenced hilts.',
    config: {
      name: 'DarthKrayt',
      baseColor: { r: 210, g: 5, b: 0 },
      clashColor: { r: 255, g: 180, b: 130 },
      lockupColor: { r: 245, g: 70, b: 35 },
      blastColor: { r: 235, g: 50, b: 20 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'fracture',
      retraction: 'dissolve',
      ignitionMs: 220,
      retractionMs: 300,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.45,
    },
  },

  // ── Cade Skywalker ──
  {
    id: 'legends-cade-skywalker-blue',
    name: 'Cade Skywalker (Blue)',
    character: 'Cade Skywalker',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Cade Skywalker\'s blue lightsaber. The reluctant Legacy-era descendant of Luke Skywalker — a rough-edged blue blade.',
    config: {
      name: 'CadeSkywalker',
      baseColor: { r: 30, g: 90, b: 255 },
      clashColor: { r: 200, g: 215, b: 255 },
      lockupColor: { r: 140, g: 170, b: 255 },
      blastColor: { r: 110, g: 155, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 320,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Maris Brood ──
  {
    id: 'legends-maris-brood-red',
    name: 'Maris Brood (Red - Tonfa)',
    character: 'Maris Brood',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Maris Brood\'s red tonfa-style lightsabers. Unique guard shoto configuration — the Zabrak Padawan fell to the dark side on Felucia.',
    hiltNotes: 'Paired tonfa-grip lightsabers with perpendicular handles.',
    config: {
      name: 'MarisBrood',
      baseColor: { r: 240, g: 10, b: 20 },
      clashColor: { r: 255, g: 195, b: 160 },
      lockupColor: { r: 255, g: 90, b: 60 },
      blastColor: { r: 255, g: 70, b: 40 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 220,
      retractionMs: 280,
      shimmer: 0.14,
      ledCount: 100,
    },
  },

  // ── Rahm Kota ──
  {
    id: 'legends-rahm-kota-green',
    name: 'Rahm Kota (Green)',
    character: 'Rahm Kota',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'General Rahm Kota\'s green lightsaber. The grizzled Clone Wars veteran and militia leader — a weathered, battle-hardened emerald blade.',
    hiltNotes: 'Katana-inspired hilt with wrapped grip.',
    config: {
      name: 'RahmKota',
      baseColor: { r: 10, g: 190, b: 35 },
      clashColor: { r: 190, g: 255, b: 180 },
      lockupColor: { r: 110, g: 230, b: 120 },
      blastColor: { r: 80, g: 240, b: 95 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 360,
      retractionMs: 420,
      shimmer: 0.07,
      ledCount: 144,
    },
  },

  // ── PROXY ──
  {
    id: 'legends-proxy-prism',
    name: 'PROXY (Variable - Prism)',
    character: 'PROXY',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'other',
    tier: 'detailed',
    description:
      'PROXY\'s holographic lightsaber — constantly shifting color and form as the droid mimics various Jedi and Sith combatants.',
    hiltNotes: 'Holographic projection, changes to match whatever combatant PROXY is imitating.',
    config: {
      name: 'PROXY',
      baseColor: { r: 100, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 150, b: 255 },
      blastColor: { r: 255, g: 200, b: 100 },
      style: 'prism',
      ignition: 'glitch',
      retraction: 'shatter',
      ignitionMs: 180,
      retractionMs: 250,
      shimmer: 0.4,
      ledCount: 144,
      colorShiftSpeed: 2.0,
      facets: 8,
      rotationSpeed: 2.5,
      swingFxIntensity: 0.5,
    },
  },

  // ── Darth Traya / Kreia ──
  {
    id: 'legends-darth-traya-purple',
    name: 'Darth Traya / Kreia (Purple)',
    character: 'Kreia',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'neutral',
    tier: 'detailed',
    description:
      'Darth Traya\'s purple lightsaber — or rather, lightsabers, as she wielded three simultaneously through the Force. The archetypal grey character of Legends, teaching her student to question both Jedi and Sith dogma.',
    hiltNotes: 'Three lightsabers controlled telekinetically.',
    config: {
      name: 'DarthTraya',
      baseColor: { r: 120, g: 40, b: 180 },
      clashColor: { r: 200, g: 170, b: 240 },
      lockupColor: { r: 160, g: 90, b: 210 },
      blastColor: { r: 150, g: 70, b: 200 },
      dragColor: { r: 255, g: 180, b: 80 },
      style: 'aurora',
      ignition: 'drip-up',
      retraction: 'unravel',
      ignitionMs: 400,
      retractionMs: 550,
      shimmer: 0.25,
      ledCount: 144,
      waveCount: 6,
      driftSpeed: 0.4,
      noiseLevel: 0.08,
      swingFxIntensity: 0.3,
    },
  },

  // ── Visas Marr ──
  {
    id: 'legends-visas-marr-red',
    name: 'Visas Marr (Red)',
    character: 'Visas Marr',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Visas Marr\'s red lightsaber. The blind Miraluka Sith assassin bound to Darth Nihilus — wielded for most of her career before finding redemption through the Jedi Exile.',
    hiltNotes: 'Standard Sith hilt, later swapped for a Jedi crystal if redeemed.',
    config: {
      name: 'VisasMarr',
      baseColor: { r: 200, g: 0, b: 15 },
      clashColor: { r: 255, g: 170, b: 130 },
      lockupColor: { r: 240, g: 60, b: 40 },
      blastColor: { r: 220, g: 40, b: 20 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 400,
      shimmer: 0.1,
      ledCount: 144,
    },
  },

  // ── Visas Marr (Redeemed - Blue) ──
  {
    id: 'legends-visas-marr-redeemed',
    name: 'Visas Marr (Blue - Redeemed)',
    character: 'Visas Marr',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'Visas Marr\'s blue lightsaber after her redemption through the Jedi Exile. The blind Miraluka refitted her hilt with a Jedi crystal, symbolizing the light she never physically saw but always sensed.',
    hiltNotes: 'Reconstructed hilt with Jedi crystal after her redemption.',
    config: {
      name: 'VisasMarrRedeemed',
      baseColor: { r: 30, g: 110, b: 255 },
      clashColor: { r: 200, g: 220, b: 255 },
      lockupColor: { r: 140, g: 180, b: 255 },
      blastColor: { r: 110, g: 165, b: 255 },
      dragColor: { r: 255, g: 200, b: 100 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
    },
  },

  // ── Darth Vitiate / Valkorion ──
  {
    id: 'legends-darth-vitiate-red',
    name: 'Darth Vitiate / Valkorion (Red)',
    character: 'Darth Vitiate',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'The Sith Emperor who lived for over a thousand years. A blade of ancient, terrifying power — deep blood-red, wielded by the consumer of worlds.',
    config: {
      name: 'DarthVitiate',
      baseColor: { r: 180, g: 0, b: 0 },
      clashColor: { r: 255, g: 150, b: 100 },
      lockupColor: { r: 220, g: 40, b: 20 },
      blastColor: { r: 200, g: 20, b: 10 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'pulse-wave',
      retraction: 'spaghettify',
      ignitionMs: 300,
      retractionMs: 600,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Darth Malgus (SWTOR) ──
  {
    id: 'legends-darth-malgus-red',
    name: 'Darth Malgus (Red)',
    character: 'Darth Malgus',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Darth Malgus\'s red lightsaber. The cybernetic Sith Lord of the SWTOR era — wielder of the deep crimson blade that sacked the Jedi Temple on Coruscant.',
    hiltNotes: 'Imposing Sith-era hilt, matched to his heavy armored physique.',
    config: {
      name: 'DarthMalgus',
      baseColor: { r: 220, g: 5, b: 10 },
      clashColor: { r: 255, g: 180, b: 140 },
      lockupColor: { r: 250, g: 80, b: 45 },
      blastColor: { r: 240, g: 55, b: 25 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // BANTAM ERA / NEW JEDI ORDER NOVELS
  // ═══════════════════════════════════════════════════════════════════

  // ── Anakin Solo (Sword of the Jedi era) ──
  {
    id: 'legends-anakin-solo-blue',
    name: 'Anakin Solo (New Jedi Order)',
    character: 'Anakin Solo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Han and Leia\'s youngest, named for his grandfather. A bright Jedi blue with quick ignition reflecting his prodigious raw talent. Killed at Myrkr in the Yuuzhan Vong war — a generation\'s loss.',
    hiltNotes: 'Skywalker-lineage hilt with embedded chrysopaz crystal — built by Anakin during his time as Luke\'s apprentice.',
    config: {
      name: 'AnakinSolo',
      baseColor: { r: 30, g: 130, b: 245 },
      clashColor: { r: 230, g: 240, b: 255 },
      lockupColor: { r: 150, g: 200, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 320,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Ben Skywalker ──
  {
    id: 'legends-ben-skywalker-blue',
    name: 'Ben Skywalker',
    character: 'Ben Skywalker',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Luke and Mara Jade\'s son. The Skywalker line continued through Legacy of the Force and the Fate of the Jedi novels. A clean Jedi blue with steady measured shimmer reflecting his thoughtful, watchful temperament.',
    hiltNotes: 'A streamlined Skywalker-pattern hilt; built under his father\'s instruction.',
    config: {
      name: 'BenSkywalker',
      baseColor: { r: 25, g: 115, b: 240 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 140, g: 200, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Tenel Ka Djo ──
  {
    id: 'legends-tenel-ka-turquoise',
    name: 'Tenel Ka Djo',
    character: 'Tenel Ka Djo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Hapan princess and Jedi Knight, eventually Queen Mother of the Hapes Consortium. Her unique turquoise blade reflects the rancor-tooth crystal she crafted from her single-armed combat training arc.',
    hiltNotes: 'Single-handed grip optimized after her left arm was lost in a Force training accident. Hapan royal accents along the pommel.',
    config: {
      name: 'TenelKa',
      baseColor: { r: 50, g: 200, b: 220 },
      clashColor: { r: 220, g: 250, b: 255 },
      lockupColor: { r: 150, g: 230, b: 240 },
      blastColor: { r: 240, g: 255, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.07,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Lowbacca ──
  {
    id: 'legends-lowbacca-bronze',
    name: 'Lowbacca (Wookiee Jedi)',
    character: 'Lowbacca',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Chewbacca\'s nephew and a member of Luke\'s academy. A rare Wookiee Jedi who built a single-bladed saber with a rich amber-bronze crystal — the warm earth-tones of Kashyyyk distilled into a blade.',
    hiltNotes: 'Wookiee-sized hilt forged from Kashyyyk metals; bandolier mount for hands-free carry. Often paired with his miniature droid Em Teedee.',
    config: {
      name: 'Lowbacca',
      baseColor: { r: 230, g: 150, b: 50 },
      clashColor: { r: 255, g: 220, b: 150 },
      lockupColor: { r: 255, g: 180, b: 100 },
      blastColor: { r: 255, g: 230, b: 180 },
      style: 'stable',
      ignition: 'scroll',
      retraction: 'scroll',
      ignitionMs: 480,
      retractionMs: 440,
      shimmer: 0.07,
      ledCount: 144,
      swingFxIntensity: 0.45,
    },
  },

  // ── Joruus C'baoth ──
  {
    id: 'legends-joruus-cbaoth-green',
    name: "Joruus C'baoth",
    character: "Joruus C'baoth",
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Insane clone of Jedi Master Jorus C\'baoth, ally to Grand Admiral Thrawn during the Heir to the Empire trilogy. A corrupted forest-green blade with high shimmer — the Jedi color worn over a fractured mind. Light-side affiliation by lineage but his actions were Sith-aligned.',
    hiltNotes: 'A pre-Empire Jedi Master\'s hilt, dented and worn from his decades on Wayland.',
    config: {
      name: 'JoruusCbaoth',
      baseColor: { r: 0, g: 230, b: 50 },
      clashColor: { r: 220, g: 255, b: 220 },
      lockupColor: { r: 140, g: 250, b: 130 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'unstable',
      ignition: 'crackle',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 480,
      shimmer: 0.28,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.1,
    },
  },

  // ── Vergere ──
  {
    id: 'legends-vergere-yellow',
    name: 'Vergere',
    character: 'Vergere',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'neutral',
    tier: 'detailed',
    description:
      'Fosh Jedi who served the Old Republic, taught Jacen Solo unconventional Force philosophy, and may have been Sith all along. A vibrant gold-yellow blade with warm shimmer — the color of someone who walked between light and dark for centuries.',
    hiltNotes: 'Slim ancient hilt with avian-feathered grip; predates the Clone Wars by decades.',
    config: {
      name: 'Vergere',
      baseColor: { r: 255, g: 210, b: 0 },
      clashColor: { r: 255, g: 250, b: 200 },
      lockupColor: { r: 255, g: 220, b: 100 },
      blastColor: { r: 255, g: 240, b: 180 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 420,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // KOTOR / KOTOR 2 ADDITIONAL CAST
  // ═══════════════════════════════════════════════════════════════════

  // ── Jolee Bindo ──
  {
    id: 'legends-jolee-bindo-blue',
    name: 'Jolee Bindo',
    character: 'Jolee Bindo',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'The grouchy hermit Jedi from Kashyyyk who joined Revan\'s party in KOTOR. A muted older-Jedi blue with steady, unhurried ignition — the blade of someone who has stopped trying to prove anything.',
    hiltNotes: 'Old Republic Jedi hilt, worn pommel, hand-wrapped grip showing decades of use.',
    config: {
      name: 'JoleeBindo',
      baseColor: { r: 50, g: 120, b: 220 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 160, g: 200, b: 250 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 380,
      retractionMs: 440,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Juhani ──
  {
    id: 'legends-juhani-cyan',
    name: 'Juhani (Cathar Jedi)',
    character: 'Juhani',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'The Cathar Jedi Padawan in Revan\'s KOTOR party. Cyan-blue blade reflecting her blue kyber crystal — earned after rejecting the dark side temptation on Dantooine.',
    hiltNotes: 'Slim hilt sized for Cathar grip; integrated crystal-window viewport along the throat.',
    config: {
      name: 'Juhani',
      baseColor: { r: 0, g: 200, b: 240 },
      clashColor: { r: 220, g: 245, b: 255 },
      lockupColor: { r: 130, g: 220, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.45,
    },
  },

  // ── Atris ──
  {
    id: 'legends-atris-blue',
    name: 'Atris (Jedi Historian)',
    character: 'Atris',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'The dogmatic Jedi historian from KOTOR 2 who isolates herself on Telos with the Holocron Vault. A pale Jedi blue, almost grey-blue — the color of someone whose connection to the living Force has gone cold.',
    hiltNotes: 'Long ornate hilt with antique Jedi heraldry; collected from the Vault rather than personally crafted.',
    config: {
      name: 'Atris',
      baseColor: { r: 100, g: 160, b: 240 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 180, g: 210, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'fadeout',
      ignitionMs: 380,
      retractionMs: 440,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // SWTOR / OLD REPUBLIC MMO
  // ═══════════════════════════════════════════════════════════════════

  // ── Satele Shan ──
  {
    id: 'legends-satele-shan-blue',
    name: 'Satele Shan',
    character: 'Satele Shan',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'Grand Master of the Jedi Order during the SWTOR era. Descendant of Bastila Shan and Revan. A clean Jedi blue with a quiet authority — the leader of a Jedi Order that survived the Sith Empire\'s return.',
    hiltNotes: 'A long, elegant hilt of Mandalorian-influenced design — Satele\'s mother trained her with the heritage of the Mandalorian Wars.',
    config: {
      name: 'SateleShan',
      baseColor: { r: 30, g: 130, b: 250 },
      clashColor: { r: 220, g: 240, b: 255 },
      lockupColor: { r: 140, g: 200, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Lana Beniko ──
  {
    id: 'legends-lana-beniko-red',
    name: 'Lana Beniko',
    character: 'Lana Beniko',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'SWTOR Sith Lord, member of the Empire\'s Sith Intelligence and (eventually) ally of the Outlander. A controlled, deep red — Lana favors precision over spectacle. The Sith who would rather negotiate than destroy.',
    hiltNotes: 'Polished gold-and-black Sith hilt; engraved reliefs of Korriban tomb statuary along the throat.',
    config: {
      name: 'LanaBeniko',
      baseColor: { r: 220, g: 5, b: 15 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 80, b: 50 },
      blastColor: { r: 255, g: 100, b: 70 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 340,
      shimmer: 0.14,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Kira Carsen ──
  {
    id: 'legends-kira-carsen-blue',
    name: 'Kira Carsen',
    character: 'Kira Carsen',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'base',
    description:
      'SWTOR Jedi Knight\'s primary companion, secret Child of the Emperor. A bright Jedi blue with quick energetic ignition matching her impulsive Knight-class temperament.',
    hiltNotes: 'Standard SWTOR-era Jedi Knight hilt with Padawan-engraved Pyrian wave crystal.',
    config: {
      name: 'KiraCarsen',
      baseColor: { r: 40, g: 140, b: 250 },
      clashColor: { r: 220, g: 240, b: 255 },
      lockupColor: { r: 150, g: 210, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 320,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.5,
    },
  },

  // ── Darth Marr ──
  {
    id: 'legends-darth-marr-red',
    name: 'Darth Marr',
    character: 'Darth Marr',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Member of the Dark Council in SWTOR, eventual leader of the Sith Empire who unites with the Republic against Vitiate. A heavy, warm crimson — Marr\'s lightsaber carries the weight of millennia of Sith tradition without the volatility of younger Lords.',
    hiltNotes: 'Massive armored hilt of black duranium and tempered red glass; Marr\'s helmet visible reflected in the saber\'s polished crossguard.',
    config: {
      name: 'DarthMarr',
      baseColor: { r: 220, g: 0, b: 10 },
      clashColor: { r: 255, g: 200, b: 160 },
      lockupColor: { r: 255, g: 90, b: 50 },
      blastColor: { r: 255, g: 110, b: 70 },
      dragColor: { r: 255, g: 60, b: 0 },
      style: 'unstable',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 420,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.45,
    },
  },

  // ── Darth Baras ──
  {
    id: 'legends-darth-baras-red',
    name: 'Darth Baras',
    character: 'Darth Baras',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Sith Warrior class storyline antagonist in SWTOR. A heavy, bloodthirsty red — Baras is the manipulator who outlived smarter Sith because he never trusted anyone, including himself.',
    hiltNotes: 'Massive armored hilt with corpulent grip; engraved with Sith heraldry from his stint on the Dark Council.',
    config: {
      name: 'DarthBaras',
      baseColor: { r: 230, g: 5, b: 5 },
      clashColor: { r: 255, g: 220, b: 200 },
      lockupColor: { r: 255, g: 80, b: 50 },
      blastColor: { r: 255, g: 100, b: 70 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 480,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.08,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // BANE TRILOGY (Old Sith Wars era)
  // ═══════════════════════════════════════════════════════════════════

  // ── Darth Zannah ──
  {
    id: 'legends-darth-zannah-red',
    name: 'Darth Zannah',
    character: 'Darth Zannah',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Bane\'s apprentice, the second Sith Lord of the Banite Rule of Two. Wields a double-bladed lightsaber inherited from her early Jedi-Padawan training. A vivid blood-red with the patient instability of a Sith who spent years learning before striking.',
    hiltNotes: 'Saberstaff hilt — rebuilt from a Jedi double-blade design she trained on as a Padawan, repurposed after her fall to the Sith.',
    topologyNotes: 'Double-bladed staff configuration.',
    config: {
      name: 'DarthZannah',
      baseColor: { r: 240, g: 5, b: 10 },
      clashColor: { r: 255, g: 220, b: 200 },
      lockupColor: { r: 255, g: 90, b: 60 },
      blastColor: { r: 255, g: 110, b: 80 },
      style: 'unstable',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 240,
      retractionMs: 300,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.5,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // FORCE UNLEASHED ADDITIONAL
  // ═══════════════════════════════════════════════════════════════════

  // ── Kazdan Paratus (Junk Jedi) ──
  {
    id: 'legends-kazdan-paratus-blue',
    name: 'Kazdan Paratus (Junk Jedi)',
    character: 'Kazdan Paratus',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'The deranged Aleena Jedi Master who rebuilt the Jedi Temple in scrap on Raxus Prime. Battles Starkiller in The Force Unleashed. A bright Jedi blue, but with the uneasy shimmer of someone whose Force connection broke alongside his sanity.',
    hiltNotes: 'A Frankenstein hilt assembled from junkyard parts after Order 66; the original was lost on Coruscant.',
    config: {
      name: 'KazdanParatus',
      baseColor: { r: 30, g: 140, b: 255 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 150, g: 200, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'unstable',
      ignition: 'stutter',
      retraction: 'fadeout',
      ignitionMs: 360,
      retractionMs: 480,
      shimmer: 0.22,
      ledCount: 144,
      swingFxIntensity: 0.45,
      noiseLevel: 0.1,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // JEDI KNIGHT / DARK FORCES GAMES
  // ═══════════════════════════════════════════════════════════════════

  // ── Jerec ──
  {
    id: 'legends-jerec-red',
    name: 'Jerec (Blind Dark Jedi)',
    character: 'Jerec',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'The blind Miraluka Dark Jedi from Jedi Knight: Dark Forces 2. Hunted Kyle Katarn for the Valley of the Jedi\'s power. A volatile crimson blade with frequent flicker — the unsteady gait of a man ruling by ambition rather than wisdom.',
    hiltNotes: 'Imperial Inquisitor-style hilt with a chrome activation collar; Jerec wields it through Force-sight rather than visual aim.',
    config: {
      name: 'Jerec',
      baseColor: { r: 240, g: 5, b: 15 },
      clashColor: { r: 255, g: 210, b: 180 },
      lockupColor: { r: 255, g: 90, b: 60 },
      blastColor: { r: 255, g: 110, b: 80 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 360,
      shimmer: 0.22,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.08,
    },
  },

  // ── Desann ──
  {
    id: 'legends-desann-green',
    name: 'Desann',
    character: 'Desann',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Chistori Reborn warlord from Jedi Outcast — Dark Jedi sentenced for Padawan-killing, escaped Jedi prison, came back with an army. A toxic green blade — corrupted Jedi green now bled through with Sith intent.',
    hiltNotes: 'A salvaged Jedi-era hilt with Reborn-faction modifications; Desann was a Jedi student before his fall.',
    config: {
      name: 'Desann',
      baseColor: { r: 30, g: 230, b: 80 },
      clashColor: { r: 200, g: 255, b: 200 },
      lockupColor: { r: 130, g: 250, b: 130 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 320,
      retractionMs: 400,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.08,
    },
  },

  // ── Tavion Axmis ──
  {
    id: 'legends-tavion-axmis-red',
    name: 'Tavion Axmis',
    character: 'Tavion Axmis',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'base',
    description:
      'Female Reborn-cult Sith from Jedi Academy — apprentice to Desann and later cult leader hunting the Scepter of Ragnos. Crimson red with quick, agile flicker reflecting her duelist combat style.',
    hiltNotes: 'A slender hilt rebuilt during her cult-leader era with Sith-glyph etching.',
    config: {
      name: 'TavionAxmis',
      baseColor: { r: 235, g: 10, b: 15 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 90, b: 60 },
      blastColor: { r: 255, g: 110, b: 80 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 220,
      retractionMs: 300,
      shimmer: 0.16,
      ledCount: 144,
      swingFxIntensity: 0.55,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // ADDITIONAL OLD SITH WARS / NOVELS
  // ═══════════════════════════════════════════════════════════════════

  // ── Darth Tenebrous ──
  {
    id: 'legends-darth-tenebrous-red',
    name: 'Darth Tenebrous',
    character: 'Darth Tenebrous',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Plagueis\'s Master, a Bith Sith Lord from the Plagueis novel. Crimson with the cool, calculated stability of a scientist-Sith — Tenebrous saw the Force as an equation to solve, not a passion to embrace.',
    hiltNotes: 'A precision-engineered hilt of polished durasteel and lab-glass viewport — built more like a scientific instrument than a weapon.',
    config: {
      name: 'DarthTenebrous',
      baseColor: { r: 220, g: 5, b: 5 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 80, b: 50 },
      blastColor: { r: 255, g: 100, b: 60 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 380,
      shimmer: 0.07,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ── Lord Hoth ──
  {
    id: 'legends-lord-hoth-blue',
    name: 'Lord Hoth (Army of Light)',
    character: 'Lord Hoth',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'jedi',
    tier: 'detailed',
    description:
      'General of the Army of Light during the New Sith Wars; the Jedi who defeated Lord Kaan\'s Brotherhood at the Seventh Battle of Ruusan. A deep, commanding Jedi blue — the color of a thousand-year war\'s end.',
    hiltNotes: 'Old-Republic-era Jedi General hilt; ornate quillon-style guards rare for the period.',
    config: {
      name: 'LordHoth',
      baseColor: { r: 0, g: 100, b: 240 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 140, g: 200, b: 250 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'stable',
      ignition: 'wipe',
      retraction: 'standard',
      ignitionMs: 380,
      retractionMs: 440,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════
  // MARVEL COMICS / DARK EMPIRE
  // ═══════════════════════════════════════════════════════════════════

  // ── Lumiya ──
  {
    id: 'legends-lumiya-red-lightwhip',
    name: 'Lumiya (Sith Lightwhip)',
    character: 'Lumiya',
    era: 'expanded-universe',
    continuity: 'legends',
    affiliation: 'sith',
    tier: 'detailed',
    description:
      'Shira Brie / Lumiya, Marvel-era Star Wars comics Sith and Vader\'s secret apprentice. Wields a flexible lightwhip — represented here as a single-blade with high shimmer to evoke the whip\'s coiling motion (true lightwhip topology is post-launch engine work).',
    hiltNotes: 'Sith-Marvel-era hilt with multiple flexible filament emitters; the whip extends and coils on activation.',
    config: {
      name: 'Lumiya',
      baseColor: { r: 230, g: 5, b: 15 },
      clashColor: { r: 255, g: 200, b: 170 },
      lockupColor: { r: 255, g: 80, b: 50 },
      blastColor: { r: 255, g: 100, b: 70 },
      style: 'unstable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 280,
      retractionMs: 360,
      shimmer: 0.3,
      ledCount: 144,
      swingFxIntensity: 0.6,
      noiseLevel: 0.1,
    },
  },
];
