import type { Preset } from '../types.js';

export const PREQUEL_ERA_PRESETS: Preset[] = [
  // ─── Obi-Wan Kenobi (Episode I) ───
  {
    id: 'prequel-obi-wan-ep1',
    name: 'Obi-Wan Kenobi (Padawan)',
    character: 'Obi-Wan Kenobi',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Obi-Wan\'s first lightsaber as a Padawan, wielded during the Battle of Naboo against Darth Maul.',
    hiltNotes: 'Slim cylindrical hilt with ridged grip section and thin neck.',
    config: {
      name: 'ObiWanEp1',
      baseColor: { r: 0, g: 215, b: 32 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 280,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.3,
      swingColorShift: { r: 0, g: 255, b: 60 },
    },
  },

  // ─── Obi-Wan Kenobi (Episodes II-III) ───
  {
    id: 'prequel-obi-wan-ep3',
    name: 'Obi-Wan Kenobi (Master)',
    character: 'Obi-Wan Kenobi',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Obi-Wan\'s third lightsaber, used throughout the Clone Wars and the duel on Mustafar.',
    hiltNotes:
      'Classic Obi-Wan hilt with tapered pommel and black grip ridges. Inspired the ANH hilt.',
    config: {
      name: 'ObiWanEp3',
      baseColor: { r: 0, g: 135, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      dragColor: { r: 255, g: 160, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  // ─── Qui-Gon Jinn ───
  {
    id: 'prequel-qui-gon',
    name: 'Qui-Gon Jinn',
    character: 'Qui-Gon Jinn',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The maverick Jedi Master\'s lightsaber, used in the fateful duel against Darth Maul on Naboo.',
    hiltNotes: 'Simple, utilitarian hilt with ribbed grip and flat pommel.',
    config: {
      name: 'QuiGon',
      baseColor: { r: 0, g: 220, b: 28 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 290,
      retractionMs: 300,
      shimmer: 0.04,
      ledCount: 144,
      swingFxIntensity: 0.25,
      noiseLevel: 0.02,
    },
  },

  // ─── Anakin Skywalker ───
  {
    id: 'prequel-anakin',
    name: 'Anakin Skywalker',
    character: 'Anakin Skywalker',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Anakin\'s second lightsaber, later passed to Luke. The most iconic hilt in Star Wars.',
    hiltNotes:
      'Graflex-style hilt with black grips, red activation button, and D-ring pommel.',
    config: {
      name: 'AnakinEp3',
      baseColor: { r: 0, g: 120, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 255, b: 200 },
      dragColor: { r: 255, g: 150, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.03,
    },
  },

  // ─── Mace Windu ───
  {
    id: 'prequel-mace-windu',
    name: 'Mace Windu',
    character: 'Mace Windu',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The only purple lightsaber of the Jedi Order, reflecting Windu\'s unique Vaapad fighting style.',
    hiltNotes:
      'Electrum-finished hilt signifying Windu\'s rank on the Jedi Council. Gold accents.',
    config: {
      name: 'MaceWindu',
      baseColor: { r: 170, g: 60, b: 240 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 150, b: 255 },
      dragColor: { r: 255, g: 160, b: 50 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 280,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.03,
    },
  },

  // ─── Yoda ───
  {
    id: 'prequel-yoda',
    name: 'Yoda',
    character: 'Yoda',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Grand Master Yoda\'s short-bladed lightsaber, sized for his diminutive form but devastating in combat.',
    hiltNotes: 'Compact shoto-length hilt with rounded pommel and simple design.',
    config: {
      name: 'Yoda',
      baseColor: { r: 50, g: 230, b: 20 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 220,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.55,
    },
  },

  // ─── Count Dooku ───
  {
    id: 'prequel-dooku',
    name: 'Count Dooku',
    character: 'Count Dooku',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The elegant curved-hilt lightsaber of the Sith Lord and former Jedi, optimized for Form II Makashi.',
    hiltNotes:
      'Distinctive curved hilt designed for precise one-handed fencing. Silver and black finish.',
    config: {
      name: 'Dooku',
      baseColor: { r: 255, g: 20, b: 10 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 128, b: 128 },
      dragColor: { r: 255, g: 100, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.04,
      ledCount: 144,
      noiseLevel: 0.02,
    },
  },

  // ─── Darth Maul ───
  {
    id: 'prequel-darth-maul',
    name: 'Darth Maul',
    character: 'Darth Maul',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Darth Maul\'s iconic double-bladed lightsaber, a weapon of terror and acrobatic combat.',
    hiltNotes: 'Long staff hilt with emitters on both ends. Can be split into two single sabers.',
    topologyNotes: 'Double-bladed staff saber. Each blade is 144 LEDs.',
    config: {
      name: 'DarthMaul',
      baseColor: { r: 255, g: 15, b: 5 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 100, b: 100 },
      dragColor: { r: 255, g: 80, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.45,
    },
  },

  // ─── Kit Fisto ───
  {
    id: 'prequel-kit-fisto',
    name: 'Kit Fisto',
    character: 'Kit Fisto',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The Nautolan Jedi Master\'s lightsaber, designed to function underwater on his homeworld.',
    hiltNotes: 'Hilt with dual activation switches and waterproof design.',
    config: {
      name: 'KitFisto',
      baseColor: { r: 0, g: 230, b: 40 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 280,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ─── Plo Koon ───
  {
    id: 'prequel-plo-koon',
    name: 'Plo Koon',
    character: 'Plo Koon',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Jedi Master Plo Koon\'s lightsaber, wielded by the Kel Dor pilot and Council member.',
    hiltNotes: 'Gauntlet-style hilt adapted for his clawed Kel Dor hands.',
    config: {
      name: 'PloKoon',
      baseColor: { r: 0, g: 140, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      dragColor: { r: 255, g: 180, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ─── Aayla Secura ───
  {
    id: 'prequel-aayla-secura',
    name: 'Aayla Secura',
    character: 'Aayla Secura',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Twi\'lek Jedi Knight Aayla Secura\'s lightsaber, carried through the Clone Wars until Order 66.',
    hiltNotes: 'Slim cylindrical hilt with tapered emitter and blue accents.',
    config: {
      name: 'AaylaSecura',
      baseColor: { r: 0, g: 100, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 290,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Luminara Unduli ───
  {
    id: 'prequel-luminara',
    name: 'Luminara Unduli',
    character: 'Luminara Unduli',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Mirialan Jedi Master Luminara Unduli\'s lightsaber, reflecting her disciplined and graceful combat style.',
    hiltNotes: 'Ornate hilt with stepped emitter and decorative grip patterns.',
    config: {
      name: 'Luminara',
      baseColor: { r: 0, g: 225, b: 30 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 310,
      retractionMs: 300,
      shimmer: 0.03,
      ledCount: 144,
    },
  },

  // ─── Barriss Offee ───
  {
    id: 'prequel-barriss-offee',
    name: 'Barriss Offee',
    character: 'Barriss Offee',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Padawan Barriss Offee\'s lightsaber, wielded before her fall to the dark side and betrayal of the Jedi.',
    hiltNotes: 'Slender hilt similar in design to her master Luminara\'s.',
    config: {
      name: 'BarrissOffee',
      baseColor: { r: 0, g: 110, b: 245 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 290,
      retractionMs: 280,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Shaak Ti ───
  {
    id: 'prequel-shaak-ti',
    name: 'Shaak Ti',
    character: 'Shaak Ti',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Togruta Jedi Master Shaak Ti\'s lightsaber, carried during the defense of Kamino and beyond.',
    hiltNotes: 'Curved-neck hilt with flared emitter, designed for her Ataru and Makashi techniques.',
    config: {
      name: 'ShaakTi',
      baseColor: { r: 0, g: 130, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
    },
  },

  // ─── Ki-Adi-Mundi ───
  {
    id: 'prequel-ki-adi-mundi',
    name: 'Ki-Adi-Mundi',
    character: 'Ki-Adi-Mundi',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Cerean Jedi Master Ki-Adi-Mundi\'s lightsaber, carried from Geonosis through the Outer Rim Sieges.',
    hiltNotes: 'Long hilt with stepped emitter and ribbed grip section.',
    config: {
      name: 'KiAdiMundi',
      baseColor: { r: 0, g: 120, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 310,
      retractionMs: 290,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Depa Billaba ───
  {
    id: 'prequel-depa-billaba',
    name: 'Depa Billaba',
    character: 'Depa Billaba',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Jedi Master Depa Billaba\'s lightsaber, later passed to her Padawan Caleb Dume (Kanan Jarrus).',
    hiltNotes: 'Elegant hilt with gold accents, reflecting her position on the Jedi Council.',
    config: {
      name: 'DepaBillaba',
      baseColor: { r: 0, g: 210, b: 35 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 290,
      retractionMs: 300,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Savage Opress ───
  {
    id: 'prequel-savage-opress',
    name: 'Savage Opress',
    character: 'Savage Opress',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The Nightbrother warrior\'s double-bladed lightsaber with a distinctive yellow-green blade.',
    hiltNotes: 'Heavy double-bladed hilt with a brutalist, primitive design.',
    topologyNotes: 'Double-bladed staff saber.',
    config: {
      name: 'SavageOpress',
      baseColor: { r: 210, g: 235, b: 0 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 220, g: 255, b: 150 },
      dragColor: { r: 200, g: 180, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.1,
      ledCount: 144,
      noiseLevel: 0.05,
      swingFxIntensity: 0.3,
    },
  },

  // ─── Asajj Ventress ───
  {
    id: 'prequel-asajj-ventress',
    name: 'Asajj Ventress',
    character: 'Asajj Ventress',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Ventress\'s paired curved-hilt lightsabers that can connect at the pommels to form a double-blade.',
    hiltNotes:
      'Dual curved hilts that clip together at the pommel. Designed for Jar\'Kai dual-wielding.',
    topologyNotes: 'Dual wielded curved hilts, connectable into a staff configuration.',
    config: {
      name: 'Ventress',
      baseColor: { r: 255, g: 0, b: 10 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 100, b: 100 },
      dragColor: { r: 255, g: 120, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 270,
      retractionMs: 280,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ─── General Grievous ───
  {
    id: 'prequel-grievous',
    name: 'General Grievous',
    character: 'General Grievous',
    era: 'prequel',
    affiliation: 'other',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Trophies stolen from defeated Jedi. Grievous wields up to four sabers simultaneously — blue and green blades collected from his victims.',
    hiltNotes:
      'Various stolen Jedi hilts. Most commonly depicted with Anakin-style and generic Jedi hilts.',
    topologyNotes: 'Quad-wielded stolen Jedi lightsabers (2 blue, 2 green).',
    config: {
      name: 'Grievous',
      baseColor: { r: 0, g: 200, b: 40 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 300,
      shimmer: 0.05,
      ledCount: 144,
    },
  },

  // ─── Palpatine / Darth Sidious ───
  {
    id: 'prequel-palpatine',
    name: 'Darth Sidious',
    character: 'Palpatine / Darth Sidious',
    era: 'prequel',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The Sith Lord\'s concealed lightsaber, an elegant Phrik-alloy weapon hidden within the Supreme Chancellor\'s robes.',
    hiltNotes:
      'Compact electrum-finished hilt with ornate aurodium inlays. Designed to be concealed in his sleeve.',
    config: {
      name: 'Sidious',
      baseColor: { r: 255, g: 25, b: 15 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 255, g: 100, b: 100 },
      dragColor: { r: 255, g: 80, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 280,
      shimmer: 0.04,
      ledCount: 144,
      noiseLevel: 0.03,
      swingFxIntensity: 0.25,
    },
  },

  // ─── Anakin Skywalker (Episode II) ───
  {
    id: 'prequel-anakin-ep2',
    name: 'Anakin Skywalker (Ep. II)',
    character: 'Anakin Skywalker',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Anakin\'s first lightsaber, destroyed in the Geonosis droid factory. A youthful, slightly brighter blue than his later saber.',
    hiltNotes: 'Wider, bulkier hilt with visible green and red wiring. Built as a Padawan.',
    config: {
      name: 'AnakinEp2',
      baseColor: { r: 0, g: 140, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 230, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 280,
      shimmer: 0.05,
      ledCount: 144,
    },
  },

  // ─── Agen Kolar ───
  {
    id: 'prequel-agen-kolar',
    name: 'Agen Kolar',
    character: 'Agen Kolar',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Zabrak Jedi Master Agen Kolar\'s blue lightsaber. Accompanied Mace Windu to arrest Palpatine.',
    hiltNotes: 'Standard Jedi Council hilt with ribbed grip.',
    config: {
      name: 'AgenKolar',
      baseColor: { r: 0, g: 110, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 280,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Saesee Tiin ───
  {
    id: 'prequel-saesee-tiin',
    name: 'Saesee Tiin',
    character: 'Saesee Tiin',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'The Iktotchi Jedi Master\'s green lightsaber. An ace pilot and swordsman on the Jedi Council.',
    hiltNotes: 'Rugged hilt design built for aggressive combat.',
    config: {
      name: 'SaeseeTiin',
      baseColor: { r: 0, g: 200, b: 30 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 280,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Eeth Koth ───
  {
    id: 'prequel-eeth-koth',
    name: 'Eeth Koth',
    character: 'Eeth Koth',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Zabrak Jedi Master Eeth Koth\'s green lightsaber. Known for his exceptional resilience and pain tolerance.',
    config: {
      name: 'EethKoth',
      baseColor: { r: 0, g: 210, b: 30 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.04,
      ledCount: 144,
    },
  },

  // ─── Stass Allie ───
  {
    id: 'prequel-stass-allie',
    name: 'Stass Allie',
    character: 'Stass Allie',
    era: 'prequel',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: true,
    author: 'on-screen',
    description:
      'Jedi Master Stass Allie\'s green lightsaber. A healer and Council member killed during Order 66 on Saleucami.',
    config: {
      name: 'StassAllie',
      baseColor: { r: 0, g: 220, b: 35 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 200, b: 0 },
      blastColor: { r: 200, g: 255, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 300,
      shimmer: 0.03,
      ledCount: 144,
    },
  },
];
