import type { BoardProfile } from '../types.js';

// ─── Shared mappings for minimal boards ───

const MINIMAL_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', notes: 'Basic clash flash only' },
  { bladeforgeEffect: 'lockup', boardEffectName: null, notes: 'Lockup not supported' },
  { bladeforgeEffect: 'blast', boardEffectName: null, notes: 'Blast not supported' },
  { bladeforgeEffect: 'drag', boardEffectName: null, notes: 'Drag not supported' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported' },
  { bladeforgeEffect: 'stab', boardEffectName: null, notes: 'Stab not supported' },
  { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported' },
];

const ASTERIA_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', notes: 'Clash flash with color' },
  { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', notes: 'Basic lockup flicker' },
  { bladeforgeEffect: 'blast', boardEffectName: 'blast', notes: 'Basic blast flash' },
  { bladeforgeEffect: 'drag', boardEffectName: null, notes: 'Drag not supported on Asteria' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on Asteria' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on Asteria' },
  { bladeforgeEffect: 'stab', boardEffectName: null, notes: 'Stab not supported on Asteria' },
  { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on Asteria' },
];

const SOLID_ONLY_STYLES: BoardProfile['supportedStyles'] = [
  { bladeforgeStyle: 'stable', boardStyleName: 'solid', notes: 'Solid color — primary mode' },
  { bladeforgeStyle: 'unstable', boardStyleName: 'solid', notes: 'No unstable mode; mapped to solid' },
  { bladeforgeStyle: 'fire', boardStyleName: 'solid', notes: 'No fire effect; mapped to solid' },
  { bladeforgeStyle: 'rotoscope', boardStyleName: 'solid', notes: 'No rotoscope; mapped to solid' },
  { bladeforgeStyle: 'pulse', boardStyleName: 'solid', notes: 'No pulse mode; mapped to solid' },
  { bladeforgeStyle: 'gradient', boardStyleName: 'solid', notes: 'No gradient; mapped to solid' },
  { bladeforgeStyle: 'photon', boardStyleName: 'solid', notes: 'No photon; mapped to solid' },
  { bladeforgeStyle: 'plasma', boardStyleName: 'solid', notes: 'No plasma; mapped to solid' },
  { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'solid', notes: 'No crystal-shatter; mapped to solid' },
  { bladeforgeStyle: 'aurora', boardStyleName: 'solid', notes: 'No aurora; mapped to solid' },
  { bladeforgeStyle: 'cinder', boardStyleName: 'solid', notes: 'No cinder; mapped to solid' },
  { bladeforgeStyle: 'prism', boardStyleName: 'solid', notes: 'No prism; mapped to solid' },
];

const BUDGET_TERMINOLOGY: BoardProfile['terminology'] = {
  'blade style': 'Blade Color',
  clash: 'Clash',
  lockup: 'Lockup',
  preset: 'Color Preset',
  ignition: 'Power On',
  retraction: 'Power Off',
  'sound font': 'Sound Font',
};

const BUDGET_HIDE_ALL: string[] = [
  'layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade',
  'custom-ignition', 'custom-retraction', 'effect-panel', 'timeline-panel',
  'motion-sim-panel', 'code-output',
];

const BUDGET_DISABLE_ALL: string[] = [
  'custom-ignition-code', 'custom-transition-code', 'layer-compositing',
  'audio-reactive', 'motion-reactive', 'effect-customization',
  'code-generation', 'style-customization',
];

// ─── LGT Baselit ───

export const LGT_BASELIT: BoardProfile = {
  id: 'lgt-baselit',
  name: 'LGT Baselit',
  manufacturer: 'LGT',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: false,
    maxLEDs: 1,
    smoothSwing: false,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: false,
    colorProfiles: 12,
    soundFontFormat: 'generic',
    maxPresets: 12,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'fixed-palette',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 0,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: MINIMAL_EFFECTS,
  supportedStyles: SOLID_ONLY_STYLES,
  ledConfig: {
    defaultCount: 1,
    maxCount: 1,
    colorOrders: ['RGB'],
  },
  terminology: BUDGET_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: BUDGET_HIDE_ALL,
    disableFeatures: BUDGET_DISABLE_ALL,
    showWarnings: [
      'LGT Baselit uses in-hilt LEDs, not Neopixel — only color changes are possible.',
      'This board has no neopixel support. Blade effects and animations are not available.',
    ],
  },
};

// ─── Asteria ───

export const ASTERIA: BoardProfile = {
  id: 'asteria',
  name: 'Asteria',
  manufacturer: 'LGT / Darkwolf',
  versions: ['2.5'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 6,
    soundFontFormat: 'generic',
    maxPresets: 6,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'fixed-palette',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: ASTERIA_EFFECTS,
  supportedStyles: SOLID_ONLY_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: BUDGET_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: BUDGET_HIDE_ALL,
    disableFeatures: BUDGET_DISABLE_ALL,
    showWarnings: [
      'Asteria supports basic color and effects only — blade styles are firmware-baked.',
      'Limited to 6 preset profiles. Color selection uses a fixed palette.',
    ],
  },
};

// ─── Darkwolf (Xenopixel variant) ───

export const DARKWOLF: BoardProfile = {
  id: 'darkwolf',
  name: 'Darkwolf Xenopixel',
  manufacturer: 'Darkwolf Sabers',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: false,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 16,
    soundFontFormat: 'generic',
    maxPresets: 16,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'fixed-palette',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: [
    { bladeforgeEffect: 'clash', boardEffectName: 'clash', notes: 'Basic clash flash' },
    { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', notes: 'Basic lockup flicker' },
    { bladeforgeEffect: 'blast', boardEffectName: 'blast', notes: 'Basic blast flash' },
    { bladeforgeEffect: 'drag', boardEffectName: null, notes: 'Drag not supported' },
    { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported' },
    { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported' },
    { bladeforgeEffect: 'stab', boardEffectName: null, notes: 'Stab not supported' },
    { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported' },
  ],
  supportedStyles: SOLID_ONLY_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: {
    ...BUDGET_TERMINOLOGY,
    'blade style': 'Blade Color',
    preset: 'Color Preset',
  },
  uiOverrides: {
    hideFeatures: BUDGET_HIDE_ALL,
    disableFeatures: BUDGET_DISABLE_ALL,
    showWarnings: [
      'Darkwolf uses a Xenopixel-variant board — only color changes are possible.',
      'Effects are firmware-baked and cannot be customized.',
    ],
  },
};

// ─── DamienSaber (CFX-like) ───

const DAMIEN_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', configParam: 'clash_color', notes: 'Clash effect with configurable color' },
  { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', configParam: 'lockup_color', notes: 'Lockup effect with configurable color' },
  { bladeforgeEffect: 'blast', boardEffectName: 'blast', configParam: 'blast_color', notes: 'Blast deflection with configurable color' },
  { bladeforgeEffect: 'drag', boardEffectName: 'drag', configParam: 'drag_color', notes: 'Drag tip effect' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on DamienSaber' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on DamienSaber' },
  { bladeforgeEffect: 'stab', boardEffectName: 'stab', configParam: 'stab_color', notes: 'Basic stab flash' },
  { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on DamienSaber' },
];

const DAMIEN_STYLES: BoardProfile['supportedStyles'] = [
  { bladeforgeStyle: 'stable', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'Solid color blade' },
  { bladeforgeStyle: 'unstable', boardStyleName: 'unstable', configMapping: { style: 'unstable' }, notes: 'Built-in unstable effect' },
  { bladeforgeStyle: 'fire', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Built-in fire effect' },
  { bladeforgeStyle: 'rotoscope', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
  { bladeforgeStyle: 'pulse', boardStyleName: 'pulse', configMapping: { style: 'pulse' }, notes: 'Built-in pulse effect' },
  { bladeforgeStyle: 'gradient', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No gradient; falls back to solid' },
  { bladeforgeStyle: 'photon', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No photon; falls back to solid' },
  { bladeforgeStyle: 'plasma', boardStyleName: 'unstable', configMapping: { style: 'unstable' }, notes: 'Closest match: unstable' },
  { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'strobe', configMapping: { style: 'strobe' }, notes: 'Closest match: strobe' },
  { bladeforgeStyle: 'aurora', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
  { bladeforgeStyle: 'cinder', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Closest match: fire' },
  { bladeforgeStyle: 'prism', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
];

export const DAMIENSABER: BoardProfile = {
  id: 'damiensaber',
  name: 'DamienSaber',
  manufacturer: 'DamienSaber',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: true,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 20,
    soundFontFormat: 'cfx',
    maxPresets: 20,
    tier: 2,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'ini-txt',
  supportedEffects: DAMIEN_EFFECTS,
  supportedStyles: DAMIEN_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB', 'RGB'],
  },
  terminology: {
    'blade style': 'Blade Profile',
    clash: 'Clash',
    lockup: 'Lockup',
    preset: 'Profile',
    ignition: 'Power On',
    retraction: 'Power Off',
    'sound font': 'Sound Bank',
  },
  uiOverrides: {
    hideFeatures: ['layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade'],
    disableFeatures: ['custom-ignition-code', 'custom-transition-code', 'layer-compositing'],
    showWarnings: [
      'DamienSaber uses a CFX-like configuration — custom code generation is not available.',
      'Effect customization is limited to color parameters.',
    ],
  },
};

// ─── Verso ───

const VERSO_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', configParam: 'clash_color', notes: 'Clash with configurable color' },
  { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', configParam: 'lockup_color', notes: 'Basic lockup' },
  { bladeforgeEffect: 'blast', boardEffectName: 'blast', configParam: 'blast_color', notes: 'Basic blast' },
  { bladeforgeEffect: 'drag', boardEffectName: null, notes: 'Drag not supported on Verso' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on Verso' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on Verso' },
  { bladeforgeEffect: 'stab', boardEffectName: null, notes: 'Stab not supported on Verso' },
  { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on Verso' },
];

const VERSO_STYLES: BoardProfile['supportedStyles'] = [
  { bladeforgeStyle: 'stable', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'Solid color blade' },
  { bladeforgeStyle: 'unstable', boardStyleName: 'flicker', configMapping: { style: 'flicker' }, notes: 'Basic flicker effect' },
  { bladeforgeStyle: 'fire', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Basic fire animation' },
  { bladeforgeStyle: 'rotoscope', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No rotoscope; falls back to solid' },
  { bladeforgeStyle: 'pulse', boardStyleName: 'pulse', configMapping: { style: 'pulse' }, notes: 'Basic pulsing effect' },
  { bladeforgeStyle: 'gradient', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No gradient; falls back to solid' },
  { bladeforgeStyle: 'photon', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No photon; falls back to solid' },
  { bladeforgeStyle: 'plasma', boardStyleName: 'flicker', configMapping: { style: 'flicker' }, notes: 'Closest match: flicker' },
  { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No crystal-shatter; falls back to solid' },
  { bladeforgeStyle: 'aurora', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Basic rainbow cycle' },
  { bladeforgeStyle: 'cinder', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Closest match: fire' },
  { bladeforgeStyle: 'prism', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
];

export const VERSO: BoardProfile = {
  id: 'verso',
  name: 'Verso',
  manufacturer: 'Sabertrio',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 20,
    soundFontFormat: 'generic',
    maxPresets: 20,
    tier: 2,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'txt-multifile',
  supportedEffects: VERSO_EFFECTS,
  supportedStyles: VERSO_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: {
    'blade style': 'Blade Effect',
    clash: 'Clash',
    lockup: 'Lockup',
    preset: 'Sound Font',
    ignition: 'Ignition',
    retraction: 'Retraction',
    'sound font': 'Sound Font',
  },
  uiOverrides: {
    hideFeatures: ['layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade', 'code-output'],
    disableFeatures: ['custom-ignition-code', 'custom-transition-code', 'layer-compositing', 'audio-reactive'],
    showWarnings: [
      'Verso has limited style customization — only predefined blade effects are available.',
      'Effect customization is limited to color adjustments.',
    ],
  },
};

// ─── Proffie Lite (genuine Proffie feature set) ───

export const PROFFIE_LITE: BoardProfile = {
  id: 'proffie-lite',
  name: 'Proffie Lite',
  manufacturer: 'Various / Third-party',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 264,
    smoothSwing: true,
    bluetoothConfig: false,
    editMode: true,
    customBladeStyles: true,
    multiBladeSupport: true,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 'unlimited',
    soundFontFormat: 'proffie',
    maxPresets: 'unlimited',
    tier: 1,
    customIgnition: true,
    customRetraction: true,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: true,
    customLightning: true,
    responsiveEffects: true,
    audioReactiveStyles: true,
    motionReactiveStyles: true,
    colorChangeMode: 'full-rgb',
    subBladeSupport: true,
    multiDataPin: true,
    maxDataPins: 2,
    layerCompositing: true,
    transitionCustomization: true,
  },
  configFormat: 'cpp-template',
  supportedEffects: [
    { bladeforgeEffect: 'clash', boardEffectName: 'SimpleClashL', configParam: 'EFFECT_CLASH', notes: 'Full responsive clash' },
    { bladeforgeEffect: 'lockup', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_NORMAL', notes: 'Full responsive lockup' },
    { bladeforgeEffect: 'blast', boardEffectName: 'BlastL', configParam: 'EFFECT_BLAST', notes: 'Randomized blast deflection' },
    { bladeforgeEffect: 'drag', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_DRAG', notes: 'Drag effect' },
    { bladeforgeEffect: 'melt', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_MELT', notes: 'Melt tip effect' },
    { bladeforgeEffect: 'lightning', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_LIGHTNING_BLOCK', notes: 'Lightning block' },
    { bladeforgeEffect: 'stab', boardEffectName: 'StabL', configParam: 'EFFECT_STAB', notes: 'Stab effect' },
    { bladeforgeEffect: 'force', boardEffectName: 'AlphaL', configParam: 'EFFECT_FORCE', notes: 'Force effect' },
  ],
  supportedStyles: [
    { bladeforgeStyle: 'stable', boardStyleName: 'Rgb', configMapping: { template: 'Layers<Rgb<{r},{g},{b}>,...>' }, notes: 'Solid color base' },
    { bladeforgeStyle: 'unstable', boardStyleName: 'AudioFlicker', configMapping: { template: 'AudioFlicker<{color1},{color2}>' }, notes: 'Audio-responsive flickering' },
    { bladeforgeStyle: 'fire', boardStyleName: 'StyleFire', configMapping: { template: 'StyleFire<{color1},{color2},{delay},{sparkle}>' }, notes: 'Animated fire' },
    { bladeforgeStyle: 'rotoscope', boardStyleName: 'Stripes', configMapping: { template: 'Stripes<{width},{speed},{color1},{color2},{color3}>' }, notes: 'Scrolling stripes' },
    { bladeforgeStyle: 'pulse', boardStyleName: 'Pulsing', configMapping: { template: 'Pulsing<{color1},{color2},{period}>' }, notes: 'Smooth pulsing' },
    { bladeforgeStyle: 'gradient', boardStyleName: 'Gradient', configMapping: { template: 'Gradient<{color1},{color2}>' }, notes: 'Static gradient' },
    { bladeforgeStyle: 'photon', boardStyleName: 'Mix', configMapping: { template: 'Mix<{f},{color1},{color2}>' }, notes: 'Custom mix-based photon' },
    { bladeforgeStyle: 'plasma', boardStyleName: 'RandomFlicker', configMapping: { template: 'RandomFlicker<{color1},{color2}>' }, notes: 'Plasma-like flicker' },
    { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'Strobe', configMapping: { template: 'Strobe<{color1},{color2},{frequency},{duration}>' }, notes: 'Shatter strobe' },
    { bladeforgeStyle: 'aurora', boardStyleName: 'Rainbow', configMapping: { template: 'Rainbow' }, notes: 'Full spectrum cycling' },
    { bladeforgeStyle: 'cinder', boardStyleName: 'StyleFire', configMapping: { template: 'StyleFire<{color1},{color2},{delay},{sparkle}>' }, notes: 'Ember variant of fire' },
    { bladeforgeStyle: 'prism', boardStyleName: 'RotateColorsX', configMapping: { template: 'RotateColorsX<Variation,Rainbow>' }, notes: 'Rotating prismatic rainbow' },
  ],
  ledConfig: {
    defaultCount: 144,
    maxCount: 264,
    colorOrders: ['GRB', 'RGB', 'BGR', 'RGBW'],
  },
  terminology: {
    'blade style': 'Blade Style',
    clash: 'Clash',
    lockup: 'Lockup',
    preset: 'Preset',
    ignition: 'Ignition',
    retraction: 'Retraction',
    'sound font': 'Sound Font',
  },
  uiOverrides: {
    hideFeatures: ['oled-preview'],
    disableFeatures: [],
    showWarnings: [
      'Proffie Lite may have reduced data pin count compared to genuine Proffieboard.',
    ],
  },
};

// ─── Proffie Clone (same as genuine Proffie) ───

export const PROFFIE_CLONE: BoardProfile = {
  id: 'proffie-clone',
  name: 'Proffie Clone',
  manufacturer: 'Various / Third-party',
  versions: ['2.2-clone'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 264,
    smoothSwing: true,
    bluetoothConfig: false,
    editMode: true,
    customBladeStyles: true,
    multiBladeSupport: true,
    oledSupport: true,
    gestureControl: true,
    colorProfiles: 'unlimited',
    soundFontFormat: 'proffie',
    maxPresets: 'unlimited',
    tier: 1,
    customIgnition: true,
    customRetraction: true,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: true,
    customLightning: true,
    responsiveEffects: true,
    audioReactiveStyles: true,
    motionReactiveStyles: true,
    colorChangeMode: 'full-rgb',
    subBladeSupport: true,
    multiDataPin: true,
    maxDataPins: 4,
    layerCompositing: true,
    transitionCustomization: true,
  },
  configFormat: 'cpp-template',
  supportedEffects: [
    { bladeforgeEffect: 'clash', boardEffectName: 'SimpleClashL', configParam: 'EFFECT_CLASH', notes: 'Full responsive clash' },
    { bladeforgeEffect: 'lockup', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_NORMAL', notes: 'Full responsive lockup' },
    { bladeforgeEffect: 'blast', boardEffectName: 'BlastL', configParam: 'EFFECT_BLAST', notes: 'Randomized blast deflection' },
    { bladeforgeEffect: 'drag', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_DRAG', notes: 'Drag effect' },
    { bladeforgeEffect: 'melt', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_MELT', notes: 'Melt tip effect' },
    { bladeforgeEffect: 'lightning', boardEffectName: 'LockupTrL', configParam: 'LOCKUP_LIGHTNING_BLOCK', notes: 'Lightning block' },
    { bladeforgeEffect: 'stab', boardEffectName: 'StabL', configParam: 'EFFECT_STAB', notes: 'Stab effect' },
    { bladeforgeEffect: 'force', boardEffectName: 'AlphaL', configParam: 'EFFECT_FORCE', notes: 'Force effect' },
  ],
  supportedStyles: [
    { bladeforgeStyle: 'stable', boardStyleName: 'Rgb', configMapping: { template: 'Layers<Rgb<{r},{g},{b}>,...>' }, notes: 'Solid color base' },
    { bladeforgeStyle: 'unstable', boardStyleName: 'AudioFlicker', configMapping: { template: 'AudioFlicker<{color1},{color2}>' }, notes: 'Audio-responsive flickering' },
    { bladeforgeStyle: 'fire', boardStyleName: 'StyleFire', configMapping: { template: 'StyleFire<{color1},{color2},{delay},{sparkle}>' }, notes: 'Animated fire' },
    { bladeforgeStyle: 'rotoscope', boardStyleName: 'Stripes', configMapping: { template: 'Stripes<{width},{speed},{color1},{color2},{color3}>' }, notes: 'Scrolling stripes' },
    { bladeforgeStyle: 'pulse', boardStyleName: 'Pulsing', configMapping: { template: 'Pulsing<{color1},{color2},{period}>' }, notes: 'Smooth pulsing' },
    { bladeforgeStyle: 'gradient', boardStyleName: 'Gradient', configMapping: { template: 'Gradient<{color1},{color2}>' }, notes: 'Static gradient' },
    { bladeforgeStyle: 'photon', boardStyleName: 'Mix', configMapping: { template: 'Mix<{f},{color1},{color2}>' }, notes: 'Custom mix-based photon' },
    { bladeforgeStyle: 'plasma', boardStyleName: 'RandomFlicker', configMapping: { template: 'RandomFlicker<{color1},{color2}>' }, notes: 'Plasma-like flicker' },
    { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'Strobe', configMapping: { template: 'Strobe<{color1},{color2},{frequency},{duration}>' }, notes: 'Shatter strobe' },
    { bladeforgeStyle: 'aurora', boardStyleName: 'Rainbow', configMapping: { template: 'Rainbow' }, notes: 'Full spectrum cycling' },
    { bladeforgeStyle: 'cinder', boardStyleName: 'StyleFire', configMapping: { template: 'StyleFire<{color1},{color2},{delay},{sparkle}>' }, notes: 'Ember variant of fire' },
    { bladeforgeStyle: 'prism', boardStyleName: 'RotateColorsX', configMapping: { template: 'RotateColorsX<Variation,Rainbow>' }, notes: 'Rotating prismatic rainbow' },
  ],
  ledConfig: {
    defaultCount: 144,
    maxCount: 264,
    colorOrders: ['GRB', 'RGB', 'BGR', 'RGBW'],
  },
  terminology: {
    'blade style': 'Blade Style',
    clash: 'Clash',
    lockup: 'Lockup',
    preset: 'Preset',
    ignition: 'Ignition',
    retraction: 'Retraction',
    'sound font': 'Sound Font',
  },
  uiOverrides: {
    hideFeatures: [],
    disableFeatures: [],
    showWarnings: [
      'Proffie Clone boards may have hardware quality variations — verify pin assignments match your specific clone.',
    ],
  },
};

// ─── SN-Pixel V4 ───

const SNPIXEL_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', notes: 'Clash with color flash' },
  { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', notes: 'Basic lockup flicker' },
  { bladeforgeEffect: 'blast', boardEffectName: 'blast', notes: 'Blast deflection flash' },
  { bladeforgeEffect: 'drag', boardEffectName: 'drag', notes: 'Drag tip effect' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on SN-Pixel' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on SN-Pixel' },
  { bladeforgeEffect: 'stab', boardEffectName: 'stab', notes: 'Basic stab flash' },
  { bladeforgeEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on SN-Pixel' },
];

const SNPIXEL_STYLES: BoardProfile['supportedStyles'] = [
  { bladeforgeStyle: 'stable', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'Solid color blade' },
  { bladeforgeStyle: 'unstable', boardStyleName: 'unstable', configMapping: { style: 'unstable' }, notes: 'Built-in unstable flicker' },
  { bladeforgeStyle: 'fire', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Built-in fire animation' },
  { bladeforgeStyle: 'rotoscope', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
  { bladeforgeStyle: 'pulse', boardStyleName: 'pulse', configMapping: { style: 'pulse' }, notes: 'Built-in pulsing effect' },
  { bladeforgeStyle: 'gradient', boardStyleName: 'gradient', configMapping: { style: 'gradient' }, notes: 'Basic two-color gradient' },
  { bladeforgeStyle: 'photon', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No photon; falls back to solid' },
  { bladeforgeStyle: 'plasma', boardStyleName: 'unstable', configMapping: { style: 'unstable' }, notes: 'Closest match: unstable' },
  { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'strobe', configMapping: { style: 'strobe' }, notes: 'Closest match: strobe' },
  { bladeforgeStyle: 'aurora', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Rainbow cycle' },
  { bladeforgeStyle: 'cinder', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Closest match: fire' },
  { bladeforgeStyle: 'prism', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow' },
];

export const SNPIXEL_V4: BoardProfile = {
  id: 'snpixel-v4',
  name: 'SN-Pixel V4',
  manufacturer: 'LGT / SN',
  versions: ['4.0', '4.0 Pro'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: true,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 16,
    soundFontFormat: 'generic',
    maxPresets: 16,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: SNPIXEL_EFFECTS,
  supportedStyles: SNPIXEL_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: {
    ...BUDGET_TERMINOLOGY,
    preset: 'Color Profile',
  },
  uiOverrides: {
    hideFeatures: BUDGET_HIDE_ALL,
    disableFeatures: BUDGET_DISABLE_ALL,
    showWarnings: [
      'SN-Pixel V4 supports Bluetooth app configuration (ForcePark/SN App).',
      'Blade effects are firmware-built-in — custom code generation is not available.',
    ],
  },
};

// ─── S-RGB (Budget Baselit) ───

export const S_RGB: BoardProfile = {
  id: 's-rgb',
  name: 'S-RGB',
  manufacturer: 'Various / Budget',
  versions: ['1.0'],
  capabilities: {
    neopixelSupport: false,
    maxLEDs: 1,
    smoothSwing: false,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: false,
    colorProfiles: 6,
    soundFontFormat: 'generic',
    maxPresets: 6,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'fixed-palette',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 0,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: MINIMAL_EFFECTS,
  supportedStyles: SOLID_ONLY_STYLES,
  ledConfig: {
    defaultCount: 1,
    maxCount: 1,
    colorOrders: ['RGB'],
  },
  terminology: BUDGET_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: BUDGET_HIDE_ALL,
    disableFeatures: BUDGET_DISABLE_ALL,
    showWarnings: [
      'S-RGB is a basic baselit board with in-hilt LEDs — no neopixel support.',
      'Only fixed color presets are available. No custom effects or animations.',
    ],
  },
};
