import type { BoardProfile } from '../types.js';

const CFX_EFFECTS: BoardProfile['supportedEffects'] = [
  { bladeforgeEffect: 'clash', boardEffectName: 'clash', configParam: 'clash_profile', notes: 'Clash effect via clash profile parameters in config.txt' },
  { bladeforgeEffect: 'lockup', boardEffectName: 'lockup', configParam: 'lockup_profile', notes: 'Lockup effect with configurable color and intensity' },
  { bladeforgeEffect: 'blast', boardEffectName: 'blaster', configParam: 'blaster_profile', notes: 'Blast deflection via blaster profile in config.txt' },
  { bladeforgeEffect: 'drag', boardEffectName: 'drag', configParam: 'drag_profile', notes: 'Drag effect via drag profile parameters' },
  { bladeforgeEffect: 'melt', boardEffectName: null, notes: 'Melt effect not natively supported on CFX' },
  { bladeforgeEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not natively supported on CFX' },
  { bladeforgeEffect: 'stab', boardEffectName: 'stab', configParam: 'stab_profile', notes: 'Basic stab effect via config parameter' },
  { bladeforgeEffect: 'force', boardEffectName: 'force', configParam: 'force_profile', notes: 'Force push effect via force profile' },
];

const CFX_STYLES: BoardProfile['supportedStyles'] = [
  { bladeforgeStyle: 'stable', boardStyleName: 'static', configMapping: { effect: 'static' }, notes: 'Solid color blade' },
  { bladeforgeStyle: 'unstable', boardStyleName: 'unstable', configMapping: { effect: 'unstable' }, notes: 'CFX built-in unstable flicker' },
  { bladeforgeStyle: 'fire', boardStyleName: 'fire', configMapping: { effect: 'fire' }, notes: 'CFX built-in fire effect' },
  { bladeforgeStyle: 'rotoscope', boardStyleName: 'rainbow', configMapping: { effect: 'rainbow' }, notes: 'Closest match: rainbow scrolling effect' },
  { bladeforgeStyle: 'pulse', boardStyleName: 'pulse', configMapping: { effect: 'pulse' }, notes: 'CFX built-in pulsing effect' },
  { bladeforgeStyle: 'gradient', boardStyleName: 'gradient', configMapping: { effect: 'gradient' }, notes: 'CFX gradient between two colors' },
  { bladeforgeStyle: 'photon', boardStyleName: 'static', configMapping: { effect: 'static' }, notes: 'No direct match; falls back to static' },
  { bladeforgeStyle: 'plasma', boardStyleName: 'unstable', configMapping: { effect: 'unstable' }, notes: 'Closest match: unstable flicker' },
  { bladeforgeStyle: 'crystal-shatter', boardStyleName: 'strobe', configMapping: { effect: 'strobe' }, notes: 'Closest match: strobe effect' },
  { bladeforgeStyle: 'aurora', boardStyleName: 'rainbow', configMapping: { effect: 'rainbow' }, notes: 'Closest match: rainbow cycle' },
  { bladeforgeStyle: 'cinder', boardStyleName: 'fire', configMapping: { effect: 'fire' }, notes: 'Closest match: fire effect' },
  { bladeforgeStyle: 'prism', boardStyleName: 'rainbow', configMapping: { effect: 'rainbow' }, notes: 'Closest match: rainbow cycle' },
];

export const CFX_PROFILE: BoardProfile = {
  id: 'cfx',
  name: 'Crystal Focus X (CFX)',
  manufacturer: 'Plecter Labs',
  versions: ['10', '10.5'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: true,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: true,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 32,
    soundFontFormat: 'cfx',
    maxPresets: 32,
    tier: 2,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'ini-txt',
  supportedEffects: CFX_EFFECTS,
  supportedStyles: CFX_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB', 'RGB'],
  },
  terminology: {
    'blade style': 'Blade Profile',
    clash: 'Clash',
    lockup: 'Lockup',
    preset: 'Profile',
    ignition: 'Power On',
    retraction: 'Power Off',
    'sound font': 'Sound Bank',
  },
  uiOverrides: {
    hideFeatures: ['layer-compositor', 'oled-preview', 'edit-mode'],
    disableFeatures: ['custom-ignition-code', 'custom-transition-code', 'layer-compositing'],
    showWarnings: [
      'CFX uses predefined blade effects — custom layer compositing is not available.',
      'Ignition and retraction types are limited to CFX built-in animations.',
    ],
  },
};
