import type { BoardProfile } from '../types.js';

const GH_EFFECTS_V3: BoardProfile['supportedEffects'] = [
  { kyberstationEffect: 'clash', boardEffectName: 'clash', configParam: 'clash_color', notes: 'Clash flash with configurable color' },
  { kyberstationEffect: 'lockup', boardEffectName: 'lockup', configParam: 'lockup_color', notes: 'Lockup with configurable color and flicker' },
  { kyberstationEffect: 'blast', boardEffectName: 'blast', configParam: 'blast_color', notes: 'Blast deflection with configurable color' },
  { kyberstationEffect: 'drag', boardEffectName: 'drag', configParam: 'drag_color', notes: 'Drag effect with tip color override' },
  { kyberstationEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on GHv3' },
  { kyberstationEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on GHv3' },
  { kyberstationEffect: 'stab', boardEffectName: 'stab', configParam: 'stab_color', notes: 'Basic stab flash effect' },
  { kyberstationEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on GHv3' },
];

const GH_EFFECTS_V4: BoardProfile['supportedEffects'] = [
  { kyberstationEffect: 'clash', boardEffectName: 'clash', configParam: 'clash', notes: 'Clash with configurable color and intensity' },
  { kyberstationEffect: 'lockup', boardEffectName: 'lockup', configParam: 'lockup', notes: 'Lockup with configurable color and pattern' },
  { kyberstationEffect: 'blast', boardEffectName: 'blast', configParam: 'blast', notes: 'Blast deflection effect' },
  { kyberstationEffect: 'drag', boardEffectName: 'drag', configParam: 'drag', notes: 'Drag tip effect' },
  { kyberstationEffect: 'melt', boardEffectName: 'melt', configParam: 'melt', notes: 'Basic melt effect on GHv4' },
  { kyberstationEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on GHv4' },
  { kyberstationEffect: 'stab', boardEffectName: 'stab', configParam: 'stab', notes: 'Stab flash effect' },
  { kyberstationEffect: 'force', boardEffectName: 'force', configParam: 'force', notes: 'Basic force push color change' },
];

const GH_STYLES: BoardProfile['supportedStyles'] = [
  { kyberstationStyle: 'stable', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'Solid color blade' },
  { kyberstationStyle: 'unstable', boardStyleName: 'flicker', configMapping: { style: 'flicker' }, notes: 'GH flicker mode for unstable effect' },
  { kyberstationStyle: 'fire', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'GH built-in fire animation' },
  { kyberstationStyle: 'rotoscope', boardStyleName: 'scroll', configMapping: { style: 'scroll' }, notes: 'Scrolling color pattern' },
  { kyberstationStyle: 'pulse', boardStyleName: 'pulse', configMapping: { style: 'pulse' }, notes: 'Pulsing brightness effect' },
  { kyberstationStyle: 'gradient', boardStyleName: 'gradient', configMapping: { style: 'gradient' }, notes: 'Two-color gradient' },
  { kyberstationStyle: 'photon', boardStyleName: 'solid', configMapping: { style: 'solid' }, notes: 'No direct match; falls back to solid' },
  { kyberstationStyle: 'plasma', boardStyleName: 'flicker', configMapping: { style: 'flicker' }, notes: 'Closest match: flicker mode' },
  { kyberstationStyle: 'crystal-shatter', boardStyleName: 'strobe', configMapping: { style: 'strobe' }, notes: 'Closest match: strobe mode' },
  { kyberstationStyle: 'aurora', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Rainbow color cycling' },
  { kyberstationStyle: 'cinder', boardStyleName: 'fire', configMapping: { style: 'fire' }, notes: 'Closest match: fire animation' },
  { kyberstationStyle: 'prism', boardStyleName: 'rainbow', configMapping: { style: 'rainbow' }, notes: 'Closest match: rainbow cycle' },
];

const GH_TERMINOLOGY: BoardProfile['terminology'] = {
  'blade style': 'Effect Font',
  clash: 'Clash',
  lockup: 'Lockup',
  preset: 'Sound Font Slot',
  ignition: 'Ignition',
  retraction: 'Retraction',
  'sound font': 'Sound Font',
};

export const GHV3_PROFILE: BoardProfile = {
  id: 'ghv3',
  name: 'Golden Harvest V3',
  manufacturer: 'Sabertrio / Golden Harvest',
  versions: ['3.0', '3.1'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 16,
    soundFontFormat: 'ghv3',
    maxPresets: 16,
    tier: 2,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'txt-multifile',
  supportedEffects: GH_EFFECTS_V3,
  supportedStyles: GH_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB', 'RGB'],
  },
  terminology: GH_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: ['layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade'],
    disableFeatures: ['custom-ignition-code', 'custom-transition-code', 'layer-compositing', 'audio-reactive'],
    showWarnings: [
      'Golden Harvest V3 uses its own style system — custom layer compositing is not available.',
      'Effect customization is limited to color and parameter adjustments.',
    ],
  },
};

export const GHV4_PROFILE: BoardProfile = {
  id: 'ghv4',
  name: 'Golden Harvest V4',
  manufacturer: 'Sabertrio / Golden Harvest',
  versions: ['4.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: true,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: true,
    oledSupport: true,
    gestureControl: true,
    colorProfiles: 32,
    soundFontFormat: 'ghv3',
    maxPresets: 32,
    tier: 2,
    customIgnition: false,
    customRetraction: false,
    customClash: true,
    customLockup: true,
    customBlast: true,
    customDrag: true,
    customMelt: true,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: true,
    motionReactiveStyles: true,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'json',
  supportedEffects: GH_EFFECTS_V4,
  supportedStyles: GH_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB', 'RGB'],
  },
  terminology: GH_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: ['layer-compositor', 'sub-blade'],
    disableFeatures: ['custom-ignition-code', 'custom-transition-code', 'layer-compositing'],
    showWarnings: [
      'Golden Harvest V4 uses JSON-based configuration — custom code generation is not available.',
      'Effect customization is limited to color and parameter adjustments.',
    ],
  },
};
