import type { BoardProfile } from '../types.js';

const XENOPIXEL_EFFECTS_V2: BoardProfile['supportedEffects'] = [
  { kyberstationEffect: 'clash', boardEffectName: 'clash', notes: 'Basic clash flash, color not customizable' },
  { kyberstationEffect: 'lockup', boardEffectName: 'lockup', notes: 'Basic lockup flicker, firmware-defined' },
  { kyberstationEffect: 'blast', boardEffectName: 'blast', notes: 'Basic blast flash, firmware-defined' },
  { kyberstationEffect: 'drag', boardEffectName: null, notes: 'Drag not supported on Xenopixel V2' },
  { kyberstationEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on Xenopixel V2' },
  { kyberstationEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on Xenopixel V2' },
  { kyberstationEffect: 'stab', boardEffectName: null, notes: 'Stab not supported on Xenopixel V2' },
  { kyberstationEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on Xenopixel V2' },
];

const XENOPIXEL_EFFECTS_V3: BoardProfile['supportedEffects'] = [
  { kyberstationEffect: 'clash', boardEffectName: 'clash', notes: 'Clash flash with improved animation' },
  { kyberstationEffect: 'lockup', boardEffectName: 'lockup', notes: 'Lockup flicker effect' },
  { kyberstationEffect: 'blast', boardEffectName: 'blast', notes: 'Blast deflection flash' },
  { kyberstationEffect: 'drag', boardEffectName: 'drag', notes: 'Basic drag effect on V3' },
  { kyberstationEffect: 'melt', boardEffectName: null, notes: 'Melt not supported on Xenopixel V3' },
  { kyberstationEffect: 'lightning', boardEffectName: null, notes: 'Lightning block not supported on Xenopixel V3' },
  { kyberstationEffect: 'stab', boardEffectName: 'stab', notes: 'Basic stab effect on V3' },
  { kyberstationEffect: 'force', boardEffectName: null, notes: 'Force effect not supported on Xenopixel V3' },
];

const XENOPIXEL_STYLES: BoardProfile['supportedStyles'] = [
  { kyberstationStyle: 'stable', boardStyleName: 'solid', notes: 'Solid blade color — primary Xenopixel mode' },
  { kyberstationStyle: 'unstable', boardStyleName: 'solid', notes: 'Xenopixel has no unstable mode; mapped to solid color' },
  { kyberstationStyle: 'fire', boardStyleName: 'solid', notes: 'No fire effect; mapped to solid color' },
  { kyberstationStyle: 'rotoscope', boardStyleName: 'solid', notes: 'No rotoscope; mapped to solid color' },
  { kyberstationStyle: 'pulse', boardStyleName: 'solid', notes: 'No pulse mode; mapped to solid color' },
  { kyberstationStyle: 'gradient', boardStyleName: 'solid', notes: 'No gradient; mapped to solid color' },
  { kyberstationStyle: 'photon', boardStyleName: 'solid', notes: 'No photon effect; mapped to solid color' },
  { kyberstationStyle: 'plasma', boardStyleName: 'solid', notes: 'No plasma effect; mapped to solid color' },
  { kyberstationStyle: 'crystal-shatter', boardStyleName: 'solid', notes: 'No crystal-shatter; mapped to solid color' },
  { kyberstationStyle: 'aurora', boardStyleName: 'solid', notes: 'No aurora; mapped to solid color' },
  { kyberstationStyle: 'cinder', boardStyleName: 'solid', notes: 'No cinder; mapped to solid color' },
  { kyberstationStyle: 'prism', boardStyleName: 'solid', notes: 'No prism; mapped to solid color' },
];

const XENOPIXEL_TERMINOLOGY: BoardProfile['terminology'] = {
  'blade style': 'Blade Color',
  clash: 'Clash',
  lockup: 'Lockup',
  preset: 'Color Preset',
  ignition: 'Power On',
  retraction: 'Power Off',
  'sound font': 'Sound Font',
};

export const XENOPIXEL_V2: BoardProfile = {
  id: 'xenopixel-v2',
  name: 'Xenopixel V2',
  manufacturer: 'LGT / Generic',
  versions: ['2.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: false,
    bluetoothConfig: false,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 16,
    soundFontFormat: 'generic',
    maxPresets: 16,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'fixed-palette',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: XENOPIXEL_EFFECTS_V2,
  supportedStyles: XENOPIXEL_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: XENOPIXEL_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: [
      'layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade',
      'custom-ignition', 'custom-retraction', 'effect-panel', 'timeline-panel',
    ],
    disableFeatures: [
      'custom-ignition-code', 'custom-transition-code', 'layer-compositing',
      'audio-reactive', 'motion-reactive', 'effect-customization',
    ],
    showWarnings: [
      'Xenopixel V2 supports color changes only — all blade styles appear as solid colors.',
      'Effects are firmware-baked and cannot be customized.',
      'Color changes are limited to a fixed palette of preset colors.',
    ],
  },
};

export const XENOPIXEL_V3: BoardProfile = {
  id: 'xenopixel-v3',
  name: 'Xenopixel V3',
  manufacturer: 'LGT / Generic',
  versions: ['3.0'],
  capabilities: {
    neopixelSupport: true,
    maxLEDs: 144,
    smoothSwing: true,
    bluetoothConfig: true,
    editMode: false,
    customBladeStyles: false,
    multiBladeSupport: false,
    oledSupport: false,
    gestureControl: true,
    colorProfiles: 16,
    soundFontFormat: 'generic',
    maxPresets: 16,
    tier: 3,
    customIgnition: false,
    customRetraction: false,
    customClash: false,
    customLockup: false,
    customBlast: false,
    customDrag: false,
    customMelt: false,
    customLightning: false,
    responsiveEffects: false,
    audioReactiveStyles: false,
    motionReactiveStyles: false,
    colorChangeMode: 'color-wheel',
    subBladeSupport: false,
    multiDataPin: false,
    maxDataPins: 1,
    layerCompositing: false,
    transitionCustomization: false,
  },
  configFormat: 'none',
  supportedEffects: XENOPIXEL_EFFECTS_V3,
  supportedStyles: XENOPIXEL_STYLES,
  ledConfig: {
    defaultCount: 144,
    maxCount: 144,
    colorOrders: ['GRB'],
  },
  terminology: XENOPIXEL_TERMINOLOGY,
  uiOverrides: {
    hideFeatures: [
      'layer-compositor', 'oled-preview', 'edit-mode', 'sub-blade',
      'custom-ignition', 'custom-retraction', 'timeline-panel',
    ],
    disableFeatures: [
      'custom-ignition-code', 'custom-transition-code', 'layer-compositing',
      'audio-reactive', 'motion-reactive', 'effect-customization',
    ],
    showWarnings: [
      'Xenopixel V3 supports color changes only — all blade styles appear as solid colors.',
      'Effects are firmware-baked and cannot be customized.',
      'Color selection uses a color wheel for full RGB choice.',
    ],
  },
};
