# These are supported funding model platforms
# Uncomment and fill in the ones you want to enable

# github: kenkoller
# ko_fi: # your Ko-fi username
# buy_me_a_coffee: # your BMC username
# custom: ['https://your-link.com']
