// ─── CFX Board Emitter ───
// Generates Plecter Labs CFX config files (.txt profile format).
// CFX uses INI-style text files with key=value pairs for each preset.

import type { StyleNode } from '../types.js';
import type { BoardEmitter, BoardEmitOptions, EmitterOutput } from './BaseEmitter.js';

// CFX color format: 0-255 per channel, semicolon separated
function cfxColor(c: { r: number; g: number; b: number }): string {
  return `${c.r};${c.g};${c.b}`;
}

// Map KyberStation ignition types to CFX ignition IDs
function cfxIgnition(ignition: string): number {
  switch (ignition) {
    case 'standard': return 0;  // Standard scroll
    case 'scroll': return 0;
    case 'spark': return 2;     // Spark tip
    case 'center': return 3;    // Center out
    case 'wipe': return 1;      // Wipe
    case 'stutter': return 4;   // Stutter
    case 'glitch': return 5;    // Ghost
    default: return 0;
  }
}

// Map KyberStation retraction types to CFX retraction IDs
function cfxRetraction(retraction: string): number {
  switch (retraction) {
    case 'standard': return 0;
    case 'scroll': return 0;
    case 'fadeout': return 1;   // Fade
    case 'center': return 2;    // Center in
    case 'shatter': return 3;   // Shatter
    default: return 0;
  }
}

// Map KyberStation style to CFX blade style
function cfxBladeStyle(style: string): string {
  switch (style) {
    case 'stable': return 'stable';
    case 'unstable': return 'unstable';
    case 'fire': return 'fire';
    case 'pulse': return 'pulse';
    case 'rotoscope': return 'stable';  // Degraded
    case 'gradient': return 'gradient';
    case 'photon': return 'rainbow';    // Closest match
    case 'plasma': return 'fire';       // Degraded
    case 'crystalShatter': return 'unstable'; // Degraded
    case 'aurora': return 'rainbow';
    case 'cinder': return 'fire';       // Degraded
    case 'prism': return 'rainbow';
    default: return 'stable';
  }
}

function buildPresetBlock(options: BoardEmitOptions, presetIndex: number): string {
  const lines: string[] = [];
  const p = presetIndex;

  lines.push(`[profile${p}]`);
  lines.push(`name=${options.presetName}`);
  lines.push(`font=${options.fontName}`);
  lines.push(`track=tracks/track.wav`);
  lines.push(`color=${cfxColor(options.baseColor)}`);
  lines.push(`clashcolor=${cfxColor(options.clashColor)}`);

  if (options.lockupColor) {
    lines.push(`lockupcolor=${cfxColor(options.lockupColor)}`);
  }
  if (options.blastColor) {
    lines.push(`blastcolor=${cfxColor(options.blastColor)}`);
  }

  lines.push(`bladestyle=${cfxBladeStyle(options.style)}`);
  lines.push(`ignitiontype=${cfxIgnition(options.ignition)}`);
  lines.push(`retractiontype=${cfxRetraction(options.retraction)}`);
  lines.push(`ignitiontime=${options.ignitionMs}`);
  lines.push(`retractiontime=${options.retractionMs}`);
  lines.push(`ledcount=${options.ledCount}`);

  if (options.volume !== undefined) {
    lines.push(`volume=${options.volume}`);
  }

  lines.push(''); // Blank line between profiles
  return lines.join('\n');
}

export class CFXEmitter implements BoardEmitter {
  readonly boardId = 'cfx';
  readonly boardName = 'Plecter Labs CFX';
  readonly formatDescription = 'CFX profile .txt files with key=value configuration';

  emit(ast: StyleNode, options: BoardEmitOptions): EmitterOutput {
    return this.emitMultiPreset([{ ast, options }]);
  }

  emitMultiPreset(presets: Array<{ ast: StyleNode; options: BoardEmitOptions }>): EmitterOutput {
    const lines: string[] = [];
    const notes: string[] = [];

    lines.push('# CFX Configuration');
    lines.push(`# Generated by KyberStation`);
    lines.push(`# ${presets.length} preset(s)`);
    lines.push('');

    // General config
    lines.push('[general]');
    lines.push(`numprofiles=${presets.length}`);
    lines.push(`smoothswing=1`);
    lines.push(`smoothswingstrength=100`);
    lines.push('');

    for (let i = 0; i < presets.length; i++) {
      const { options } = presets[i];
      lines.push(buildPresetBlock(options, i + 1));

      // Note any degradations
      const style = options.style;
      if (['rotoscope', 'plasma', 'crystalShatter', 'cinder'].includes(style)) {
        notes.push(`Preset "${options.presetName}": Style "${style}" degraded to closest CFX equivalent.`);
      }
    }

    return {
      configContent: lines.join('\n'),
      configFileName: 'config.txt',
      notes,
    };
  }
}
