// ─── Golden Harvest V3/V4 Emitter ───
// Generates GHv3 config files (INI-style .txt with sections).
// Golden Harvest uses a different parameter naming convention from CFX.

import type { StyleNode } from '../types.js';
import type { BoardEmitter, BoardEmitOptions, EmitterOutput } from './BaseEmitter.js';

function ghColor(c: { r: number; g: number; b: number }): string {
  // GH uses hex color format
  return `#${c.r.toString(16).padStart(2, '0')}${c.g.toString(16).padStart(2, '0')}${c.b.toString(16).padStart(2, '0')}`;
}

function ghBladeEffect(style: string): string {
  switch (style) {
    case 'stable': return 'Static';
    case 'unstable': return 'Unstable';
    case 'fire': return 'Fire';
    case 'pulse': return 'Pulse';
    case 'rotoscope': return 'Static';  // Degraded
    case 'gradient': return 'Gradient';
    case 'photon': return 'Rainbow';
    case 'plasma': return 'Fire';       // Degraded
    case 'crystalShatter': return 'Unstable';
    case 'aurora': return 'Rainbow';
    case 'cinder': return 'Fire';
    case 'prism': return 'Rainbow';
    default: return 'Static';
  }
}

function ghIgnition(ignition: string): string {
  switch (ignition) {
    case 'standard': return 'ScrollUp';
    case 'scroll': return 'ScrollUp';
    case 'spark': return 'SparkTip';
    case 'center': return 'CenterOut';
    case 'wipe': return 'Wipe';
    case 'stutter': return 'Stutter';
    case 'glitch': return 'Ghost';
    default: return 'ScrollUp';
  }
}

function ghRetraction(retraction: string): string {
  switch (retraction) {
    case 'standard': return 'ScrollDown';
    case 'scroll': return 'ScrollDown';
    case 'fadeout': return 'Fade';
    case 'center': return 'CenterIn';
    case 'shatter': return 'Shatter';
    default: return 'ScrollDown';
  }
}

export class GHv3Emitter implements BoardEmitter {
  readonly boardId = 'ghv3';
  readonly boardName = 'Golden Harvest V3/V4';
  readonly formatDescription = 'Golden Harvest INI-style config files';

  emit(ast: StyleNode, options: BoardEmitOptions): EmitterOutput {
    return this.emitMultiPreset([{ ast, options }]);
  }

  emitMultiPreset(presets: Array<{ ast: StyleNode; options: BoardEmitOptions }>): EmitterOutput {
    const lines: string[] = [];
    const notes: string[] = [];

    lines.push('# Golden Harvest Configuration');
    lines.push(`# Generated by BladeForge`);
    lines.push('');

    // Global settings
    lines.push('[Global]');
    lines.push('SmoothSwing=1');
    lines.push(`NumPresets=${presets.length}`);
    lines.push('');

    for (let i = 0; i < presets.length; i++) {
      const { options } = presets[i];

      lines.push(`[Preset${i + 1}]`);
      lines.push(`Name=${options.presetName}`);
      lines.push(`SoundFont=${options.fontName}`);
      lines.push(`BladeColor=${ghColor(options.baseColor)}`);
      lines.push(`ClashColor=${ghColor(options.clashColor)}`);

      if (options.lockupColor) {
        lines.push(`LockupColor=${ghColor(options.lockupColor)}`);
      }
      if (options.blastColor) {
        lines.push(`BlastColor=${ghColor(options.blastColor)}`);
      }

      lines.push(`BladeEffect=${ghBladeEffect(options.style)}`);
      lines.push(`Ignition=${ghIgnition(options.ignition)}`);
      lines.push(`Retraction=${ghRetraction(options.retraction)}`);
      lines.push(`IgnitionTime=${options.ignitionMs}`);
      lines.push(`RetractionTime=${options.retractionMs}`);
      lines.push(`LEDCount=${options.ledCount}`);
      lines.push('');

      const style = options.style;
      if (['rotoscope', 'plasma', 'crystalShatter', 'cinder'].includes(style)) {
        notes.push(`Preset "${options.presetName}": Style "${style}" degraded to closest GH equivalent.`);
      }
    }

    return {
      configContent: lines.join('\n'),
      configFileName: 'config.ini',
      notes,
    };
  }
}
