import JSZip from 'jszip';
import type { BladeConfig } from '@bladeforge/engine';
import { generateStyleCode } from '@bladeforge/codegen';
import { buildConfigFile } from '@bladeforge/codegen';
import type { ConfigOptions, PresetEntry } from '@bladeforge/codegen';

// ─── Board Identifiers ───

export type BoardId = 'proffie' | 'cfx' | 'golden_harvest' | 'xenopixel';

export interface BoardInfo {
  id: BoardId;
  label: string;
  configFileName: string;
}

export const BOARDS: Record<BoardId, BoardInfo> = {
  proffie: { id: 'proffie', label: 'ProffieOS', configFileName: 'config.h' },
  cfx: { id: 'cfx', label: 'CFX', configFileName: 'config.txt' },
  golden_harvest: { id: 'golden_harvest', label: 'Golden Harvest', configFileName: 'config.ini' },
  xenopixel: { id: 'xenopixel', label: 'Xenopixel', configFileName: 'config.json' },
};

// ─── Preset Export Shape ───

export interface ExportPreset {
  name: string;
  config: BladeConfig;
  fontName?: string;
  soundFiles?: File[];
}

export interface ExportOptions {
  preset: ExportPreset;
  boardId: BoardId;
  boardOptions?: ConfigOptions;
}

export interface MultiExportOptions {
  presets: ExportPreset[];
  boardId: BoardId;
  boardOptions?: ConfigOptions;
}

// ─── Helpers ───

function sanitizeFolderName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
}

function rgbToCfxHex(r: number, g: number, b: number): string {
  return [r, g, b]
    .map((c) => Math.max(0, Math.min(255, c)).toString(16).padStart(2, '0'))
    .join('');
}

// ─── ProffieOS Config Generator ───

function generateProffieConfig(presets: ExportPreset[], boardOptions?: ConfigOptions): string {
  if (boardOptions) {
    return buildConfigFile(boardOptions);
  }

  // Build a minimal config.h from presets
  const presetEntries: PresetEntry[] = presets.map((p, i) => ({
    fontName: p.fontName ?? `font${i + 1}`,
    styleCodes: [generateStyleCode(p.config, { comments: false })],
    presetName: p.name,
  }));

  const options: ConfigOptions = {
    boardType: 'proffieboard_v3',
    propFile: 'saber_fett263_buttons.h',
    numBlades: 1,
    numButtons: 2,
    volume: 2000,
    clashThresholdG: 3.0,
    maxClashStrength: 16,
    fett263Defines: [
      'FETT263_EDIT_MODE_MENU',
      'FETT263_MULTI_PHASE',
    ],
    presets: presetEntries,
    bladeConfig: [
      {
        type: 'ws281x',
        ledCount: presets[0]?.config.ledCount ?? 144,
        pin: 'bladePin',
        colorOrder: 'Color8::GRB',
        powerPins: ['bladePowerPin2', 'bladePowerPin3'],
      },
    ],
  };

  return buildConfigFile(options);
}

// ─── CFX Config Generator ───

function generateCfxFontConfig(preset: ExportPreset, index: number): string {
  const c = preset.config;
  const lines: string[] = [];
  lines.push(`# CFX Font Configuration - ${preset.name}`);
  lines.push(`# Generated by BladeForge`);
  lines.push('');
  lines.push(`[general]`);
  lines.push(`profile=${index + 1}`);
  lines.push(`name=${preset.name}`);
  lines.push('');
  lines.push(`[color]`);
  lines.push(`base=${rgbToCfxHex(c.baseColor.r, c.baseColor.g, c.baseColor.b)}`);
  lines.push(`clash=${rgbToCfxHex(c.clashColor.r, c.clashColor.g, c.clashColor.b)}`);
  lines.push(`lockup=${rgbToCfxHex(c.lockupColor.r, c.lockupColor.g, c.lockupColor.b)}`);
  lines.push(`blast=${rgbToCfxHex(c.blastColor.r, c.blastColor.g, c.blastColor.b)}`);
  lines.push('');
  lines.push(`[ignition]`);
  lines.push(`type=${c.ignition}`);
  lines.push(`duration=${c.ignitionMs}`);
  lines.push('');
  lines.push(`[retraction]`);
  lines.push(`type=${c.retraction}`);
  lines.push(`duration=${c.retractionMs}`);
  return lines.join('\n');
}

function generateCfxMainConfig(presets: ExportPreset[]): string {
  const lines: string[] = [];
  lines.push('# CFX Saber Configuration');
  lines.push('# Generated by BladeForge');
  lines.push('');
  lines.push(`[general]`);
  lines.push(`profiles=${presets.length}`);
  lines.push(`volume=80`);
  lines.push(`clash_sensitivity=4`);
  lines.push('');
  for (let i = 0; i < presets.length; i++) {
    lines.push(`[profile${i + 1}]`);
    lines.push(`font=font${i + 1}`);
    lines.push(`name=${presets[i].name}`);
    lines.push(`color=${rgbToCfxHex(presets[i].config.baseColor.r, presets[i].config.baseColor.g, presets[i].config.baseColor.b)}`);
    lines.push('');
  }
  return lines.join('\n');
}

// ─── Golden Harvest Config Generator ───

function generateGoldenHarvestConfig(presets: ExportPreset[]): string {
  const lines: string[] = [];
  lines.push('; Golden Harvest V3 Configuration');
  lines.push('; Generated by BladeForge');
  lines.push('');
  lines.push('[board]');
  lines.push('version=3');
  lines.push(`profiles=${presets.length}`);
  lines.push('volume=80');
  lines.push('');
  for (let i = 0; i < presets.length; i++) {
    const c = presets[i].config;
    lines.push(`[profile${i + 1}]`);
    lines.push(`name=${presets[i].name}`);
    lines.push(`font=font${i + 1}`);
    lines.push(`color_base=${c.baseColor.r},${c.baseColor.g},${c.baseColor.b}`);
    lines.push(`color_clash=${c.clashColor.r},${c.clashColor.g},${c.clashColor.b}`);
    lines.push(`color_lockup=${c.lockupColor.r},${c.lockupColor.g},${c.lockupColor.b}`);
    lines.push(`ignition_type=${c.ignition}`);
    lines.push(`ignition_time=${c.ignitionMs}`);
    lines.push(`retraction_type=${c.retraction}`);
    lines.push(`retraction_time=${c.retractionMs}`);
    lines.push('');
  }
  return lines.join('\n');
}

// ─── Xenopixel Config Generator ───

function generateXenopixelConfig(presets: ExportPreset[]): Record<string, unknown> {
  return {
    generator: 'BladeForge',
    version: '1.0',
    profiles: presets.map((p, i) => {
      const c = p.config;
      return {
        id: i + 1,
        name: p.name,
        font: `font${i + 1}`,
        color: {
          base: [c.baseColor.r, c.baseColor.g, c.baseColor.b],
          clash: [c.clashColor.r, c.clashColor.g, c.clashColor.b],
          lockup: [c.lockupColor.r, c.lockupColor.g, c.lockupColor.b],
          blast: [c.blastColor.r, c.blastColor.g, c.blastColor.b],
        },
        ignition: { type: c.ignition, duration: c.ignitionMs },
        retraction: { type: c.retraction, duration: c.retractionMs },
        style: c.style,
        ledCount: c.ledCount,
      };
    }),
  };
}

// ─── ZIP Builders ───

function addFontFolder(zip: JSZip, folderName: string, soundFiles?: File[]): void {
  const folder = zip.folder(folderName);
  if (!folder) return;

  // Add sound files if provided
  if (soundFiles && soundFiles.length > 0) {
    for (const file of soundFiles) {
      folder.file(file.name, file);
    }
  } else {
    // Create an empty placeholder so the folder exists in the ZIP
    folder.file('.bladeforge', 'BladeForge sound font placeholder\n');
  }
}

/**
 * Create a ZIP archive for a single preset targeting a specific board.
 */
export async function exportPresetZip(options: ExportOptions): Promise<Blob> {
  return exportMultiPresetZip({
    presets: [options.preset],
    boardId: options.boardId,
    boardOptions: options.boardOptions,
  });
}

/**
 * Create a ZIP archive for multiple presets targeting a specific board.
 */
export async function exportMultiPresetZip(options: MultiExportOptions): Promise<Blob> {
  const { presets, boardId, boardOptions } = options;
  const zip = new JSZip();

  switch (boardId) {
    case 'proffie': {
      // config.h at root
      const configH = generateProffieConfig(presets, boardOptions);
      zip.file('config.h', configH);

      // Font folders: font1/, font2/, ...
      for (let i = 0; i < presets.length; i++) {
        const folderName = presets[i].fontName
          ? sanitizeFolderName(presets[i].fontName!)
          : `font${i + 1}`;
        addFontFolder(zip, folderName, presets[i].soundFiles);
      }
      break;
    }

    case 'cfx': {
      // Main config.txt at root
      zip.file('config.txt', generateCfxMainConfig(presets));

      // Per-font folders + config files
      for (let i = 0; i < presets.length; i++) {
        const folderName = `font${i + 1}`;
        addFontFolder(zip, folderName, presets[i].soundFiles);
        zip.file(`${folderName}/config.txt`, generateCfxFontConfig(presets[i], i));
      }
      break;
    }

    case 'golden_harvest': {
      // config.ini at root
      zip.file('config.ini', generateGoldenHarvestConfig(presets));

      // Font folders
      for (let i = 0; i < presets.length; i++) {
        const folderName = `font${i + 1}`;
        addFontFolder(zip, folderName, presets[i].soundFiles);
      }
      break;
    }

    case 'xenopixel': {
      // config.json at root
      const configJson = generateXenopixelConfig(presets);
      zip.file('config.json', JSON.stringify(configJson, null, 2));

      // Font folders
      for (let i = 0; i < presets.length; i++) {
        const folderName = `font${i + 1}`;
        addFontFolder(zip, folderName, presets[i].soundFiles);
      }
      break;
    }
  }

  return zip.generateAsync({ type: 'blob' });
}
