import Link from 'next/link';
import { MarketingShell } from '@/components/marketing/MarketingShell';
import { MarketingHero } from '@/components/marketing/MarketingHero';
import { MarketingSection } from '@/components/marketing/MarketingSection';
import { FeatureCard } from '@/components/marketing/FeatureCard';
import { pageMetadata } from '@/lib/pageMetadata';

export const metadata = pageMetadata({
  title: 'Community',
  description:
    'How to help the KyberStation project — reporting bugs, requesting presets, sharing saber builds, and the current contribution policy for this first public hobby release.',
  path: '/community',
  keywords: [
    'proffieboard community',
    'lightsaber hobbyist',
    'neopixel saber community',
    'kyberstation contribute',
  ],
});

const ISSUES_URL = 'https://github.com/kenkoller/KyberStation/issues';
const BUG_URL =
  'https://github.com/kenkoller/KyberStation/issues/new?template=bug_report.md';
const FEATURE_URL =
  'https://github.com/kenkoller/KyberStation/issues/new?template=feature_request.md';
const REPO_URL = 'https://github.com/kenkoller/KyberStation';

interface RoadmapItem {
  version: string;
  title: string;
  description: string;
}

const ROADMAP: ReadonlyArray<RoadmapItem> = [
  {
    version: 'v0.14.0',
    title: 'Community gallery via GitHub PR',
    description:
      'A curated preset gallery where every saber is a typed file in the repo. Contributors open a pull request; reviews are the moderation; merges are the publication. Planned — not shipped.',
  },
  {
    version: 'v0.14.0',
    title: 'Preset library expansion',
    description:
      'A multi-lane sweep through the Prequel / OT / Sequel eras, Legends / KOTOR / SWTOR deep cuts, animated series, and cross-franchise "inspired by" builds. Goal is to multiply the preset count several times over in one sprint.',
  },
  {
    version: 'v0.15.0',
    title: 'Multi-blade workbench',
    description:
      'A channel-strip editor for dual-blade sabers, saberstaffs, and crossguards. The share format already supports multi-blade — this sprint is the editor side catching up.',
  },
];

interface Recognition {
  name: string;
  contribution: string;
  href?: string;
}

const RECOGNITIONS: ReadonlyArray<Recognition> = [
  {
    name: 'ProffieOS',
    contribution:
      'The GPL-3.0 firmware that every saber generated by this tool ultimately runs. KyberStation emits ProffieOS-compatible C++ and treats its template grammar as the source of truth. Reference material from the project ships alongside the app as an aggregate work.',
    href: 'https://github.com/profezzorn/ProffieOS',
  },
  {
    name: 'Proffieboard',
    contribution:
      'The hardware platform this whole ecosystem is built around. The community that documents, sells, solders, and troubleshoots these boards did the hard work of making Neopixel sabers a thing ordinary hobbyists can actually build.',
    href: 'https://fredrik.hubbe.net/lightsaber/proffieboard.html',
  },
  {
    name: 'Fett263 prop file',
    contribution:
      'The widely-used button and gesture convention KyberStation targets by default. The five-prop-file picker in the editor sits on top of work that others did to make saber controls legible.',
  },
  {
    name: 'The Neopixel saber community',
    contribution:
      'Reddit threads, YouTube tutorials, Discord help channels, forum posts going back years. This project is a UI layer sitting on top of a mountain of collective knowledge. KyberStation is fan-made aggregate tooling — not a replacement for any of it.',
  },
];

export default function CommunityPage() {
  return (
    <MarketingShell>
      <MarketingHero
        eyebrow="01 / COMMUNITY"
        title="Saber-builders helping saber-builders."
        subtitle="KyberStation is a small hobby project and a first public release. The best way to help right now is to try it, break it, and tell us what broke."
      />

      <MarketingSection
        eyebrow="02 / WAYS IN"
        title="How you can help right now."
      >
        <div className="grid md:grid-cols-3 gap-5">
          <FeatureCard
            index="W.01"
            title="Report a bug"
            description="Something render wrong? A ProffieOS export not compile? The WebUSB flow misbehave on your board? File an issue with the bug template — reproduction steps help more than anything."
            bullets={[
              'Use the bug-report template',
              'Include browser + OS + board revision',
              'Attach the Kyber Glyph URL if you can',
            ]}
          />
          <FeatureCard
            index="W.02"
            title="Request a feature or preset"
            description="Missing a blade style from a film, show, or game? Wish the editor surfaced something differently? Feature requests and preset requests both live in the same issue tracker."
            bullets={[
              'Use the feature-request template',
              'Reference screen-capture or concept art if you have it',
              'A rough config is fine — we can refine on review',
            ]}
          />
          <FeatureCard
            index="W.03"
            title="Share your saber"
            description="Every saber in the editor compresses down to a short Kyber Glyph URL. Drop it in a Reddit thread, a Discord channel, or a DM — the other person opens /editor?s=… and sees exactly what you built, offline."
            bullets={[
              'Round-trips every field of the config',
              'No server, no account, no telemetry',
              'Also renders as a scannable QR on the Kyber Crystal',
            ]}
          />
        </div>

        <div className="mt-6 flex flex-wrap gap-3">
          <a
            href={BUG_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center px-4 py-2 rounded-[2px] font-cinematic text-[11px] tracking-[0.22em] uppercase transition-colors"
            style={{
              background: 'rgb(var(--accent) / 0.10)',
              border: '1px solid rgb(var(--accent) / 0.45)',
              color: 'rgb(var(--accent))',
            }}
          >
            Report a bug
          </a>
          <a
            href={FEATURE_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center px-4 py-2 rounded-[2px] border border-border-light text-text-secondary hover:text-text-primary font-cinematic text-[11px] tracking-[0.22em] uppercase transition-colors hover:bg-bg-surface"
          >
            Request a feature
          </a>
        </div>
      </MarketingSection>

      <MarketingSection
        eyebrow="03 / SOURCE + CONTRIBUTIONS"
        title="Contribution policy."
      >
        <div className="max-w-3xl space-y-5 text-[15px] text-text-secondary leading-relaxed">
          <p>
            The source is{' '}
            <strong className="text-text-primary">MIT-licensed</strong> and
            lives on{' '}
            <a
              href={REPO_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline"
            >
              GitHub
            </a>
            . Issues and feature requests are open — anyone can file one, and
            the tracker is where the honest feedback loop happens.
          </p>
          <p>
            Outside pull requests{' '}
            <strong className="text-text-primary">
              are not accepted yet
            </strong>
            . This is the author&rsquo;s first public programming project and
            first GitHub project, and the contribution flow is still being
            worked out — a healthy one means clear review criteria, good tests,
            and a CI gate that catches mistakes before they land. We&rsquo;d
            rather get that right than rush it.
          </p>
          <p>
            The policy gets revisited{' '}
            <strong className="text-text-primary">
              30 days after public launch
            </strong>
            . Until then, the most useful thing anyone can do is report bugs,
            request features, and share what they&rsquo;ve built. Every
            reproducible issue filed shortens the gap between &ldquo;first
            release&rdquo; and &ldquo;ready for outside code contributions.&rdquo;
          </p>
        </div>
      </MarketingSection>

      <MarketingSection
        eyebrow="04 / ROADMAP"
        title="What's coming (planned, not shipped)."
      >
        <div className="grid md:grid-cols-3 gap-5">
          {ROADMAP.map((item) => (
            <FeatureCard
              key={item.title}
              index={item.version}
              title={item.title}
              description={item.description}
              footer="Planned — subject to change"
            />
          ))}
        </div>
        <p className="mt-8 max-w-3xl text-[14px] text-text-muted leading-relaxed">
          These are tracked in the project&rsquo;s CLAUDE.md as planned
          sprints, not commitments. A hobby project ships when it ships. The
          roadmap exists so you know the direction of travel, not the arrival
          time.
        </p>
      </MarketingSection>

      <MarketingSection
        eyebrow="05 / STANDING ON SHOULDERS"
        title="Recognition."
      >
        <div className="max-w-3xl mb-10 text-[15px] text-text-secondary leading-relaxed">
          <p>
            KyberStation exists because other people did a decade of work
            first. It is fan-made aggregate tooling built on top of firmware,
            hardware, prop conventions, and a community that makes Neopixel
            sabers possible in the first place. It is not a replacement for
            any of the projects below.
          </p>
        </div>
        <dl className="max-w-3xl space-y-8">
          {RECOGNITIONS.map((r) => (
            <div
              key={r.name}
              className="border-t border-border-subtle pt-6 first:border-t-0 first:pt-0"
            >
              <dt className="font-cinematic text-base tracking-[0.14em] uppercase text-text-primary mb-3 leading-snug">
                {r.href ? (
                  <a
                    href={r.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-text-primary hover:text-accent transition-colors"
                  >
                    {r.name}
                  </a>
                ) : (
                  r.name
                )}
              </dt>
              <dd className="text-[15px] text-text-secondary leading-relaxed">
                {r.contribution}
              </dd>
            </div>
          ))}
        </dl>
      </MarketingSection>

      <section className="py-14">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <p className="text-sm text-text-muted mb-5">
            Have a bug, a request, or a saber to share?
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <a
              href={ISSUES_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-hum inline-flex items-center justify-center min-w-[200px] px-6 py-2.5 rounded-[2px] font-cinematic text-xs tracking-[0.22em] uppercase transition-colors"
              style={{
                background: 'rgb(var(--accent) / 0.10)',
                border: '1px solid rgb(var(--accent) / 0.45)',
                color: 'rgb(var(--accent))',
              }}
            >
              Open a GitHub issue
            </a>
            <Link
              href="/faq"
              className="btn-hum inline-flex items-center justify-center min-w-[200px] px-6 py-2.5 rounded-[2px] border border-border-light text-text-secondary hover:text-text-primary font-cinematic text-xs tracking-[0.22em] uppercase transition-colors hover:bg-bg-surface"
            >
              Read the FAQ
            </Link>
          </div>
        </div>
      </section>
    </MarketingShell>
  );
}
