import Link from 'next/link';
import { MarketingHeader } from '@/components/marketing/MarketingHeader';
import { MarketingFooter } from '@/components/marketing/MarketingFooter';
import { ScrollReveal } from '@/components/marketing/ScrollReveal';
import { pageMetadata } from '@/lib/marketing/pageMetadata';

export const metadata = pageMetadata({
  title: 'Community',
  description:
    'How to help the KyberStation project — reporting bugs, requesting presets, sharing saber builds, and the current contribution policy for this first public hobby release.',
  path: '/community',
});

const ISSUES_URL = 'https://github.com/kenkoller/KyberStation/issues';
const BUG_URL = 'https://github.com/kenkoller/KyberStation/issues/new?template=bug_report.md';
const FEATURE_URL =
  'https://github.com/kenkoller/KyberStation/issues/new?template=feature_request.md';
const REPO_URL = 'https://github.com/kenkoller/KyberStation';

interface WayIn {
  index: string;
  title: string;
  description: string;
  bullets: string[];
}

const WAYS_IN: ReadonlyArray<WayIn> = [
  {
    index: 'W.01',
    title: 'Report a bug',
    description:
      'Something render wrong? A ProffieOS export not compile? The WebUSB flow misbehave on your board? File an issue with the bug template — reproduction steps help more than anything.',
    bullets: [
      'Use the bug-report template',
      'Include browser + OS + board revision',
      'Attach the Kyber Glyph URL if you can',
    ],
  },
  {
    index: 'W.02',
    title: 'Request a feature or preset',
    description:
      'Missing a blade style from a film, show, or game? Wish the editor surfaced something differently? Feature requests and preset requests both live in the same issue tracker.',
    bullets: [
      'Use the feature-request template',
      'Reference screen-capture or concept art if you have it',
      'A rough config is fine — we can refine on review',
    ],
  },
  {
    index: 'W.03',
    title: 'Share your saber',
    description:
      'Every saber in the editor compresses down to a short Kyber Glyph URL. Drop it in a Reddit thread, a Discord channel, or a DM — the other person opens /editor?s=… and sees exactly what you built, offline.',
    bullets: [
      'Round-trips every field of the config',
      'No server, no account, no telemetry',
      'Also renders as a scannable QR on the Kyber Crystal',
    ],
  },
];

interface RoadmapItem {
  version: string;
  title: string;
  description: string;
}

const ROADMAP: ReadonlyArray<RoadmapItem> = [
  {
    version: 'v0.17.0',
    title: 'Web Bluetooth wireless updates',
    description:
      'Flash a Proffieboard from the browser without a USB cable. Research doc lives in the repo at docs/research/BLUETOOTH_FEASIBILITY.md. iOS is hard-blocked by Apple WebKit policy; Chromium-family browsers on desktop and Android only. Planned — not shipped.',
  },
  {
    version: 'v0.17.0',
    title: 'Modulation v1.1 full feature set',
    description:
      'Beyond v1.1 Core: full peggy parser surface, all 11 modulators with plates, true drag-to-route polish, hover wire highlighting refinements. Currently 5 modulators have plates active in the UI. Planned — not shipped.',
  },
  {
    version: 'v0.18.0+',
    title: 'Modulation v1.2 Creative',
    description:
      'Modulator chains, macros, an LFO shape library, conditionals, snapshots and scenes, sidechain, probability and random, blade-level user-defined functions, response curves. The expressive layer on top of the v1.1 Core foundation. Planned — not shipped.',
  },
];

interface Recognition {
  name: string;
  contribution: string;
  href?: string;
}

const RECOGNITIONS: ReadonlyArray<Recognition> = [
  {
    name: 'ProffieOS',
    contribution:
      'The GPL-3.0 firmware that every saber generated by this tool ultimately runs. KyberStation emits ProffieOS-compatible C++ and treats its template grammar as the source of truth. Reference material from the project ships alongside the app as an aggregate work.',
    href: 'https://github.com/profezzorn/ProffieOS',
  },
  {
    name: 'Proffieboard',
    contribution:
      'The hardware platform this whole ecosystem is built around. The community that documents, sells, solders, and troubleshoots these boards did the hard work of making Neopixel sabers a thing ordinary hobbyists can actually build.',
    href: 'https://fredrik.hubbe.net/lightsaber/proffieboard.html',
  },
  {
    name: 'Fett263 prop file',
    contribution:
      'The widely-used button and gesture convention KyberStation targets by default. The five-prop-file picker in the editor sits on top of work that others did to make saber controls legible.',
  },
  {
    name: 'The Neopixel saber community',
    contribution:
      'Reddit threads, YouTube tutorials, Discord help channels, forum posts going back years. This project is a UI layer sitting on top of a mountain of collective knowledge. KyberStation is fan-made aggregate tooling — not a replacement for any of it.',
  },
];

export default function CommunityPage() {
  return (
    <main id="main-content" className="min-h-screen flex flex-col">
      <MarketingHeader active="community" />

      <section
        className="relative border-b border-border-subtle py-16 md:py-20"
        aria-labelledby="community-page-heading"
      >
        <div className="max-w-4xl mx-auto px-6 md:px-8 text-center">
          <ScrollReveal>
            <div
              className="font-mono text-xs tracking-widest mb-4 tabular-nums"
              style={{ color: 'rgb(var(--accent))' }}
            >
              01 / COMMUNITY
            </div>
            <h1
              id="community-page-heading"
              className="font-cinematic text-3xl md:text-5xl tracking-[0.08em] font-semibold uppercase text-text-primary mb-5"
            >
              Saber-builders helping saber-builders.
            </h1>
            <p className="font-sans text-[15px] md:text-base leading-relaxed text-text-secondary max-w-2xl mx-auto">
              KyberStation is a small hobby project and a first public release.
              The best way to help right now is to try it, break it, and tell us
              what broke.
            </p>
          </ScrollReveal>
        </div>
      </section>

      <section
        id="ways-in"
        className="py-12 md:py-16 border-b border-border-subtle scroll-mt-24"
        aria-labelledby="ways-in-heading"
      >
        <div className="max-w-4xl mx-auto px-6 md:px-8">
          <ScrollReveal>
            <header className="mb-10">
              <div
                className="font-mono text-xs tracking-widest mb-3 tabular-nums"
                style={{ color: 'rgb(var(--accent))' }}
              >
                02 / WAYS IN
              </div>
              <h2
                id="ways-in-heading"
                className="font-sans text-xl md:text-2xl tracking-[0.08em] font-semibold uppercase text-text-primary"
              >
                How you can help right now.
              </h2>
            </header>
          </ScrollReveal>

          <div className="grid md:grid-cols-3 gap-5">
            {WAYS_IN.map((way) => (
              <article
                key={way.index}
                className="border border-border-subtle bg-bg-surface p-5 md:p-6 flex flex-col"
                style={{ borderRadius: 'var(--r-chrome, 2px)' }}
              >
                <div
                  className="font-mono text-[11px] tracking-widest mb-3 tabular-nums"
                  style={{ color: 'rgb(var(--accent))' }}
                >
                  {way.index}
                </div>
                <h3 className="font-sans text-base tracking-[0.06em] font-semibold uppercase text-text-primary mb-3">
                  {way.title}
                </h3>
                <p className="font-sans text-[14px] leading-relaxed text-text-secondary mb-4">
                  {way.description}
                </p>
                <ul className="space-y-2 text-text-secondary text-[13px] leading-relaxed mt-auto">
                  {way.bullets.map((bullet) => (
                    <li key={bullet} className="flex gap-2">
                      <span
                        aria-hidden="true"
                        className="font-mono shrink-0 mt-[2px]"
                        style={{ color: 'rgb(var(--accent) / 0.85)' }}
                      >
                        ◆
                      </span>
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </article>
            ))}
          </div>

          <div className="mt-8 flex flex-wrap gap-3">
            <a
              href={BUG_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center px-4 py-2 font-cinematic text-[11px] tracking-[0.22em] uppercase transition-colors"
              style={{
                background: 'rgb(var(--accent) / 0.10)',
                border: '1px solid rgb(var(--accent) / 0.45)',
                color: 'rgb(var(--accent))',
                borderRadius: 'var(--r-chrome, 2px)',
              }}
            >
              Report a bug
            </a>
            <a
              href={FEATURE_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center px-4 py-2 border border-border-light text-text-secondary hover:text-text-primary font-cinematic text-[11px] tracking-[0.22em] uppercase transition-colors hover:bg-bg-surface"
              style={{ borderRadius: 'var(--r-chrome, 2px)' }}
            >
              Request a feature
            </a>
          </div>
        </div>
      </section>

      <section
        id="contribution-policy"
        className="py-12 md:py-16 border-b border-border-subtle scroll-mt-24"
        aria-labelledby="contribution-policy-heading"
      >
        <div className="max-w-4xl mx-auto px-6 md:px-8">
          <ScrollReveal>
            <header className="mb-8">
              <div
                className="font-mono text-xs tracking-widest mb-3 tabular-nums"
                style={{ color: 'rgb(var(--accent))' }}
              >
                03 / SOURCE + CONTRIBUTIONS
              </div>
              <h2
                id="contribution-policy-heading"
                className="font-sans text-xl md:text-2xl tracking-[0.08em] font-semibold uppercase text-text-primary"
              >
                Contribution policy.
              </h2>
            </header>
          </ScrollReveal>

          <div className="max-w-3xl space-y-5 text-[15px] text-text-secondary leading-relaxed">
            <p>
              The source is{' '}
              <strong className="text-text-primary">MIT-licensed</strong> and
              lives on{' '}
              <a
                href={REPO_URL}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent hover:underline"
              >
                GitHub
              </a>
              . Issues and feature requests are open — anyone can file one, and
              the tracker is where the honest feedback loop happens.
            </p>
            <p>
              Outside pull requests{' '}
              <strong className="text-text-primary">
                are not accepted yet
              </strong>
              . This is the author&rsquo;s first public programming project and
              first GitHub project, and the contribution flow is still being
              worked out — a healthy one means clear review criteria, good
              tests, and a CI gate that catches mistakes before they land.
              We&rsquo;d rather get that right than rush it.
            </p>
            <p>
              The policy gets revisited{' '}
              <strong className="text-text-primary">
                30 days after public launch
              </strong>
              . Until then, the most useful thing anyone can do is report bugs,
              request features, and share what they&rsquo;ve built. Every
              reproducible issue filed shortens the gap between &ldquo;first
              release&rdquo; and &ldquo;ready for outside code
              contributions.&rdquo;
            </p>
          </div>
        </div>
      </section>

      <section
        id="roadmap"
        className="py-12 md:py-16 border-b border-border-subtle scroll-mt-24"
        aria-labelledby="roadmap-heading"
      >
        <div className="max-w-4xl mx-auto px-6 md:px-8">
          <ScrollReveal>
            <header className="mb-10">
              <div
                className="font-mono text-xs tracking-widest mb-3 tabular-nums"
                style={{ color: 'rgb(var(--accent))' }}
              >
                04 / ROADMAP
              </div>
              <h2
                id="roadmap-heading"
                className="font-sans text-xl md:text-2xl tracking-[0.08em] font-semibold uppercase text-text-primary"
              >
                What&rsquo;s coming (planned, not shipped).
              </h2>
            </header>
          </ScrollReveal>

          <div className="grid md:grid-cols-3 gap-5">
            {ROADMAP.map((item) => (
              <article
                key={item.title}
                className="border border-border-subtle bg-bg-surface p-5 md:p-6 flex flex-col"
                style={{ borderRadius: 'var(--r-chrome, 2px)' }}
              >
                <div
                  className="font-mono text-[11px] tracking-widest mb-3 tabular-nums"
                  style={{ color: 'rgb(var(--accent))' }}
                >
                  {item.version}
                </div>
                <h3 className="font-sans text-base tracking-[0.06em] font-semibold uppercase text-text-primary mb-3">
                  {item.title}
                </h3>
                <p className="font-sans text-[14px] leading-relaxed text-text-secondary flex-1">
                  {item.description}
                </p>
                <p className="font-mono text-[11px] tracking-widest text-text-muted uppercase mt-4">
                  Planned — subject to change
                </p>
              </article>
            ))}
          </div>

          <p className="mt-8 max-w-3xl text-[14px] text-text-muted leading-relaxed">
            These are tracked in the project&rsquo;s repo as planned sprints,
            not commitments. A hobby project ships when it ships. The roadmap
            exists so you know the direction of travel, not the arrival time.
          </p>
        </div>
      </section>

      <section
        id="recognition"
        className="py-12 md:py-16 border-b border-border-subtle scroll-mt-24"
        aria-labelledby="recognition-heading"
      >
        <div className="max-w-4xl mx-auto px-6 md:px-8">
          <ScrollReveal>
            <header className="mb-8">
              <div
                className="font-mono text-xs tracking-widest mb-3 tabular-nums"
                style={{ color: 'rgb(var(--accent))' }}
              >
                05 / STANDING ON SHOULDERS
              </div>
              <h2
                id="recognition-heading"
                className="font-sans text-xl md:text-2xl tracking-[0.08em] font-semibold uppercase text-text-primary"
              >
                Recognition.
              </h2>
            </header>
          </ScrollReveal>

          <div className="max-w-3xl mb-10 text-[15px] text-text-secondary leading-relaxed">
            <p>
              KyberStation exists because other people did a decade of work
              first. It is fan-made aggregate tooling built on top of firmware,
              hardware, prop conventions, and a community that makes Neopixel
              sabers possible in the first place. It is not a replacement for
              any of the projects below.
            </p>
          </div>
          <dl className="max-w-3xl space-y-8">
            {RECOGNITIONS.map((r) => (
              <div
                key={r.name}
                className="border-t border-border-subtle pt-6 first:border-t-0 first:pt-0"
              >
                <dt className="font-cinematic text-base tracking-[0.14em] uppercase text-text-primary mb-3 leading-snug">
                  {r.href ? (
                    <a
                      href={r.href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-text-primary hover:text-accent transition-colors"
                    >
                      {r.name}
                    </a>
                  ) : (
                    r.name
                  )}
                </dt>
                <dd className="text-[15px] text-text-secondary leading-relaxed">
                  {r.contribution}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      <section className="py-14">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <p className="text-sm text-text-muted mb-5">
            Have a bug, a request, or a saber to share?
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <a
              href={ISSUES_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center min-w-[200px] px-6 py-2.5 font-cinematic text-xs tracking-[0.22em] uppercase transition-colors"
              style={{
                background: 'rgb(var(--accent) / 0.10)',
                border: '1px solid rgb(var(--accent) / 0.45)',
                color: 'rgb(var(--accent))',
                borderRadius: 'var(--r-chrome, 2px)',
              }}
            >
              Open a GitHub issue
            </a>
            <Link
              href="/faq"
              className="inline-flex items-center justify-center min-w-[200px] px-6 py-2.5 border border-border-light text-text-secondary hover:text-text-primary font-cinematic text-xs tracking-[0.22em] uppercase transition-colors hover:bg-bg-surface"
              style={{ borderRadius: 'var(--r-chrome, 2px)' }}
            >
              Read the FAQ
            </Link>
          </div>
        </div>
      </section>

      <MarketingFooter />
    </main>
  );
}
