import type { Preset } from '../../types.js';

/**
 * DC pop-culture tribute presets.
 *
 * Fan reinterpretations of the Green Lantern Emotional Spectrum and other
 * DC artifacts as lightsaber blades. Each Lantern Corps color represents
 * a different facet of the emotional electromagnetic spectrum.
 *
 * Continuity: `pop-culture`. Era fallback: `expanded-universe`.
 */
export const DC_PRESETS: Preset[] = [
  // ── Green Lantern Emotional Spectrum ────────────────────────────

  {
    id: 'pop-dc-green-lantern',
    name: 'Green Lantern (Willpower)',
    character: 'Hal Jordan / Green Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Willpower, channeled by the Guardians of Oa. A warm confident emerald green — the will to act despite fear.",
    hiltNotes: 'Power ring emblem embedded in the pommel; lantern battery grip.',
    config: {
      name: 'Willpower',
      baseColor: { r: 0, g: 255, b: 100 },
      clashColor: { r: 200, g: 255, b: 220 },
      lockupColor: { r: 150, g: 255, b: 180 },
      blastColor: { r: 230, g: 255, b: 240 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-yellow-lantern',
    name: 'Yellow Lantern (Fear)',
    character: 'Sinestro Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Fear, weaponized by Sinestro. A sickly yellow-gold, corrupted at its edges — power that knows how to hurt.",
    hiltNotes: 'Sinestro Corps insignia; black-and-yellow chevron grip.',
    config: {
      name: 'Fear',
      baseColor: { r: 255, g: 200, b: 20 },
      clashColor: { r: 255, g: 240, b: 180 },
      lockupColor: { r: 255, g: 220, b: 100 },
      blastColor: { r: 255, g: 235, b: 160 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.3,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.15,
    },
  },

  {
    id: 'pop-dc-red-lantern',
    name: 'Red Lantern (Rage)',
    character: 'Atrocitus / Red Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Rage, burning in the hearts of those with cause for vengeance. Molten blood-red with flickering coronal flares.",
    hiltNotes: 'Skull-and-crossbones Red Lantern emblem; vein-etched crimson grip.',
    config: {
      name: 'Rage',
      baseColor: { r: 220, g: 20, b: 20 },
      clashColor: { r: 255, g: 140, b: 80 },
      lockupColor: { r: 255, g: 60, b: 40 },
      blastColor: { r: 255, g: 180, b: 100 },
      style: 'fire',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 340,
      shimmer: 0.6,
      ledCount: 144,
      swingFxIntensity: 0.6,
      noiseLevel: 0.4,
    },
  },

  {
    id: 'pop-dc-orange-lantern',
    name: 'Orange Lantern (Avarice)',
    character: 'Larfleeze / Agent Orange',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Avarice, hoarded by a single greedy bearer. A harsh bright orange — the color of mine, mine, mine.",
    hiltNotes: 'Over-ornate hoarded-treasure grip; orange Lantern emblem.',
    config: {
      name: 'Avarice',
      baseColor: { r: 255, g: 130, b: 0 },
      clashColor: { r: 255, g: 220, b: 140 },
      lockupColor: { r: 255, g: 180, b: 80 },
      blastColor: { r: 255, g: 210, b: 120 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 360,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  {
    id: 'pop-dc-blue-lantern',
    name: 'Blue Lantern (Hope)',
    character: 'Saint Walker / Blue Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Hope, brightest in the darkest hour. Clear optimistic sky-blue haloed by the gentle light of dawn.",
    hiltNotes: 'Sunrise-blue Lantern emblem; simple pilgrim grip.',
    config: {
      name: 'Hope',
      baseColor: { r: 50, g: 180, b: 255 },
      clashColor: { r: 220, g: 240, b: 255 },
      lockupColor: { r: 180, g: 220, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 340,
      retractionMs: 440,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-indigo-lantern',
    name: 'Indigo Lantern (Compassion)',
    character: 'Indigo Tribe',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Compassion, wielded by the penitent. A deep steady indigo-violet — empathy rendered into light.",
    hiltNotes: 'Staff-like tribal grip, sigil of the Indigo Tribe.',
    config: {
      name: 'Compassion',
      baseColor: { r: 80, g: 30, b: 200 },
      clashColor: { r: 200, g: 170, b: 255 },
      lockupColor: { r: 150, g: 110, b: 240 },
      blastColor: { r: 220, g: 200, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 460,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.2,
    },
  },

  {
    id: 'pop-dc-violet-lantern',
    name: 'Star Sapphire (Love)',
    character: 'Star Sapphires',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The light of Love, bonded in the Zamaron crystal. A warm pulsing pink-magenta — the heart's own spectrum.",
    hiltNotes: 'Heart-cut Zamaron crystal in the emitter; rose-tinted grip.',
    config: {
      name: 'Love',
      baseColor: { r: 255, g: 50, b: 180 },
      clashColor: { r: 255, g: 200, b: 240 },
      lockupColor: { r: 255, g: 150, b: 210 },
      blastColor: { r: 255, g: 220, b: 245 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Other DC Artifacts ──────────────────────────────────────────

  {
    id: 'pop-dc-godkiller',
    name: 'Godkiller',
    character: 'Wonder Woman',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The sword forged by Hephaestus to slay gods. Silver-steel blade edged by the divine gold of Themyscira.",
    hiltNotes: 'Long-handled Amazonian longsword, gold-wrapped grip, winged crossguard.',
    config: {
      name: 'Godkiller',
      baseColor: { r: 220, g: 225, b: 235 },
      clashColor: { r: 255, g: 230, b: 150 },
      lockupColor: { r: 245, g: 240, b: 220 },
      blastColor: { r: 255, g: 240, b: 180 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  {
    id: 'pop-dc-ankh-of-fate',
    name: "Dr. Fate's Ankh",
    character: 'Doctor Fate',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Helm of Nabu given edge. Ancient Egyptian gold pulsing with the arcane rhythm of Lords of Order.",
    hiltNotes: 'Ankh-shaped pommel, hieroglyph-etched shaft, golden emitter.',
    config: {
      name: 'AnkhOfFate',
      baseColor: { r: 255, g: 195, b: 30 },
      clashColor: { r: 255, g: 245, b: 200 },
      lockupColor: { r: 255, g: 220, b: 120 },
      blastColor: { r: 255, g: 235, b: 170 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 460,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-swamp-thing',
    name: 'Swamp Thing Green',
    character: 'Swamp Thing',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Green itself, manifest. A mossy deep-green blade breathing in the slow rhythm of the Parliament of Trees.",
    hiltNotes: 'Bark-textured grip, root-wrapped emitter, living moss accents.',
    config: {
      name: 'SwampThing',
      baseColor: { r: 40, g: 120, b: 40 },
      clashColor: { r: 180, g: 230, b: 150 },
      lockupColor: { r: 100, g: 180, b: 80 },
      blastColor: { r: 200, g: 240, b: 170 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.15,
    },
  },

  // ── Aquaman — Tidal Trident ─────────────────────────────────────
  {
    id: 'pop-dc-aquaman',
    name: "Aquaman's Tidal Trident",
    character: 'Arthur Curry / Aquaman',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The King of Atlantis's blade is a wave that won't break. Cyan ocean energy rolls along the channel in lockstep with motion, foam-white at the leading edges, deep abyssal blue in the troughs.",
    hiltNotes: 'Triple-pronged trident hilt with carved Atlantean glyphs and sea-glass inlays.',
    config: {
      name: 'AquamanTidal',
      baseColor: { r: 0, g: 160, b: 230 },
      clashColor: { r: 220, g: 250, b: 255 },
      lockupColor: { r: 100, g: 200, b: 255 },
      blastColor: { r: 230, g: 250, b: 255 },
      style: 'tidal',
      ignition: 'wipe',
      retraction: 'drain',
      ignitionMs: 450,
      retractionMs: 700,
      shimmer: 0.22,
      ledCount: 144,
      swingFxIntensity: 0.6,
    },
  },

  // ── Flash — Speedforce Streams ──────────────────────────────────
  {
    id: 'pop-dc-flash',
    name: 'The Flash (Speedforce Stream)',
    character: 'Barry Allen / The Flash',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Speedforce given form as a blade. Streams of yellow-gold lightning-energy rush from hilt to tip at impossible velocity, and they accelerate the harder you swing. The blade is always running.",
    hiltNotes: 'Aerodynamic teardrop hilt with red lightning-bolt grip wrap.',
    config: {
      name: 'FlashStream',
      baseColor: { r: 255, g: 200, b: 0 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 220, b: 60 },
      blastColor: { r: 255, g: 245, b: 200 },
      style: 'torrent',
      ignition: 'flash-fill',
      retraction: 'unravel',
      ignitionMs: 200,
      retractionMs: 350,
      shimmer: 0.24,
      ledCount: 144,
      swingFxIntensity: 0.7,
    },
  },
];
