import type { Preset } from '../../types.js';

/**
 * DC pop-culture tribute presets.
 *
 * Fan reinterpretations of the Green Lantern Emotional Spectrum and other
 * DC artifacts as lightsaber blades. Each Lantern Corps color represents
 * a different facet of the emotional electromagnetic spectrum.
 *
 * Continuity: `pop-culture`. Era fallback: `expanded-universe`.
 */
export const DC_PRESETS: Preset[] = [
  // ── Green Lantern Emotional Spectrum ────────────────────────────

  {
    id: 'pop-dc-green-lantern',
    name: 'Green Lantern (Willpower)',
    character: 'Hal Jordan / Green Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The emerald-green core of the emotional spectrum — Willpower, the will to act despite fear. Issued from Oa's Central Power Battery to every Green Lantern sworn to the Corps' oath, in the brightest day and the blackest night. A confident saturated emerald, stable as a held breath at the moment before commitment.",
    hiltNotes: 'Power ring emblem embedded in the pommel; lantern battery grip.',
    config: {
      name: 'Willpower',
      baseColor: { r: 0, g: 255, b: 100 },
      clashColor: { r: 200, g: 255, b: 220 },
      lockupColor: { r: 150, g: 255, b: 180 },
      blastColor: { r: 230, g: 255, b: 240 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-yellow-lantern',
    name: 'Yellow Lantern (Fear)',
    character: 'Sinestro Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Fear given form — the yellow light of Parallax, weaponized by Sinestro after his exile from the Green Lantern Corps. Sickly yellow-gold with an unstable flicker that brightens around stronger willpower, the way nightmare gathers around someone with the most to lose. The chevron-edged Sinestro Corps oath made luminous.",
    hiltNotes: 'Sinestro Corps insignia; black-and-yellow chevron grip.',
    config: {
      name: 'Fear',
      baseColor: { r: 255, g: 200, b: 20 },
      clashColor: { r: 255, g: 240, b: 180 },
      lockupColor: { r: 255, g: 220, b: 100 },
      blastColor: { r: 255, g: 235, b: 160 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.3,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.15,
    },
  },

  {
    id: 'pop-dc-red-lantern',
    name: 'Red Lantern (Rage)',
    character: 'Atrocitus / Red Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Rage given form — the Red Light born of Atrocitus' grief on Ryut, the spectrum's first true weapon. Molten blood-red with coronal fire-flares licking off the edge; the Red Lantern ring replaces its bearer's heart with burning rage-plasma, and the blade carries that bargain through every swing. Vengeance as luminous element.",
    hiltNotes: 'Skull-and-crossbones Red Lantern emblem; vein-etched crimson grip.',
    config: {
      name: 'Rage',
      baseColor: { r: 220, g: 20, b: 20 },
      clashColor: { r: 255, g: 140, b: 80 },
      lockupColor: { r: 255, g: 60, b: 40 },
      blastColor: { r: 255, g: 180, b: 100 },
      style: 'fire',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 340,
      shimmer: 0.6,
      ledCount: 144,
      swingFxIntensity: 0.6,
      noiseLevel: 0.4,
    },
  },

  {
    id: 'pop-dc-orange-lantern',
    name: 'Orange Lantern (Avarice)',
    character: 'Larfleeze / Agent Orange',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Avarice given form — the Orange Light hoarded by Larfleeze on the planet Okaara, a Corps of one because the bearer refuses to share. Harsh saturated orange, stable on the surface but tense underneath; every captured soul of every previous owner glimmers at the edges as a half-conjured Identity Construct. The Light that means only mine.",
    hiltNotes: 'Over-ornate hoarded-treasure grip; orange Lantern emblem.',
    config: {
      name: 'Avarice',
      baseColor: { r: 255, g: 130, b: 0 },
      clashColor: { r: 255, g: 220, b: 140 },
      lockupColor: { r: 255, g: 180, b: 80 },
      blastColor: { r: 255, g: 210, b: 120 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 360,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.35,
    },
  },

  {
    id: 'pop-dc-blue-lantern',
    name: 'Blue Lantern (Hope)',
    character: 'Saint Walker / Blue Lantern Corps',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Hope given form — the Blue Light worn by Saint Walker and the pilgrim Corps of Odym, the spectrum's most fragile and most stubborn band. A clear optimistic sky-blue with a soft aurora halo of dawn-rose at the edges; the Blue ring's power only ignites alongside a Green Lantern's. Hope alone won't save you, but it makes Willpower stronger.",
    hiltNotes: 'Sunrise-blue Lantern emblem; simple pilgrim grip.',
    config: {
      name: 'Hope',
      baseColor: { r: 50, g: 180, b: 255 },
      clashColor: { r: 220, g: 240, b: 255 },
      lockupColor: { r: 180, g: 220, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 340,
      retractionMs: 440,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-indigo-lantern',
    name: 'Indigo Lantern (Compassion)',
    character: 'Indigo Tribe',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Compassion given form — the Indigo Light wielded by the Indigo Tribe of Nok, a Corps drafted from the spectrum's worst offenders, their crimes overwritten by empathy. Deep steady indigo-violet with a slow stable pulse, the rhythm of penitent breath. The Light that walks in another's footprints before it strikes.",
    hiltNotes: 'Staff-like tribal grip, sigil of the Indigo Tribe.',
    config: {
      name: 'Compassion',
      baseColor: { r: 80, g: 30, b: 200 },
      clashColor: { r: 200, g: 170, b: 255 },
      lockupColor: { r: 150, g: 110, b: 240 },
      blastColor: { r: 220, g: 200, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 460,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.2,
    },
  },

  {
    id: 'pop-dc-violet-lantern',
    name: 'Star Sapphire (Love)',
    character: 'Star Sapphires',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Love given form — the Violet Light wielded by the Star Sapphires of Zamaron, who recruit by encasing the truly-bonded heart in living crystal. Warm pulsing pink-magenta on the slow rhythm of a held lover's heartbeat; gentle at rest, devastating in defense of the one the bearer cannot bear to lose. The heart's own spectrum.",
    hiltNotes: 'Heart-cut Zamaron crystal in the emitter; rose-tinted grip.',
    config: {
      name: 'Love',
      baseColor: { r: 255, g: 50, b: 180 },
      clashColor: { r: 255, g: 200, b: 240 },
      lockupColor: { r: 255, g: 150, b: 210 },
      blastColor: { r: 255, g: 220, b: 245 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  // ── Other DC Artifacts ──────────────────────────────────────────

  {
    id: 'pop-dc-godkiller',
    name: 'Godkiller',
    character: 'Wonder Woman',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The God Killer — forged by Hephaestus at the request of Zeus, kept on Themyscira against the prophesied return of Ares. Silver-steel base flashing into divine Olympian gold on clash; stable in the hand of the rare wielder strong enough to lift it. A blade meant to end immortals rather than humble them.",
    hiltNotes: 'Long-handled Amazonian longsword, gold-wrapped grip, winged crossguard.',
    config: {
      name: 'Godkiller',
      baseColor: { r: 220, g: 225, b: 235 },
      clashColor: { r: 255, g: 230, b: 150 },
      lockupColor: { r: 245, g: 240, b: 220 },
      blastColor: { r: 255, g: 240, b: 180 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  {
    id: 'pop-dc-ankh-of-fate',
    name: "Dr. Fate's Ankh",
    character: 'Doctor Fate',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Helm of Nabu given an edge — the bearer's body lent out to the Lord of Order who has worn the Helm since the First Dynasty. Ancient Egyptian gold with an aurora halo that pulses on the slow rhythm of arcane mathematics rather than mortal pulse. The hieroglyphs on the shaft are not decoration — they are the spell, currently being cast.",
    hiltNotes: 'Ankh-shaped pommel, hieroglyph-etched shaft, golden emitter.',
    config: {
      name: 'AnkhOfFate',
      baseColor: { r: 255, g: 195, b: 30 },
      clashColor: { r: 255, g: 245, b: 200 },
      lockupColor: { r: 255, g: 220, b: 120 },
      blastColor: { r: 255, g: 235, b: 170 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 460,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  {
    id: 'pop-dc-swamp-thing',
    name: 'Swamp Thing Green',
    character: 'Swamp Thing',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Green itself — every chlorophyll cell on Earth, networked through the Parliament of Trees and given a human-shaped avatar. A mossy deep-green blade breathing on a slow circadian pulse, the rhythm of photosynthesis instead of pulse. Cool at rest, deeply alive in motion — the Swamp Thing's stewardship of the Green made visible.",
    hiltNotes: 'Bark-textured grip, root-wrapped emitter, living moss accents.',
    config: {
      name: 'SwampThing',
      baseColor: { r: 40, g: 120, b: 40 },
      clashColor: { r: 180, g: 230, b: 150 },
      lockupColor: { r: 100, g: 180, b: 80 },
      blastColor: { r: 200, g: 240, b: 170 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.15,
    },
  },

  // ── Aquaman — Tidal Trident ─────────────────────────────────────
  {
    id: 'pop-dc-aquaman',
    name: "Aquaman's Tidal Trident",
    character: 'Arthur Curry / Aquaman',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The King of Atlantis's blade is a wave that won't break. Cyan ocean energy rolls along the channel in lockstep with motion, foam-white at the leading edges, deep abyssal blue in the troughs.",
    hiltNotes: 'Triple-pronged trident hilt with carved Atlantean glyphs and sea-glass inlays.',
    config: {
      name: 'AquamanTidal',
      baseColor: { r: 0, g: 160, b: 230 },
      clashColor: { r: 220, g: 250, b: 255 },
      lockupColor: { r: 100, g: 200, b: 255 },
      blastColor: { r: 230, g: 250, b: 255 },
      style: 'tidal',
      ignition: 'wipe',
      retraction: 'drain',
      ignitionMs: 450,
      retractionMs: 700,
      shimmer: 0.22,
      ledCount: 144,
      swingFxIntensity: 0.6,
    },
  },

  // ── Flash — Speedforce Streams ──────────────────────────────────
  {
    id: 'pop-dc-flash',
    name: 'The Flash (Speedforce Stream)',
    character: 'Barry Allen / The Flash',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Speedforce given form as a blade. Streams of yellow-gold lightning-energy rush from hilt to tip at impossible velocity, and they accelerate the harder you swing. The blade is always running.",
    hiltNotes: 'Aerodynamic teardrop hilt with red lightning-bolt grip wrap.',
    config: {
      name: 'FlashStream',
      baseColor: { r: 255, g: 200, b: 0 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 220, b: 60 },
      blastColor: { r: 255, g: 245, b: 200 },
      style: 'torrent',
      ignition: 'flash-fill',
      retraction: 'unravel',
      ignitionMs: 200,
      retractionMs: 350,
      shimmer: 0.24,
      ledCount: 144,
      swingFxIntensity: 0.7,
    },
  },
];
