import type { Preset } from '../../types.js';

/**
 * Final Fantasy + Kingdom Hearts — pop-culture tribute presets.
 *
 * Swords and Keyblades from Square Enix properties reimagined as lightsaber
 * blades. `era: 'expanded-universe'` is the structural fallback since the
 * preset `Era` union is Star-Wars-scoped — `continuity: 'pop-culture'` is the
 * canonical filter.
 */
export const FINAL_FANTASY_PRESETS: Preset[] = [
  {
    id: 'pop-ff-buster-sword',
    name: 'Buster Sword (Materia Glow)',
    character: 'Cloud Strife',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Cloud's iconic slab sword with a green Materia slot pulsing along the edge. Steel-gray base with a Mako-green clash evoking the Lifestream energy of a slotted Materia orb.",
    hiltNotes:
      'Oversized two-handed steel slab with twin Materia slots near the ricasso; wrapped leather grip.',
    config: {
      name: 'BusterSword',
      baseColor: { r: 160, g: 170, b: 180 },
      clashColor: { r: 80, g: 255, b: 140 },
      lockupColor: { r: 120, g: 220, b: 140 },
      blastColor: { r: 200, g: 255, b: 220 },
      dragColor: { r: 60, g: 200, b: 100 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.06,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.03,
    },
  },

  {
    id: 'pop-ff-masamune',
    name: 'Masamune (Sephiroth)',
    character: 'Sephiroth',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Sephiroth's impossibly-long ōdachi. Silver-white blade with a faint lavender aura — the unnatural stillness of a One-Winged Angel. Subtle instability reads as otherworldly presence.",
    hiltNotes:
      'Seven-foot ōdachi with a plain black grip and minimal tsuba. The blade IS the signature; the hilt is understatement.',
    config: {
      name: 'Masamune',
      baseColor: { r: 230, g: 225, b: 245 },
      clashColor: { r: 200, g: 170, b: 255 },
      lockupColor: { r: 210, g: 190, b: 255 },
      blastColor: { r: 245, g: 235, b: 255 },
      dragColor: { r: 180, g: 140, b: 230 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.05,
    },
  },

  {
    id: 'pop-ff-gunblade',
    name: 'Gunblade (Squall)',
    character: 'Squall Leonhart',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Squall's Revolver gunblade. Clean blue-steel metallic with a cold, disciplined core. Crisp clash like a hammer falling on a primer — SeeD training, not swordsmanship.",
    hiltNotes:
      'Revolver-chambered grip with a trigger; the blade is a single straight edge tuned for pull-cut kinetics.',
    config: {
      name: 'Gunblade',
      baseColor: { r: 110, g: 160, b: 220 },
      clashColor: { r: 220, g: 240, b: 255 },
      lockupColor: { r: 180, g: 210, b: 240 },
      blastColor: { r: 230, g: 240, b: 255 },
      dragColor: { r: 100, g: 140, b: 200 },
      style: 'stable',
      ignition: 'stab',
      retraction: 'standard',
      ignitionMs: 250,
      retractionMs: 350,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.02,
    },
  },

  {
    id: 'pop-ff-brotherhood',
    name: 'Brotherhood (Noctis)',
    character: 'Noctis Lucis Caelum',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Lucian prince's engraved sword, gift from his best friend. Royal Lucian blue with gold crystal shards catching along the length. Gradient layers the warm-cool duality of the Crystal.",
    hiltNotes:
      'Ornate gold crossguard engraved with the Lucian skull; blue leather grip with a tassel.',
    config: {
      name: 'Brotherhood',
      baseColor: { r: 40, g: 90, b: 220 },
      clashColor: { r: 255, g: 220, b: 100 },
      lockupColor: { r: 230, g: 190, b: 80 },
      blastColor: { r: 255, g: 240, b: 180 },
      dragColor: { r: 220, g: 160, b: 40 },
      style: 'gradient',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 450,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.04,
      gradientStart: { r: 30, g: 70, b: 200 },
      gradientEnd: { r: 255, g: 200, b: 80 },
    },
  },

  {
    id: 'pop-ff-ultima-weapon',
    name: 'Ultima Weapon',
    character: 'Final Fantasy Protagonist',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The franchise's recurring ultimate weapon. Rainbow-iridescent blade spanning the spectrum — a visible oath that power scales with the wielder's spirit. Strongest when the HP bar is full.",
    hiltNotes: 'Crystal-bladed with a gold crossguard; appearance varies by game but the prism is universal.',
    config: {
      name: 'UltimaWeapon',
      baseColor: { r: 200, g: 220, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 255, g: 220, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      dragColor: { r: 255, g: 200, b: 255 },
      style: 'prism',
      ignition: 'flash-fill',
      retraction: 'standard',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.25,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.05,
    },
  },

  {
    id: 'pop-ff-omega-weapon',
    name: 'Omega Weapon',
    character: 'Final Fantasy Superboss',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The franchise's hardest optional fight made manifest. Deep cosmic purple with star-glimmer scattered across the blade like a night sky. Unstable shimmer is ontological dread.",
    hiltNotes: 'Dark iron grip with cosmic accents; the blade looks like it was pulled out of the void.',
    config: {
      name: 'OmegaWeapon',
      baseColor: { r: 60, g: 20, b: 120 },
      clashColor: { r: 200, g: 150, b: 255 },
      lockupColor: { r: 140, g: 80, b: 200 },
      blastColor: { r: 220, g: 200, b: 255 },
      dragColor: { r: 180, g: 80, b: 220 },
      style: 'unstable',
      ignition: 'glitch',
      retraction: 'dissolve',
      ignitionMs: 550,
      retractionMs: 700,
      shimmer: 0.4,
      ledCount: 144,
      swingFxIntensity: 0.45,
      noiseLevel: 0.12,
    },
  },

  {
    id: 'pop-ff-kingdom-key',
    name: 'Kingdom Key',
    character: 'Sora',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Sora's starter Keyblade. Golden-yellow teeth with a silver core, ringed by a soft halo of heart-light. Aurora for the warm guardian glow that answers Sora\'s call.",
    hiltNotes:
      "Silver shaft with a golden key-tooth head and a Mickey-token keychain. The Keyblade chooses its wielder.",
    config: {
      name: 'KingdomKey',
      baseColor: { r: 220, g: 220, b: 230 },
      clashColor: { r: 255, g: 220, b: 80 },
      lockupColor: { r: 255, g: 230, b: 120 },
      blastColor: { r: 255, g: 250, b: 200 },
      dragColor: { r: 220, g: 180, b: 60 },
      style: 'aurora',
      ignition: 'summon',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.04,
    },
  },

  {
    id: 'pop-ff-oblivion',
    name: 'Oblivion Keyblade',
    character: 'Riku / Roxas',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The darkness-aligned counterpart to Oathkeeper. Jet-black shaft with a purple energy bleed. Darksaber shape gives the honest hardware approximation of black-with-emitter-accent; the purple clash carries the Nobody weight.",
    hiltNotes:
      'Black-and-purple crossguard styled as a bat wing; chain ending in a three-pointed crown charm.',
    config: {
      name: 'Oblivion',
      baseColor: { r: 5, g: 5, b: 5 },
      clashColor: { r: 180, g: 80, b: 220 },
      lockupColor: { r: 140, g: 60, b: 180 },
      blastColor: { r: 200, g: 120, b: 240 },
      dragColor: { r: 120, g: 40, b: 180 },
      style: 'darksaber',
      ignition: 'summon',
      retraction: 'dissolve',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.06,
    },
  },

  // ─── Kingdom Hearts Keyblade expansion ───────────────────────────────
  //
  // Kingdom Key + Oblivion shipped earlier (Oblivion uses the darksaber
  // engine path per the 2026-05-01 audit). This batch covers six more
  // iconic Keyblades spanning KH1, KH2, BBS, and KH3.

  // ── Way to the Dawn (Riku) ──
  {
    id: 'pop-kh-way-to-the-dawn',
    name: 'Way to the Dawn (Riku)',
    character: 'Riku',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Riku's redeemed Keyblade, born from the resolution of his Heartless arc. A blade that walks the line between light and dark. Cool blue base with high shimmer captures the ambivalent twilight character — neither pure dawn nor pure dusk.",
    hiltNotes: 'Bat-wing crossguard with an angel-wing on the opposite side; a single dark eye opens at the bell. The Keyblade of duality.',
    config: {
      name: 'WayToTheDawn',
      baseColor: { r: 30, g: 80, b: 180 },
      clashColor: { r: 220, g: 230, b: 255 },
      lockupColor: { r: 100, g: 130, b: 220 },
      blastColor: { r: 200, g: 220, b: 255 },
      dragColor: { r: 60, g: 30, b: 100 },
      style: 'unstable',
      ignition: 'summon',
      retraction: 'fadeout',
      ignitionMs: 420,
      retractionMs: 520,
      shimmer: 0.18,
      ledCount: 144,
      swingFxIntensity: 0.45,
      noiseLevel: 0.06,
    },
  },

  // ── Stormfall (Aqua) ──
  {
    id: 'pop-kh-stormfall-aqua',
    name: 'Stormfall (Aqua)',
    character: 'Aqua',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Master Aqua's primary Keyblade. An ornate ocean-blue blade — water-storm energy in a precise, formal Mistress-of-the-Realm-of-Light shape. Stable style with a measured shimmer for the Keyblade Master who never lost her composure even after a decade in the Realm of Darkness.",
    hiltNotes: 'Curling guard with stylized spray; eight-pointed-star teeth at the bell. The Keyblade most associated with mastery and formality.',
    config: {
      name: 'StormfallAqua',
      baseColor: { r: 60, g: 130, b: 240 },
      clashColor: { r: 220, g: 235, b: 255 },
      lockupColor: { r: 150, g: 200, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      dragColor: { r: 40, g: 100, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 360,
      retractionMs: 420,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.38,
      noiseLevel: 0.04,
    },
  },

  // ── Wayward Wind (Ventus) ──
  {
    id: 'pop-kh-wayward-wind-ventus',
    name: 'Wayward Wind (Ventus)',
    character: 'Ventus',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Ventus's primary Keyblade. A sleek pale-green blade — air, freedom, the Wayward Wind itself. Stable with a quick ignition reflecting Ven's reverse-grip kinetic combat style.",
    hiltNotes: 'Sleek wing-curved guard, geometric wind-spiral teeth at the bell. Always wielded reverse-grip.',
    config: {
      name: 'WaywardWindVentus',
      baseColor: { r: 130, g: 230, b: 130 },
      clashColor: { r: 230, g: 255, b: 220 },
      lockupColor: { r: 180, g: 250, b: 180 },
      blastColor: { r: 240, g: 255, b: 230 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 320,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.04,
    },
  },

  // ── Earthshaker (Terra) ──
  {
    id: 'pop-kh-earthshaker-terra',
    name: 'Earthshaker (Terra)',
    character: 'Terra',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Terra's primary Keyblade — bulky, brown-gold, weighted for the heaviest physical strikes in the BBS trio. Stable with a slow ignition + warm flame-touched clash matching his temper-driven Vanitas-vulnerable arc.",
    hiltNotes: 'Bulky earth-tone hilt with rough-hewn texture; jagged-stone teeth at the bell. The heaviest of the BBS Keyblades.',
    config: {
      name: 'EarthshakerTerra',
      baseColor: { r: 180, g: 130, b: 60 },
      clashColor: { r: 255, g: 220, b: 150 },
      lockupColor: { r: 240, g: 180, b: 80 },
      blastColor: { r: 255, g: 200, b: 120 },
      dragColor: { r: 200, g: 100, b: 0 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 380,
      retractionMs: 480,
      shimmer: 0.07,
      ledCount: 144,
      swingFxIntensity: 0.35,
      noiseLevel: 0.05,
    },
  },

  // ── Star Seeker (Sora KH2) ──
  {
    id: 'pop-kh-star-seeker-sora',
    name: 'Star Seeker (Sora)',
    character: 'Sora',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Sora's KH2 starting Keyblade after the time-skip. Cool azure with golden star teeth at the bell — the Keyblade of the wanderer following stars across worlds. Stable with crisp ignition reflecting Sora's renewed combat readiness.",
    hiltNotes: 'Pale-blue and gold; comet-curve crossguard with five-pointed star teeth. The most explicitly cosmic Keyblade in the franchise.',
    config: {
      name: 'StarSeekerSora',
      baseColor: { r: 60, g: 150, b: 240 },
      clashColor: { r: 255, g: 230, b: 150 },
      lockupColor: { r: 200, g: 220, b: 255 },
      blastColor: { r: 255, g: 240, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 360,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.04,
    },
  },

  // ── Three Wishes (Sora KH1, Agrabah world) ──
  {
    id: 'pop-kh-three-wishes-sora',
    name: 'Three Wishes (Sora)',
    character: 'Sora',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'base',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Sora's first replacement Keyblade in KH1, awarded for clearing Agrabah. Gold-and-purple with a lamp-and-genie motif throughout. Stable with a magical ignite-shimmer reflecting the Genie's blue-flame energy.",
    hiltNotes: 'Curled lamp-handle crossguard, blue-and-gold; teeth shaped like the lamp-spout at the bell. Genie\'s Magic carbon-baked into the metal.',
    config: {
      name: 'ThreeWishesSora',
      baseColor: { r: 255, g: 200, b: 80 },
      clashColor: { r: 100, g: 180, b: 255 },
      lockupColor: { r: 255, g: 220, b: 130 },
      blastColor: { r: 200, g: 220, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 360,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.05,
    },
  },
];
