import type { Preset } from '../../types.js';

/**
 * Marvel MCU pop-culture tribute presets.
 *
 * Fan reinterpretations of Marvel weapons and Infinity Stones as lightsaber
 * blades. Not screen-accurate to any lightsaber appearance — these translate
 * weapon lore (color, energy, temperament) into the Neopixel blade format.
 *
 * Continuity: `pop-culture`. Era fallback: `expanded-universe` (the Preset
 * Era union currently spans Star Wars eras only; pop-culture presets use
 * EU as a neutral bucket until a dedicated era is added).
 */
export const MARVEL_PRESETS: Preset[] = [
  // ── Thor's Arsenal ──────────────────────────────────────────────

  {
    id: 'pop-marvel-mjolnir',
    name: 'Mjolnir',
    character: 'Thor Odinson',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Thor's hammer, forged in the heart of a dying star. A crackling lightning-blue blade haloed by arcing Asgardian energy.",
    hiltNotes: 'Short, heavy grip terminating in the iconic square-faced hammer head.',
    config: {
      name: 'Mjolnir',
      baseColor: { r: 160, g: 210, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 220, g: 240, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 200,
      retractionMs: 300,
      shimmer: 0.5,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.3,
    },
  },

  {
    id: 'pop-marvel-stormbreaker',
    name: 'Stormbreaker',
    character: 'Thor Odinson',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Forged on Nidavellir to summon the Bifrost. Richer and fuller than Mjolnir — a prismatic storm-blue halo over a searing white core.",
    hiltNotes: 'Groot-handled Uru axe; the half-hammer, half-axe silhouette of a thrown star.',
    config: {
      name: 'Stormbreaker',
      baseColor: { r: 140, g: 200, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 200, g: 230, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 220,
      retractionMs: 320,
      shimmer: 0.45,
      ledCount: 144,
      swingFxIntensity: 0.5,
    },
  },

  {
    id: 'pop-marvel-jarnbjorn',
    name: 'Jarnbjorn',
    character: 'Thor Odinson',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Thor's first axe, wielded before Mjolnir and enchanted to pierce even Celestial armor. Cold Asgardian steel with warm forge-gold highlights.",
    hiltNotes: 'Bearded Norse battle-axe on a leather-wrapped shaft.',
    config: {
      name: 'Jarnbjorn',
      baseColor: { r: 200, g: 210, b: 220 },
      clashColor: { r: 255, g: 220, b: 140 },
      lockupColor: { r: 240, g: 220, b: 180 },
      blastColor: { r: 255, g: 240, b: 200 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 280,
      retractionMs: 380,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.3,
    },
  },

  {
    id: 'pop-marvel-gungnir',
    name: 'Gungnir',
    character: 'Odin Borson',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Spear of Odin, symbol of Asgardian royalty. Deep royal purple carved by golden runes of the Allfather.",
    hiltNotes: 'Long ceremonial shaft, ornate golden spearhead with rune etchings.',
    config: {
      name: 'Gungnir',
      baseColor: { r: 120, g: 60, b: 200 },
      clashColor: { r: 255, g: 215, b: 80 },
      lockupColor: { r: 200, g: 160, b: 240 },
      blastColor: { r: 255, g: 220, b: 120 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 400,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.25,
    },
  },

  // ── The Infinity Stones ─────────────────────────────────────────

  {
    id: 'pop-marvel-space-stone',
    name: 'Space Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Tesseract. Electric blue, housing dominion over space itself — a steady current with a hidden teleportation pulse.",
    hiltNotes: 'Cubic blue housing, containment chamber exposed.',
    config: {
      name: 'SpaceStone',
      baseColor: { r: 30, g: 130, b: 255 },
      clashColor: { r: 200, g: 230, b: 255 },
      lockupColor: { r: 150, g: 200, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.15,
      ledCount: 144,
    },
  },

  {
    id: 'pop-marvel-mind-stone',
    name: 'Mind Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Vision's forehead, Loki's scepter. A warm steady yellow-gold glow — thought given form.",
    hiltNotes: 'Prismatic yellow gem set in a sleek golden frame.',
    config: {
      name: 'MindStone',
      baseColor: { r: 255, g: 210, b: 40 },
      clashColor: { r: 255, g: 255, b: 200 },
      lockupColor: { r: 255, g: 230, b: 150 },
      blastColor: { r: 255, g: 240, b: 180 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.06,
      ledCount: 144,
    },
  },

  {
    id: 'pop-marvel-reality-stone',
    name: 'Reality Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Aether, drawn from the Dark World. A liquid blood-red flicker that bends truth around it.",
    hiltNotes: 'Free-flowing crimson liquid in a containment vessel.',
    config: {
      name: 'RealityStone',
      baseColor: { r: 200, g: 20, b: 30 },
      clashColor: { r: 255, g: 100, b: 90 },
      lockupColor: { r: 230, g: 60, b: 70 },
      blastColor: { r: 255, g: 140, b: 130 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 320,
      retractionMs: 420,
      shimmer: 0.4,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  {
    id: 'pop-marvel-power-stone',
    name: 'Power Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Orb of Morag. A vibrant violet blade laced with chaotic lavender arcs — raw destructive potential held barely in check.",
    hiltNotes: 'Spherical containment orb, purple energy visible within.',
    config: {
      name: 'PowerStone',
      baseColor: { r: 170, g: 50, b: 220 },
      clashColor: { r: 255, g: 200, b: 255 },
      lockupColor: { r: 220, g: 150, b: 255 },
      blastColor: { r: 255, g: 180, b: 255 },
      style: 'unstable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 240,
      retractionMs: 340,
      shimmer: 0.55,
      ledCount: 144,
      swingFxIntensity: 0.55,
      noiseLevel: 0.3,
    },
  },

  {
    id: 'pop-marvel-time-stone',
    name: 'Time Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Eye of Agamotto. Emerald green, steady but breathing with the slow rhythm of a clockwork universe.",
    hiltNotes: 'Hinged amulet around the Sanctum Sanctorum aesthetic.',
    config: {
      name: 'TimeStone',
      baseColor: { r: 40, g: 200, b: 90 },
      clashColor: { r: 200, g: 255, b: 200 },
      lockupColor: { r: 150, g: 240, b: 170 },
      blastColor: { r: 220, g: 255, b: 220 },
      style: 'pulse',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 340,
      retractionMs: 440,
      shimmer: 0.12,
      ledCount: 144,
    },
  },

  {
    id: 'pop-marvel-soul-stone',
    name: 'Soul Stone',
    character: 'Infinity Stone',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "A sacrifice on Vormir. Deep calm orange — the quietest of the Stones, holding the weight of every soul ever forfeit.",
    hiltNotes: 'Simple amber housing. No ornament. The cost is enough.',
    config: {
      name: 'SoulStone',
      baseColor: { r: 255, g: 120, b: 20 },
      clashColor: { r: 255, g: 210, b: 150 },
      lockupColor: { r: 255, g: 170, b: 80 },
      blastColor: { r: 255, g: 200, b: 140 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 380,
      retractionMs: 500,
      shimmer: 0.05,
      ledCount: 144,
      swingFxIntensity: 0.15,
    },
  },

  // ── Cursed & Exotic ─────────────────────────────────────────────

  {
    id: 'pop-marvel-ebony-blade',
    name: 'Ebony Blade',
    character: 'Black Knight',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Forged by Merlin from a meteorite. A near-black blade burning with crimson blood-curse runes from emitter to tip — cuts anything, corrupts its wielder.",
    hiltNotes: 'Gothic cruciform hilt, blackened steel, ruby pommel.',
    config: {
      name: 'EbonyBlade',
      baseColor: { r: 20, g: 5, b: 5 },
      clashColor: { r: 255, g: 40, b: 40 },
      lockupColor: { r: 180, g: 20, b: 30 },
      blastColor: { r: 255, g: 80, b: 60 },
      style: 'gradient',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.2,
      ledCount: 144,
      gradientStops: [
        { position: 0.0, color: { r: 30, g: 5, b: 5 } },
        { position: 0.5, color: { r: 120, g: 15, b: 20 } },
        { position: 1.0, color: { r: 220, g: 30, b: 40 } },
      ],
    },
  },

  {
    id: 'pop-marvel-skurge-axe',
    name: "Skurge's Axe",
    character: 'Skurge the Executioner',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Twin-barrel executioner's axe, Asgardian steel paired with M-16s from Tennessee. Cold steel-silver edge, bright white sparks on every impact.",
    hiltNotes: 'Double-headed battle-axe with integrated M-16 rifles along the haft.',
    config: {
      name: 'SkurgeAxe',
      baseColor: { r: 210, g: 215, b: 225 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 240, g: 245, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      style: 'stable',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 260,
      retractionMs: 360,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.4,
    },
  },

  // ── Storm — Lightning-Helix ─────────────────────────────────────
  {
    id: 'pop-marvel-storm',
    name: "Storm's Tempest",
    character: 'Ororo Munroe / Storm',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The X-Men's weather-witch made manifest as a blade. Twin spirals of lightning-blue energy braid up the channel like the funnel of a tornado, brightening with motion. Storm doesn't carry a sword — but if she did.",
    hiltNotes: 'Dark steel hilt with a stylized lightning-bolt clip and white-streak grip wrap.',
    config: {
      name: 'StormTempest',
      baseColor: { r: 180, g: 220, b: 255 },
      clashColor: { r: 255, g: 255, b: 255 },
      lockupColor: { r: 220, g: 240, b: 255 },
      blastColor: { r: 240, g: 250, b: 255 },
      style: 'helix',
      ignition: 'crackle',
      retraction: 'unravel',
      ignitionMs: 350,
      retractionMs: 500,
      shimmer: 0.28,
      ledCount: 144,
      swingFxIntensity: 0.6,
      noiseLevel: 0.12,
    },
  },

  // ── Doctor Strange — Vortex Portal ──────────────────────────────
  {
    id: 'pop-marvel-doctor-strange',
    name: 'Doctor Strange (Mirror Vortex)',
    character: 'Stephen Strange',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Sorcerer Supreme's portal-conjure made into a blade. A spinning vortex of orange-gold mandala light rotating around the core, with sparks at the edge that read like the runes of a circling sling-ring portal.",
    hiltNotes: 'Antique brass hilt with concentric spell-circle inlays around the emitter.',
    config: {
      name: 'DrStrangeVortex',
      baseColor: { r: 255, g: 140, b: 30 },
      clashColor: { r: 255, g: 220, b: 150 },
      lockupColor: { r: 255, g: 180, b: 80 },
      blastColor: { r: 255, g: 230, b: 180 },
      style: 'vortex',
      ignition: 'flash-fill',
      retraction: 'unravel',
      ignitionMs: 500,
      retractionMs: 700,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.55,
    },
  },
];
