import type { Preset } from '../../types.js';

/**
 * The Legend of Zelda — pop-culture tribute presets.
 *
 * Swords from the Zelda franchise reimagined as lightsaber blades.
 * Colors drawn from in-game artwork and manuals; `era: 'expanded-universe'`
 * is the structural fallback since the preset `Era` union is Star-Wars-
 * scoped — `continuity: 'pop-culture'` is the canonical filter.
 */
export const ZELDA_PRESETS: Preset[] = [
  {
    id: 'pop-zelda-master-sword-awakened',
    name: 'Master Sword (Awakened)',
    character: 'Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      'The Blade of Evil\'s Bane at full power. Bright holy blue with a warm golden halo evoking the Triforce\'s divine energy. Aurora adds the Goddess-touched shimmer around the core.',
    hiltNotes:
      'Golden-yellow crossguard with a blue leather-wrapped grip and a triangular pommel jewel. The hilt reads as Hylian ceremonial rather than Jedi utilitarian.',
    config: {
      name: 'MasterSwordAwakened',
      baseColor: { r: 80, g: 150, b: 255 },
      clashColor: { r: 255, g: 230, b: 120 },
      lockupColor: { r: 255, g: 210, b: 100 },
      blastColor: { r: 255, g: 245, b: 200 },
      dragColor: { r: 255, g: 200, b: 60 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 350,
      retractionMs: 450,
      shimmer: 0.08,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.03,
    },
  },

  {
    id: 'pop-zelda-master-sword-dormant',
    name: 'Master Sword (Dormant)',
    character: 'Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      'The Master Sword in its weakened state, before Link restores his courage. Muted blue, lower saturation, a quieter halo. Same soul, less bite.',
    hiltNotes: 'Same Hylian crossguard hilt as the Awakened form; the jewel reads dimmer.',
    config: {
      name: 'MasterSwordDormant',
      baseColor: { r: 60, g: 110, b: 200 },
      clashColor: { r: 200, g: 200, b: 160 },
      lockupColor: { r: 190, g: 180, b: 140 },
      blastColor: { r: 220, g: 220, b: 220 },
      dragColor: { r: 200, g: 170, b: 60 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'standard',
      ignitionMs: 500,
      retractionMs: 600,
      shimmer: 0.04,
      ledCount: 144,
      swingFxIntensity: 0.2,
      noiseLevel: 0.02,
    },
  },

  {
    id: 'pop-zelda-fierce-deity',
    name: 'Fierce Deity Sword',
    character: 'Fierce Deity Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      'The helix-carved blade of the mask\'s avatar from Majora\'s Mask. Silver-white core with a cyan energy spiral. Gradient carries the blade-to-tip chroma shift the double-helix shape implies on real hardware.',
    hiltNotes:
      'Silver twin-helix blade form (represented here as color-shift on a standard Neopixel tube). Hilt reads as ceremonial bone-white.',
    config: {
      name: 'FierceDeity',
      baseColor: { r: 220, g: 235, b: 255 },
      clashColor: { r: 150, g: 240, b: 255 },
      lockupColor: { r: 120, g: 220, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      dragColor: { r: 80, g: 200, b: 255 },
      style: 'gradient',
      ignition: 'center',
      retraction: 'center',
      ignitionMs: 400,
      retractionMs: 500,
      shimmer: 0.1,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.04,
      gradientStart: { r: 230, g: 240, b: 255 },
      gradientEnd: { r: 80, g: 200, b: 255 },
    },
  },

  {
    id: 'pop-zelda-goddess-sword',
    name: 'Goddess Sword',
    character: 'Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'jedi',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      'The pre-Master-Sword blade from Skyward Sword, gifted by the goddess Hylia. Lavender-pink with a silver divine shimmer. Aurora for the heavenly halo.',
    hiltNotes:
      'Silver crossguard with a pink gem in the pommel. Earlier and lighter build than the Master Sword.',
    config: {
      name: 'GoddessSword',
      baseColor: { r: 220, g: 170, b: 240 },
      clashColor: { r: 255, g: 230, b: 255 },
      lockupColor: { r: 240, g: 200, b: 250 },
      blastColor: { r: 255, g: 240, b: 255 },
      dragColor: { r: 220, g: 180, b: 250 },
      style: 'aurora',
      ignition: 'standard',
      retraction: 'fadeout',
      ignitionMs: 400,
      retractionMs: 600,
      shimmer: 0.12,
      ledCount: 144,
      swingFxIntensity: 0.25,
      noiseLevel: 0.04,
    },
  },

  {
    id: 'pop-zelda-biggoron-sacred-flame',
    name: "Biggoron's Sword (Sacred Flame)",
    character: 'Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "The Goron smith's greatsword imbued with Din's Sacred Flame. Orange-red fire trail — fast, volatile, roaring. Crackle ignition evokes the flame catching along the edge.",
    hiltNotes:
      'Massive two-handed grip wrapped in red leather; plain steel crossguard scaled for Goron hands.',
    config: {
      name: 'BiggoronFlame',
      baseColor: { r: 255, g: 90, b: 20 },
      clashColor: { r: 255, g: 220, b: 100 },
      lockupColor: { r: 255, g: 140, b: 40 },
      blastColor: { r: 255, g: 200, b: 80 },
      dragColor: { r: 255, g: 60, b: 0 },
      style: 'fire',
      ignition: 'crackle',
      retraction: 'drain',
      ignitionMs: 450,
      retractionMs: 550,
      shimmer: 0.2,
      ledCount: 144,
      swingFxIntensity: 0.5,
      noiseLevel: 0.08,
      fireSize: 0.7,
    },
  },

  {
    id: 'pop-zelda-trident-of-power',
    name: 'Trident of Power',
    character: 'Ganondorf',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'sith',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      "Ganondorf's golden trident channeling storm energy. Yellow-gold base with a menacing pulse, warm electric crackle on clash. Represented as a single blade on Neopixel hardware.",
    hiltNotes:
      "Three-pronged trident head (represented as blade color only); black-iron haft with carved Gerudo motifs.",
    config: {
      name: 'TridentOfPower',
      baseColor: { r: 255, g: 200, b: 30 },
      clashColor: { r: 255, g: 255, b: 180 },
      lockupColor: { r: 255, g: 180, b: 40 },
      blastColor: { r: 255, g: 230, b: 120 },
      dragColor: { r: 200, g: 140, b: 0 },
      style: 'pulse',
      ignition: 'stab',
      retraction: 'standard',
      ignitionMs: 300,
      retractionMs: 400,
      shimmer: 0.15,
      ledCount: 144,
      swingFxIntensity: 0.4,
      noiseLevel: 0.06,
      pulseSpeed: 0.6,
    },
  },

  {
    id: 'pop-zelda-wind-waker',
    name: 'Wind Waker (Conductor\'s Baton)',
    character: 'Link',
    era: 'expanded-universe',
    continuity: 'pop-culture',
    affiliation: 'neutral',
    tier: 'detailed',
    screenAccurate: false,
    author: 'KyberStation',
    description:
      'The enchanted conductor\'s baton as a conjured wind-energy blade. Bright white with faint cyan flickers — breath of the Goddess of Winds made visible. High shimmer reads as sparkling air.',
    hiltNotes:
      'White-and-gold baton grip, too small to be a traditional sword — the blade is entirely summoned light.',
    config: {
      name: 'WindWaker',
      baseColor: { r: 240, g: 250, b: 255 },
      clashColor: { r: 180, g: 230, b: 255 },
      lockupColor: { r: 200, g: 240, b: 255 },
      blastColor: { r: 255, g: 255, b: 255 },
      dragColor: { r: 150, g: 220, b: 255 },
      style: 'stable',
      ignition: 'spark',
      retraction: 'fadeout',
      ignitionMs: 250,
      retractionMs: 400,
      shimmer: 0.35,
      ledCount: 144,
      swingFxIntensity: 0.3,
      noiseLevel: 0.1,
    },
  },
];
