import type { PresetConfig } from '../types.js';

/**
 * A card preset template is a pre-built collection of presets ready to load
 * onto an SD card. Each template is self-contained: it carries the full
 * BladeConfig for every entry so it works without resolving built-in presets
 * at runtime.
 */
export interface CardTemplateEntry {
  presetName: string;
  fontName: string;
  config: PresetConfig;
  source: { type: 'builtin'; presetId: string };
}

export interface CardTemplate {
  id: string;
  name: string;
  description: string;
  entries: CardTemplateEntry[];
}

// ─── Original Trilogy Essentials ──────────────────────────────────────

export const ORIGINAL_TRILOGY_ESSENTIALS: CardTemplate = {
  id: 'template-ot-essentials',
  name: 'Original Trilogy Essentials',
  description:
    'The core OT sabers: Luke across all three films, Vader, Obi-Wan, and Palpatine. A compact set that covers every major lightsaber scene from Episodes IV–VI.',
  entries: [
    {
      presetName: 'Luke Skywalker (ANH)',
      fontName: 'Luke_ANH',
      source: { type: 'builtin', presetId: 'ot-luke-anh' },
      config: {
        name: 'LukeANH',
        baseColor: { r: 0, g: 135, b: 255 },
        clashColor: { r: 200, g: 220, b: 255 },
        lockupColor: { r: 200, g: 200, b: 255 },
        blastColor: { r: 255, g: 255, b: 255 },
        style: 'rotoscope',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 300,
        retractionMs: 400,
        shimmer: 0.05,
        ledCount: 144,
      },
    },
    {
      presetName: 'Luke Skywalker (ESB)',
      fontName: 'Luke_ESB',
      source: { type: 'builtin', presetId: 'ot-luke-esb' },
      config: {
        name: 'LukeESB',
        baseColor: { r: 0, g: 120, b: 255 },
        clashColor: { r: 180, g: 210, b: 255 },
        lockupColor: { r: 180, g: 200, b: 255 },
        blastColor: { r: 255, g: 255, b: 255 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 300,
        retractionMs: 400,
        shimmer: 0.04,
        ledCount: 144,
      },
    },
    {
      presetName: 'Luke Skywalker (ROTJ)',
      fontName: 'Luke_ROTJ',
      source: { type: 'builtin', presetId: 'ot-luke-rotj' },
      config: {
        name: 'LukeROTJ',
        baseColor: { r: 0, g: 255, b: 0 },
        clashColor: { r: 180, g: 255, b: 180 },
        lockupColor: { r: 200, g: 255, b: 200 },
        blastColor: { r: 255, g: 255, b: 255 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 250,
        retractionMs: 350,
        shimmer: 0.03,
        ledCount: 144,
      },
    },
    {
      presetName: 'Darth Vader',
      fontName: 'Vader',
      source: { type: 'builtin', presetId: 'ot-vader' },
      config: {
        name: 'Vader',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 180, b: 80 },
        lockupColor: { r: 255, g: 100, b: 0 },
        blastColor: { r: 255, g: 200, b: 200 },
        style: 'fire',
        ignition: 'stutter',
        retraction: 'standard',
        ignitionMs: 400,
        retractionMs: 500,
        shimmer: 0.06,
        ledCount: 144,
        fireSize: 0.4,
        sparkRate: 0.3,
        heatSpread: 0.6,
      },
    },
    {
      presetName: 'Obi-Wan Kenobi (ANH)',
      fontName: 'ObiWan_ANH',
      source: { type: 'builtin', presetId: 'ot-obiwan-anh' },
      config: {
        name: 'ObiWanANH',
        baseColor: { r: 0, g: 155, b: 255 },
        clashColor: { r: 200, g: 225, b: 255 },
        lockupColor: { r: 180, g: 210, b: 255 },
        blastColor: { r: 255, g: 255, b: 255 },
        style: 'rotoscope',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 350,
        retractionMs: 450,
        shimmer: 0.08,
        ledCount: 144,
      },
    },
    {
      presetName: 'Emperor Palpatine',
      fontName: 'Palpatine',
      source: { type: 'builtin', presetId: 'ot-palpatine' },
      config: {
        name: 'PalpatineOT',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 150, b: 50 },
        lockupColor: { r: 255, g: 80, b: 0 },
        blastColor: { r: 255, g: 180, b: 180 },
        style: 'aurora',
        ignition: 'spark',
        retraction: 'fadeout',
        ignitionMs: 200,
        retractionMs: 300,
        shimmer: 0.02,
        ledCount: 144,
        waveCount: 4,
        driftSpeed: 0.6,
      },
    },
  ],
};

// ─── Prequel Collection ──────────────────────────────────────────────

export const PREQUEL_COLLECTION: CardTemplate = {
  id: 'template-prequel-collection',
  name: 'Prequel Collection',
  description:
    'The major players of Episodes I–III: Anakin, Obi-Wan, Mace Windu, Yoda, Count Dooku, Darth Maul, and Darth Sidious.',
  entries: [
    {
      presetName: 'Anakin Skywalker',
      fontName: 'Anakin',
      source: { type: 'builtin', presetId: 'prequel-anakin' },
      config: {
        name: 'AnakinEp3',
        baseColor: { r: 0, g: 120, b: 255 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 255, b: 200 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 280,
        retractionMs: 300,
        shimmer: 0.06,
        ledCount: 144,
      },
    },
    {
      presetName: 'Obi-Wan Kenobi (Master)',
      fontName: 'ObiWan',
      source: { type: 'builtin', presetId: 'prequel-obi-wan-ep3' },
      config: {
        name: 'ObiWanEp3',
        baseColor: { r: 0, g: 135, b: 255 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 255, b: 200 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 280,
        retractionMs: 300,
        shimmer: 0.05,
        ledCount: 144,
      },
    },
    {
      presetName: 'Mace Windu',
      fontName: 'Mace_Windu',
      source: { type: 'builtin', presetId: 'prequel-mace-windu' },
      config: {
        name: 'MaceWindu',
        baseColor: { r: 130, g: 0, b: 255 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 200, g: 150, b: 255 },
        style: 'unstable',
        ignition: 'spark',
        retraction: 'standard',
        ignitionMs: 260,
        retractionMs: 280,
        shimmer: 0.25,
        ledCount: 144,
        flicker: 0.6,
      },
    },
    {
      presetName: 'Yoda',
      fontName: 'Yoda',
      source: { type: 'builtin', presetId: 'prequel-yoda' },
      config: {
        name: 'Yoda',
        baseColor: { r: 0, g: 235, b: 20 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 200, g: 255, b: 200 },
        style: 'aurora',
        ignition: 'center',
        retraction: 'center',
        ignitionMs: 250,
        retractionMs: 260,
        shimmer: 0.03,
        ledCount: 144,
        waveCount: 5,
        driftSpeed: 0.3,
      },
    },
    {
      presetName: 'Count Dooku',
      fontName: 'Dooku',
      source: { type: 'builtin', presetId: 'prequel-dooku' },
      config: {
        name: 'Dooku',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 128, b: 128 },
        style: 'stable',
        ignition: 'scroll',
        retraction: 'scroll',
        ignitionMs: 300,
        retractionMs: 320,
        shimmer: 0.04,
        ledCount: 144,
      },
    },
    {
      presetName: 'Darth Maul',
      fontName: 'Maul',
      source: { type: 'builtin', presetId: 'prequel-darth-maul' },
      config: {
        name: 'DarthMaul',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 100, b: 100 },
        style: 'fire',
        ignition: 'scroll',
        retraction: 'scroll',
        ignitionMs: 350,
        retractionMs: 380,
        shimmer: 0.08,
        ledCount: 144,
        fireSize: 0.6,
        sparkRate: 0.5,
        heatSpread: 0.7,
      },
    },
    {
      presetName: 'Darth Sidious',
      fontName: 'Sidious',
      source: { type: 'builtin', presetId: 'prequel-palpatine' },
      config: {
        name: 'Sidious',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 100, b: 100 },
        style: 'pulse',
        ignition: 'spark',
        retraction: 'fadeout',
        ignitionMs: 250,
        retractionMs: 260,
        shimmer: 0.10,
        ledCount: 144,
        pulseSpeed: 1.5,
        pulseMinBright: 0.4,
      },
    },
  ],
};

// ─── Dark Side Pack ──────────────────────────────────────────────────

export const DARK_SIDE_PACK: CardTemplate = {
  id: 'template-dark-side-pack',
  name: 'Dark Side Pack',
  description:
    'All the Sith and dark-side wielders across eras: Vader, Maul, Kylo Ren, Sidious, Ventress, and the Grand Inquisitor.',
  entries: [
    {
      presetName: 'Darth Vader',
      fontName: 'Vader',
      source: { type: 'builtin', presetId: 'ot-vader' },
      config: {
        name: 'Vader',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 180, b: 80 },
        lockupColor: { r: 255, g: 100, b: 0 },
        blastColor: { r: 255, g: 200, b: 200 },
        style: 'fire',
        ignition: 'stutter',
        retraction: 'standard',
        ignitionMs: 400,
        retractionMs: 500,
        shimmer: 0.06,
        ledCount: 144,
        fireSize: 0.4,
        sparkRate: 0.3,
        heatSpread: 0.6,
      },
    },
    {
      presetName: 'Darth Maul',
      fontName: 'Maul',
      source: { type: 'builtin', presetId: 'prequel-darth-maul' },
      config: {
        name: 'DarthMaul',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 100, b: 100 },
        style: 'fire',
        ignition: 'scroll',
        retraction: 'scroll',
        ignitionMs: 350,
        retractionMs: 380,
        shimmer: 0.08,
        ledCount: 144,
        fireSize: 0.6,
        sparkRate: 0.5,
        heatSpread: 0.7,
      },
    },
    {
      presetName: 'Kylo Ren',
      fontName: 'Kylo',
      source: { type: 'builtin', presetId: 'st-kylo-ren' },
      config: {
        name: 'KyloRen',
        baseColor: { r: 255, g: 30, b: 0 },
        clashColor: { r: 255, g: 200, b: 100 },
        lockupColor: { r: 255, g: 130, b: 0 },
        blastColor: { r: 255, g: 220, b: 180 },
        style: 'unstable',
        ignition: 'spark',
        retraction: 'standard',
        ignitionMs: 500,
        retractionMs: 400,
        shimmer: 0.25,
        ledCount: 144,
        unstableIntensity: 0.6,
        crossguard: true,
        quillonLength: 48,
      },
    },
    {
      presetName: 'Darth Sidious',
      fontName: 'Sidious',
      source: { type: 'builtin', presetId: 'prequel-palpatine' },
      config: {
        name: 'Sidious',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 100, b: 100 },
        style: 'pulse',
        ignition: 'spark',
        retraction: 'fadeout',
        ignitionMs: 250,
        retractionMs: 260,
        shimmer: 0.10,
        ledCount: 144,
        pulseSpeed: 1.5,
        pulseMinBright: 0.4,
      },
    },
    {
      presetName: 'Asajj Ventress',
      fontName: 'Ventress',
      source: { type: 'builtin', presetId: 'prequel-asajj-ventress' },
      config: {
        name: 'Ventress',
        baseColor: { r: 255, g: 0, b: 10 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 100, b: 100 },
        style: 'unstable',
        ignition: 'stutter',
        retraction: 'fadeout',
        ignitionMs: 260,
        retractionMs: 280,
        shimmer: 0.08,
        ledCount: 144,
        flicker: 0.5,
      },
    },
    {
      presetName: 'Grand Inquisitor',
      fontName: 'Grand_Inquisitor',
      source: { type: 'builtin', presetId: 'animated-grand-inquisitor-red' },
      config: {
        name: 'GrandInquisitor',
        baseColor: { r: 255, g: 10, b: 0 },
        clashColor: { r: 255, g: 200, b: 150 },
        lockupColor: { r: 255, g: 100, b: 50 },
        blastColor: { r: 255, g: 180, b: 100 },
        style: 'unstable',
        ignition: 'scroll',
        retraction: 'scroll',
        ignitionMs: 350,
        retractionMs: 380,
        shimmer: 0.12,
        ledCount: 144,
        flicker: 0.4,
      },
    },
  ],
};

// ─── Dueling Minimalist ──────────────────────────────────────────────

export const DUELING_MINIMALIST: CardTemplate = {
  id: 'template-dueling-minimalist',
  name: 'Dueling Minimalist',
  description:
    'A lean 4-preset card optimized for low flash usage and fast ignition. Simple, stable styles that look great in motion without taxing the board. Perfect for active duelists.',
  entries: [
    {
      presetName: 'Luke (ROTJ)',
      fontName: 'Luke_ROTJ',
      source: { type: 'builtin', presetId: 'ot-luke-rotj' },
      config: {
        name: 'LukeROTJ',
        baseColor: { r: 0, g: 255, b: 0 },
        clashColor: { r: 180, g: 255, b: 180 },
        lockupColor: { r: 200, g: 255, b: 200 },
        blastColor: { r: 255, g: 255, b: 255 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 250,
        retractionMs: 350,
        shimmer: 0.03,
        ledCount: 144,
      },
    },
    {
      presetName: 'Vader',
      fontName: 'Vader',
      source: { type: 'builtin', presetId: 'ot-vader' },
      config: {
        name: 'VaderDuel',
        baseColor: { r: 255, g: 0, b: 0 },
        clashColor: { r: 255, g: 180, b: 80 },
        lockupColor: { r: 255, g: 100, b: 0 },
        blastColor: { r: 255, g: 200, b: 200 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 300,
        retractionMs: 400,
        shimmer: 0.04,
        ledCount: 144,
      },
    },
    {
      presetName: 'Obi-Wan',
      fontName: 'ObiWan',
      source: { type: 'builtin', presetId: 'prequel-obi-wan-ep3' },
      config: {
        name: 'ObiWanDuel',
        baseColor: { r: 0, g: 135, b: 255 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 255, g: 255, b: 200 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 250,
        retractionMs: 280,
        shimmer: 0.03,
        ledCount: 144,
      },
    },
    {
      presetName: 'Mace Windu',
      fontName: 'Mace_Windu',
      source: { type: 'builtin', presetId: 'prequel-mace-windu' },
      config: {
        name: 'MaceDuel',
        baseColor: { r: 130, g: 0, b: 255 },
        clashColor: { r: 255, g: 255, b: 255 },
        lockupColor: { r: 255, g: 200, b: 0 },
        blastColor: { r: 200, g: 150, b: 255 },
        style: 'stable',
        ignition: 'standard',
        retraction: 'standard',
        ignitionMs: 250,
        retractionMs: 280,
        shimmer: 0.03,
        ledCount: 144,
      },
    },
  ],
};

// ─── All Templates ───────────────────────────────────────────────────

export const CARD_TEMPLATES: CardTemplate[] = [
  ORIGINAL_TRILOGY_ESSENTIALS,
  PREQUEL_COLLECTION,
  DARK_SIDE_PACK,
  DUELING_MINIMALIST,
];
